DarkflameUniverse/DarkflameServer

- dCommon/Diagnostics.cpp
- dScripts/NjMonastryBossInstance.cpp
Windows server setup:
Clang throws errors for Dbghelp and for the usage of auto to define a vector in NjMonastryBossInstance.cpp, fixed and compiled successfully
> Small fixes for windows clang compile

- CMakeVariables.txt
- README.md
as most people will not have access to the DLU client it may be better to have the default net version on 171022 to avoid confusion
> change default network version to unmodded client

- dZoneManager/Zone.cpp
fixes map files not being able to be loaded due to casing differences when extracted using lcdr's tools, fixes #22
> Try to load from original zone path before a lowercased one

- README.md
Personally missed this as this was talked about in the python part, moving it out and under it. to make it easier to read. As i personally and some other most likely won't read it the python part.
> Modified README specifying CMakeVariables outside the Python box

- README.md
The server and client cannot connect when the server is running on a WSL2 distro and the server is set to localhost, due to differences between WSL1 and 2. This won't affect most people, but would have saved me a few hours.
> Important note for WSL2 users

- README.md
This is just to make it more obvious to check the cmake version. RHEL still  likes to prefer cmake 2
> Add note to readme about cmake version to build

- migrations/dlu/0_initial.sql
Adjusts the syntax of 0_initial.sql to be compatible with MySQL while retaining MariaDB support. Changes `CREATE OR REPLACE TABLE` with `DROP TABLE IF EXISTS` + `CREATE TABLE` and wraps the '' in ugc's filename entry in parentheses.
This should close https://github.com/DarkflameUniverse/DarkflameServer/issues/4.
> Make 0_initial.sql compatible with MySQL

- CMakeLists.txt
- dGame/Entity.cpp
- dScripts/AgShipShake.cpp
- dScripts/AgShipShake.h
- dScripts/AgSpaceStuff.cpp
- dScripts/AgSpaceStuff.h
- dScripts/CppScripts.cpp
This should fix the below error on server startup
```
[07-12-21 04:58:49] [CppScripts]: Attempted to load CppScript for 'scripts\ai\AG\L_AG_SHIP_SHAKE.lua', but returned InvalidScript.
```
I have tested myself in game on a new character and verified that the desired functionality is present
The elimination of the error should also help people asking for help (and those providing help) in setting up the server, as they do not go looking for issues in potentially the wrong place (also it's an elimination of an error, which is always nice)
I've also fixed a cmake warning in the PR
> separate AgSpaceStuff and AgShipShake

- dScripts/AgDarklingMech.cpp
- dScripts/AgDarklingMech.h
- dScripts/AmDarklingMech.cpp
- dScripts/BaseEnemyMech.cpp
- dScripts/BaseEnemyMech.h
- dScripts/CppScripts.cpp
- dScripts/VeMech.cpp
Fixed #54. As part of the base enemy mech script its faction should be updated to 4
to make sure it's seen as an enemy by the client. The AgDarklingMech script
has been deleted as its functionality was essentially that of BaseEnemyMech
and thus no longer necessary.
> Update BaseEnemyMech script to change the default faction

- README.md
In my case the client didn't load the fixed, unpacked script and still used the one from the pk. Renaming `res/pack/scripts.pk` to `_scripts.pk` fixed this for me.
Related:
https://www.reddit.com/r/legouniverse/comments/raoj0q/comment/hnony7p/?utm_source=share&utm_medium=web2x&context=3
> Add note to readme for troubleshooting tips with script editing

- dScripts/NsTokenConsoleServer.cpp
Currently when you exchange maelstrom infected bricks at the console you can build out of the anvil at nimbus plaza you receive one token per 25 bricks. There is a prompt ingame that says you should get 5 tokens.
I simply increased the corresponding numbers in the NsTokenConsoleServer.cpp from 1 to 5 and tested these changes on my own server running on Manjaro Linux.
> increased the exchange rate of the nimbus station console to 5 faction tokens for 25 maelstrom infected bricks

- dGame/dBehaviors/AreaOfEffectBehavior.cpp
- dGame/dBehaviors/AreaOfEffectBehavior.h
- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dBehaviors/BehaviorContext.h
- dGame/dBehaviors/ForceMovementBehavior.cpp
- dGame/dBehaviors/ForceMovementBehavior.h
- dScripts/BuccaneerValiantShip.cpp
- dScripts/BuccaneerValiantShip.h
- dScripts/CppScripts.cpp
Adds the ability for the buccaneer valiant to spawn a ship that rams
enemies and smashes them. Next to a script that triggers the ship skill
a few other changes had to be made:
- Force movement behavior server side calculation and sync
- The ship has no physics volume so the FindValidTargets for behaviors
had to be altered to allow ControllablePhysics entities to find entities
within their area. The "target_self" AOE flag has been used to replicate
the old behavior.
Attached is a video of the new behavior. As there were no variables in the BehaviorParameter table wrt the speed of the ship I'm curious to know if the current speed feels right.
Also keen on Wincent and Xipho reviewing the behavior changes I made. I wasn't sure what to test those on. If you have any suggestions let me know. …
> Fix #164: Implement Buccaneer Valiant special ability

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/documentation_improvement.yaml
- .github/ISSUE_TEMPLATE/installation_issue.yaml
- .github/ISSUE_TEMPLATE/performance_issue.yaml
GitHub updated their issue template format, checklists now also need a label attribute.
> Fix issue templates

- README.md
`/instanceinfo` is currently documented as `/instance-info`, which silently fails.
I've tested that `/instanceinfo` works in-game, and that `/instance-info` does not. I don't know if either command was present on live.
(sidenote: would a PR with documentation for the other commands be accepted? I've written up notes for all currently-implemented commands, and would be happy to contribute them back here, either in the readme or as comments in the source or somewhere else.)
> Correct documentation for /instanceinfo

- dScripts/CppScripts.cpp
- dScripts/LegoDieRoll.cpp
- dScripts/LegoDieRoll.h
The Lego Dice item does not complete its roll animation (just spins in the air before disappearing). This is because the client lua script is not implemented server-side. This PR adds the server-side c++ script and header.
IMPORTANT: I was not able to test this with multiple accounts, so I'm not sure if this fixes the animations from the view of other players on the server. This should ideally be tested before merging.
> Implemented die roll animations for the Lego Dice item

- dScripts/BaseRandomServer.cpp
- dScripts/BaseRandomServer.h
Fixed an issue where named enemies on crux prime would no longer spawn by un-commenting a line that was commented out.
I am unsure as to why this was commented out in the first place however un-commenting it does not seem to cause short term issues.
> Crux Prime named enemy fix

- dGame/dComponents/RacingControlComponent.cpp
This fixes the first part of issue #218.
The smashedTimes counter in the RacingPlayerInfo struct was incremented by accident i assume. In Line 696 of the RacingControlComponent.cpp the OnRequestDie method always increments the smashedTimes counter.
I added an if condition to only increment the counter when the noSmashOnReload attribute is set to false. I think this was supposed to be handled like this, because the noSmashOnReload attribute is set to true in Line 694.
I will probably look into the second bug of issue #218, when i get some time off from doing my uni research.
> fixed a bug where the smashedTimes counter was falsely incremented

- dMasterServer/InstanceManager.cpp
- dMasterServer/InstanceManager.h
Made instance creation use previously used ports when available, to prevent
crashes caused by ports being used that are outside of the assigned range.
> Add port recycling to instance creation

- dDatabase/Tables/CDLootMatrixTable.cpp
- dDatabase/Tables/CDLootMatrixTable.h
- dDatabase/Tables/CDLootTableTable.cpp
- dDatabase/Tables/CDLootTableTable.h
- dDatabase/Tables/CDRarityTableTable.cpp
- dDatabase/Tables/CDRarityTableTable.h
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/RacingControlComponent.cpp
- dGame/dComponents/RebuildComponent.cpp
- dGame/dComponents/ScriptedActivityComponent.cpp
- dGame/dInventory/Item.cpp
- dGame/dUtilities/Loot.cpp
- dGame/dUtilities/Loot.h
- dGame/dUtilities/SlashCommandHandler.cpp
- dScripts/ActivityManager.cpp
- dScripts/AgPicnicBlanket.cpp
- dScripts/BaseInteractDropLootServer.cpp
- dScripts/BootyDigServer.cpp
- dScripts/BuccaneerValiantShip.cpp
- dScripts/CppScripts.h
- dScripts/GrowingFlower.cpp
- dScripts/MinigameTreasureChestServer.cpp
- dScripts/NjDragonEmblemChestServer.cpp
- dScripts/SGCannon.cpp
- dScripts/ScriptedPowerupSpawner.cpp
- dScripts/TreasureChestDragonServer.cpp
- dScripts/VeMissionConsole.cpp
- dScripts/WishingWellServer.cpp
- dWorldServer/WorldServer.cpp
- dZoneManager/Level.cpp
This PR is mostly made of repaired code from @averysumner that was never finished and has now been reimplemented.
I have no idea of knowing if these drops are accurate however Krysto (a prominent community member, who knows much more about loot than I) had spent a good amount of time with this build testing the drop rates.
> Make loot accurate to the loot drop rates during live. 

- .github/workflows/build.yml
- CMakePresets.json
This PR adds a github actions workflow for a Linux build as well as a `CMakePresets.json` that is defined by cmake and required by the action ([lukka/run-cmake](https://github.com/lukka/run-cmake)) that is used.
The `CMakePresets.json` file sets `jobs` i.e. the `-j` flag to `2` by default. That corresponds to the hardware as described in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources and cuts the build time in half (about 8 minutes instead of 15).
Warnings end errors are scraped from the log and displayed inline in the GitHub web UI. See <https://github.com/Xiphoseer/DarkflameServer/pull/2/files> for an example. The warnings there are caused by adding `-Wextra`. This may be a good opportunity to tweak the …
> Add GitHub Actions Workflow

- dGame/dUtilities/Loot.cpp
When applied this commit fixes a crash with the loot system due to a missing nullptr check.
> Fix loot crash

- dGame/dComponents/BuffComponent.cpp
- dGame/dComponents/SkillComponent.cpp
- dGame/dComponents/SkillComponent.h
Description:
- Adds an overload for `HandleUnmanaged` that includes the source
- Modifies damage buffs in `BuffComponent.cpp` to also include the source
Motivation and context:
Addresses issue #232 where the surprise beehive inventor skill does not credit kills to the player.
Tested by killing an enemy with the ability and seeing that it now drops loot, which it did not do previously.
[https://streamable.com/btz2vs](https://streamable.com/btz2vs)
> Damage Buff source fix - inventor beehive bug

- dGame/UserManager.cpp
Fixes #322
XML was missing a space between attributes `lzrw` and `stt`.
Tested this roughly and it seems to work as expected. I did not change the code to use tinyxml2 because I am not familiar enough with C++; sorry. No worries in case you don't want to merge this pull request.
> Fix initial character XML being malformed

- dScripts/NtAssemblyTubeServer.cpp
- dScripts/NtParadoxTeleServer.cpp
The Nexus Tower Assembly and Paradox portals stunned players for an excessive amount of time after the "loading in" animation was complete. This corrects the time so the player can move once the animation ends.
> Portal Stun Time Reductions

- dScripts/ZoneNsWaves.cpp
The time was previously 5 seconds, 30 seconds is what it was in live.
> Change the win delay to increase time to get BONS loot

- dGame/UserManager.cpp
- dGame/UserManager.h
This pull request fixes the issue #268 .
Now the characters will get the correct shirt color for shirts such as the space suit from the server following character creation (dark green and medium blue).
The error was probably due to a wrong copy and paste in the code.
Has been tested locally.
> Fix issue #268 : wrong shirt colors in the character selection

- dScripts/ImgBrickConsoleQB.cpp
This mission does take the item away but gives it back to you for some reason.  This has been fixed in this PR.
> Fixed a bug where Chaos Cleaner would accidentally add a Maelstrom Dagger to your inventory

- dGame/dInventory/ItemSetPassiveAbility.cpp
Previously the Bat Lord full set bonus was not implemented at all.  This PR implements the functionality for the full set to properly restore 3 hp on a kill.
> Added Bat Lord Full Set Bonus

- dScripts/ActSharkPlayerDeathTrigger.cpp
Fixed an issue where getting eaten by a shark would accidentally progress the task for entering the Ravencloud gate's left hand side.  
This creates an issue where you are now unable to get the achievement Gate Crasher however this is due to a larger issue that is not easily fixed.
Tested getting killed by a shark on Ubuntu and behavior is as expected; Shark mission progresses and Gate Crasher does not
> Fixed an issue where Gate Crasher task was progressed when eaten by a shark

- dScripts/GfBanana.cpp
Changed the Bananas drop Y spawn height to be 10 Y units lower to prevent bananas from getting stuck on the tree.  Tested on various banana trees in my local instance and had zero issues.
> Changed banana drop spawn Y height to prevent them from getting stuck on the trees

- dScripts/CppScripts.cpp
Fixes #221 
Address an issue where the anchor quickbuilds would not spawn for Crux Prime apes.  I deduced this to being an issue with the script created in cppscripts with the incorrect script being used for them.  The only thing AmNamedDarklingDragon does is make self immune to stuns, which BaseEnemyApe does already.
Tested in my local instance with Roo Morgg and various stromling invader apes.
> Changed Script Created for Apes on Crux Prime to allow for Anchor QuickBuilds

- dMasterServer/MasterServer.cpp
Previously, if a user didn't run the LCDR script to generate a CDServer.sqlite file `./MasterServer` will crash with this error message.
```
Error: no such table: ActivityRewards
Fatal error -1
Stacktrace:
/app/MasterServer[0x414163]
/usr/local/lib64/libstdc++.so.6(+0xb10ea)[0x7f15364ce0ea]
/usr/local/lib64/libstdc++.so.6(+0xb1155)[0x7f15364ce155]
/usr/local/lib64/libstdc++.so.6(+0xb13e8)[0x7f15364ce3e8]
/app/MasterServer[0x40a80c]
/app/MasterServer[0x43fc97]
/app/MasterServer[0x416864]
/app/MasterServer[0x41c81f]
/app/MasterServer[0x4171f6]
/app/MasterServer[0x40bc6d]
```
This issue is caused by a configuration problem, yet causes a traceback and the cryptic message "Error: no such table ActivityRewards"
This message does not tell the user they need to generate the file CDServer.sqlite …
> Clearer Error Message on Misconfiguration

- dGame/dUtilities/SlashCommandHandler.cpp
This removes the need to use the `force` flag when `/testmap`-ing to that zone.
I've also fixed the indentation in this function (so instead of a mix of spaces and tabs it's just spaces).
> Add zone 1700 to list of accessible zones

- dMasterServer/MasterServer.cpp
Unfortunately, Google Cloud Compute Engine does not support the `<filesystem>` library.
Even if the special flag `-lstdc++fs` is passed, the build still fails to link the appropriate functions.
```
cloudshell:~$ g++ -g -lstdc++fs -std=gnu++17 test.cpp
/usr/bin/ld: /tmp/ccYF9KdM.o: in function `std::filesystem::is_regular_file(std::filesystem::__cxx11::path const&)':/usr/include/c++/8/bits/fs_ops.h:213: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'/usr/bin/ld: /tmp/ccYF9KdM.o: in function `std::filesystem::__cxx11::path::path<char [9], std::filesystem::__cxx11::path>(char const (&) [9], std::filesystem::__cxx11::path::format)':/usr/include/c++/8/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'collect2: …
```
> Remove <filesystem> dependency

- dScripts/AgSurvivalBuffStation.cpp
- dScripts/AgSurvivalBuffStation.h
- dScripts/BaseSurvivalServer.cpp
- dScripts/CppScripts.cpp
Fixes #341 
This PR fixes 2 issues:
First was the issue of the buff station just not spawning.  This was due to a missing spawner network activation in the base survival server when starting the waves.
The second issue was the buff station just not doing anything.  This was due to a missing script.  This script was added and its behavior based on that located at [explorer.lu](https://explorer.lu/objects/6412/9).  The behavior involves every 2.5 seconds, [to heal, buff and imagine all players in its radius by 1.  ](https://explorer.lu/skills/behaviors/1784)
Tested on Ubuntu and had zero issues getting achievement progress and buff station is functioning as expected.
> Fixed an issue where the Avant Gardens Survival buff station was not spawning and implemented its' script

- dGame/dBehaviors/AreaOfEffectBehavior.cpp
- dGame/dBehaviors/AreaOfEffectBehavior.h
- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dBehaviors/BehaviorContext.h
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/DestroyableComponent.h
**Description:**
This fixes how entities are targeted during Area of Effect Behaviors. Each AOE Behavior has fields set in the CDClient database to determine who to target. The fields are read in on initialization and are used to filter targets. This fixes issues such as #328 
**Motivation/Context:**
Passive abilities, such as the Samurai's invulnerability at 0 armor, and other in-game effects are handled as an area of effect. The effect targets specific entities based on fields outlined in the CDClient Database. Some behaviors target enemies (such as the buildable sirens in Gnarled Forest), while others target friends (such as the aforementioned Samurai ability). However, there was no logical distinction, and so abilities that should target friends were targeting enemies.
**Types of …
> Fix Area of Effect Behavior Targets

- dGame/dUtilities/SlashCommandHandler.cpp
In the macros folder, the macros use `/setflag on <flag id>` and not `/setflag <flag id>`.  This causes an issue when you run macros to not set the flags correctly.  This PR fixes this issue and allows macros to function fully.
> Added support for flags in macros

- dScripts/CppScripts.cpp
- dScripts/FvBounceOverWall.cpp
- dScripts/FvBounceOverWall.h
Added the missing script for the Gate Crasher mission.  Tested on local ubuntu instance and task was successfully completed without completing other missions.  As of now this must use a forceProgress due to an overlap with the Shark Bite tasks.
Fixes #186
> Added missing script for Gate Crasher mission

- dGame/dUtilities/SlashCommandHandler.cpp
Addressed an issue where the leave-zone command was working outside of instanced zones and was also putting players in the incorrect zone when it was used.  
Tested on personal server with no issues.
> Fixed an issue where leave-zone was working outside of instanced zones

- dGame/Entity.cpp
- dGame/EntityManager.cpp
- dGame/dComponents/RacingControlComponent.cpp
- dGame/dComponents/RacingControlComponent.h
- dGame/dMission/Mission.cpp
- dGame/dMission/MissionTask.cpp
- dGame/dMission/MissionTask.h
- dGame/dMission/MissionTaskType.h
- dGame/dMission/RacingTaskParam.h
- dScripts/FvRaceSmashEggImagineServer.cpp
- dScripts/RaceImagineCrateServer.cpp
- dScripts/RaceImagineCrateServer.h
- dScripts/RaceImaginePowerup.cpp
- dScripts/RaceSmashServer.cpp
- dScripts/RaceSmashServer.h
Previously, most racing achievements either did not progress correctly or did not progress at all.  This PR fixes all of these tasks and allows them all to progress properly.  Bugs unrelated to the achievements functionality will not be in this PR (Ex. Lap times are not properly tracked for the first and possibly second lap making some lap times only possible on lap 3).  
A new enum file has been added that contains named taskparam1 to reduce the amount of magic numbers that are in the original implementation.  
This PR also fixes general grammatical errors found while working on this PR and also has alphabetized includes in files I was working in.
Fixes #218
> Implementing and Fixing All Racing Achievements

- dGame/dComponents/DestroyableComponent.cpp
Added a boolean to check if the player is at zero armor already and if so, do not trigger the passive ability.  Tested on Ubuntu and had zero issues triggering the passive from full armor and the passive did not trigger when at less than zero armor.
Fixes #394
> Added check to prevent accidental sentinel passive proc

- dGame/dComponents/BaseCombatAIComponent.cpp
This PR makes AI far more live accurate than they were before by removing them standing completely still after using any skill.  Now AI will move around during skill cooldowns, making them accurate to how they worked in live.
Tested on Oogway for a few days and responses have been that AI are indeed more live accurate.
> Removed AI Stopping after they use a skill

- dScripts/NjMonastryBossInstance.cpp
Fixes #362 
- Address the issue where the minigame would consume 2 Green Imaginate per play.  Now only 1 is correctly consumed.
- Addresses an issue where the minigame was not initializing properly for instances of more than 1 player.  What was happening was the variable `totalPlayersLoaded` was not adding players correctly to its list and for some reason either overwriting the previous list of players each time or was giving each player their own `totalPlayersLoaded` list.  This caused all players lists to have to wait for the ActivityTimerStart and also defaulted the instance to always being single player, even if there were 2 or more players.
Now the instance variable `totalPlayersLoaded` correctly has the number of players that would be loaded in the instance and starts the activity …
> Frakjaw Battle instance fixes

- docker-compose.yml
Makes config and client resource volumes used by the server read-only to prevent accidental modification, see [Docker documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3).
If I understand it correctly there should by no reason why the server has to modify the configs or client resources. Though please correct me if I am wrong.
> Make some Docker Compose volumes read-only

- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
supervisord, systemd services and the kill command by default send SIGTERM signals to shutdown proccesses. The Master Server should handle the SIGTERM signal the same way as SIGINT to ensure a gracefull shutdown on SIGTERM signal.
I tested this on my ubuntu 20.04 VPS and it works as intended.
> Add handling of SIGTERM

- dWorldServer/WorldServer.cpp
Log when a WorldServer initiates shutdown because the master server connection went missing or wasn't established in the first place.
> Log WorldServer shutdown when MasterServer connection is missing

- dWorldServer/WorldServer.cpp
Only update and log shutdown for missing master connection once.
The log I added in #443 causes spams the log until the main loop terminates. This PR adds a second conditional that prevents this log if `worldShutdownSequenceStarted` is already set.
> Fix spam-log on master disconnect

- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/InventoryComponent.h
Fixes #351 
Addresses an issue where GMs were unable to spawn in cars in non-racing worlds.   Tested all changes in Nimbus Station without any issues.  The way this works is almost identical to how players are loaded into cars for races and loaded out of cars in races.  Dying currently does not work and I dont know how to fix it however unequipping and re-equipping the car fixes the issue and respawns the player.
> Addressed GM Operators not being able to spawn in cars in non-racing worlds

- dGame/dGameMessages/GameMessages.cpp
- dScripts/CppScripts.cpp
- dScripts/MailBoxServer.cpp
- dScripts/MailBoxServer.h
Addresses an issue brought up by @Xiphoseer where the GameMessage for HandleRequestUse had a special case for mailboxes.  This has been addressed and the script for the MailBoxServer has been implemented.  
Tested changes on local ubuntu instance.  No issues were found when interacting with an empty mailbox.
> Addressed special case in GameMessage for interacting with a mailbox

- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/InventoryComponent.h
Fixes #167
Fixes an issue where proxy items would apply their buffs even when those buffs were already being applied by the parent item.  Now proxy items correctly do NOT apply their buffs, but will apply their skills to the player.
Tested on the following items and was getting the correct stats
Imagination Backpack, all Trial Faction gear from Avant Gardens, all 3 Maelstrom-Infused Hoods
> Addressed some proxy items granting duplicate skills

- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/InventoryComponent.h
Fixes an issue where missions that would progress when equipping item proxies would not progress.  Proxies still do not give extra bonuses as intended however missions like [Borrowed Gear](https://explorer.lu/missions/1935) now progress when a proxy is equipped.  This also fixes an issue introduced in #441 where calling new Item() for proxies would incorrectly pass parent->getID() for the isModMoveAndEquip parameter.  @Xiphoseer for review
Tested the following for functionality and bugs:
Mission 1950 and 1935 progress correctly.
Maelstrom infused hoods give the correct bonuses
Imagination Backpack only gives 3 imagination
[Trial Venture Gear](https://explorer.lu/objects/14359) correctly gives only 4 life, 10 armor, 12 imagination
The Serratorizor correctly gives 2 armor and 5 imagination. …
> Fixed mission progression for item proxies

- dGame/dUtilities/SlashCommandHandler.cpp
This PR removes the ability for players under GAME_MASTER_LEVEL_DEVELOPER to use /playanim. Normally I would just push this change, but there has been controversy in various circles about whether or not this should be removed. To me, the choice is clear: there is no reason normal users should have access to a debug command, and it should be removed. I'd like others' opinions on this.
> Remove ability for gmlevel 0 to use /playanim

- dScripts/BaseEnemyApe.cpp
- dScripts/WaveBossApe.cpp
Previously all apes in DLU did all their attacks at once.  Now apes correctly do 1 attack at a time and do not stack them both on top of each other.  Apes are still immune to all stuns from players even with the stun immune being removed.
Tested Crux Prime ape and named ape, Battle of Nimbus Station ape and Gnarled Forest apes and had no issues.
> Addressed incorrect ape attacks

- dGame/UserManager.cpp
- dGame/UserManager.h
Previously, character create used hard coded vectors and ids to get the LOTs for items to be used for character creation.  With this PR the CDServer is queried and the resulting LOT from the query returns the LOT of the shirt that is requested.  This is done by merging the ItemComponent and ComponentsRegistry tables together and getting all LOTs with an ItemComponent of 11.  Then this table is merged with the Objects table where we get the LOT which has an internal note of, for shirts, character create shirt, or for pants, cc pants, and the requested decal and/or color1 the client had chosen.  Should this query return nothing or fail, a default shirt and pants are chosen.  This allows users to add new shirts and pants to the CDServer/cdclient without needing to hard code them.
If this …
> Addressed hard coded character create values for shirts and pants

- dGame/dMission/MissionTask.cpp
- dGame/dMission/RacingTaskParam.h
- dScripts/FvRaceSmashEggImagineServer.cpp
- dScripts/RaceSmashServer.cpp
Missions like [1407](https://explorer.lu-dev.net/missions/1407) and [1406](https://explorer.lu-dev.net/missions/1406) use taskparam1 set to 17 to denote the mission as being smashing a specific smashable in a race.  Also addressed an issue where dragon egg smashables did not count towards generic smashing missions.  This is because the dragon eggs use a different smash server than generic race smashables.
Tested changes in Forbidden Valley and Nimbus Station race and the above missions progress without error.
> Addressed specific race smash missions not progressing

- dScripts/CppScripts.cpp
- dScripts/NtCombatChallengeExplodingDummy.cpp
- dScripts/NtCombatChallengeExplodingDummy.h
Fixes #264 
Implements the script that is attached to the exploding dummy in Nexus Tower Combat Training.  Pretty much a copy paste of the original Combat Dummy script, but with the added behaviors and the self smash after 1 hit.  
Tested on local ubuntu instance.  Other dummies act normal.  Red exploding dummies now correctly explode, and do their respective AOE attack as well as spawn the next dummy when they die.
> Implemented script for exploding dummy in Nexus Tower Combat Training

- dScripts/AgSurvivalBuffStation.cpp
- dScripts/AgSurvivalBuffStation.h
- dScripts/BaseSurvivalServer.cpp
Fixes #422 
Fully implements the buff station and all functions.  Now correctly spawns powerups.
Tested on local instance and the spawner correctly spawns powerups and smashes itself without error.
> Fully implemented Avant Gardens Survival Buff Station

- dScripts/AgSurvivalBuffStation.cpp
For some reason, the faction that I used in testing on my test branch was 6 and this allowed the buff station to work and buff the player as intended however, when testing the merge on live dlu, the correct faction was 1 and not 6.  
Tested the buff station in survival with an instance size of 1 and 2 players on a local server and it correctly healed the player and not enemies.
Edit: this was because between the time that branch was updated and the buff station PRs being made, aoe behaviors was changed.
> Corrected faction for Buff Station

- dGame/dGameMessages/GameMessages.cpp
- migrations/dlu/0_initial.sql
- migrations/dlu/2_reporter_id.sql
Fixes #355 
Made bug reporting more specific by adding a reporter_id column that contains the characterID of the reporting player.  Added a migration to add the column to the existing bug_reports table.  Also changed the stored OtherPlayerID from the LWOOBJID to the characterID.
Tested changed by reporting general bugs through the drop down and reporting other players and had no exceptions and bugs were reported correctly.
> Added more specific bug reporting

- dGame/dComponents/CharacterComponent.cpp
- dGame/dComponents/CharacterComponent.h
- dGame/dMission/Mission.cpp
- dNet/WorldPackets.cpp
- dNet/WorldPackets.h
- dWorldServer/WorldServer.cpp
This PR allows for reputation to be saved in the charxml and adds backwards compatible checks to initialize the save for old characters that did not have the system.  
Tested the following:
new character doesnt crash when loading in
when saving the attribute is added correctly
when loading a character the reputation is updated in passport
when earning reputation the GM correctly updates it on the client side.
> Reputation now saved in charxml 

- dMasterServer/MasterServer.cpp
Previously when starting `MasterServer` with `--account` the database connection was apparently not closed which caused the database to log the following warning:
> DarkflameDatabase        | 2022-01-24 22:14:38 3 [Warning] Aborted connection 3 to db: 'darkflame' user: 'darkflame' host: '172.18.0.5' (Got an error reading communication packets)
The disadvantage with this is that now closing the database connection is logged to console and file, which might be a bit irritating. Should it maybe also log that `--account` was used and log the created account name?
Additionally when handling the shutdown command it previously called `std::exit` instead of breaking the main loop and exiting this way (have not tested this behavior change).
Note that I am not very familiar with C++, so any …
> Fix MasterServer not always closing database connection on exit

- dGame/UserManager.cpp
Previously when the user chose a predefined name, the logging call would simply log an empty string because `name` is empty and their name was only stored in `predefinedName`.
> Fix UserManager not logging chosen name properly

- dGame/TradingManager.cpp
- dGame/dComponents/BuffComponent.h
- dGame/dComponents/ControllablePhysicsComponent.h
- dGame/dComponents/MissionComponent.h
- dGame/dComponents/ModuleAssemblyComponent.h
- dGame/dComponents/MovementAIComponent.h
- dGame/dComponents/VendorComponent.h
- dScripts/AmDrawBridge.h
- dScripts/BaseConsoleTeleportServer.cpp
- dScripts/GfCampfire.h
Resolved numerous compilation warnings on MacOS and also fixed a couple of errors:
Numerous missing overrides for overridden functions
Trading manager was doing an assignment instead of a comparison for some reason so this has been fixed.
BaseConsoleTeleportServer was not returning should the RocketLaunchpadComponents be null.  This has been resolved.
> resolved MacOS compilation warnings

- dGame/dGameMessages/GameMessages.cpp
For some reason when entering a property, the client send a cancelled trade GM to the server which causes a log to be printed out of context. This PR just moved the log so it happens after we check if a trade exists.
> fixed out of context log for launching to properties

- migrations/cdserver/3_plunger_gun_fix.sql
The plunger gun in the database states it currently is a "RightHand" item type however its equipLocation is stated as "special_l".  After discussion with @Xiphoseer we determined this is likely a cdclient error and have created a migration in the cdserver migrations to address the issue.  Tested change with #496 and the plunger gun correctly acted as a left hand item and was put into the correct usage slot.
> Added migration for plunger gun

- dGame/dComponents/InventoryComponent.cpp
When equipping an item that has proxies, previously, we would check if the slot had a skill and remove it first, before even checking if we have a skill to overwrite that slot.  Now we check that we have a skill to put in a slot _first_ before checking if we should remove the skill from a slot.
Fixes #168 
Fixes #438 
Tested by equipping and unequipping the following items:
equipped all trial faction sets 1 after another, then equipping various faction gear sets 1 piece at a time.  Also tested travelling between worlds with proxy items equipped to make sure we were given the skills correctly.  Had no issues on my end and was able to use skills as intended
> Addressed proxy items removing skills

- migrations/dlu/0_initial.sql
Made it so people wont accidentally wipe their database if 0_initial.sql is ever run again.  Tested in the MySQL Workbench and migration ran just fine there and with MariaDB on the CLI.
> Changed 0_initial.sql so it wont accidentally wipe a database if run again

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dDatabase/Database.cpp
- dDatabase/Database.h
- dGame/dComponents/PropertyManagementComponent.h
- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
This PRs main focus is to dramatically speed up server shutdown time.  The main issue was MasterServer was never listening for the packets from the spawned servers that they were finished shutting down, so MasterServer always shutdown via timeout.  WorldServer also was purposely delaying its shutdown by 10 seconds which does not seem necessary.  All servers now correctly shutdown as soon as they are able to without delay, speeding up development efforts.  
A smaller side addition is that when calling Database::Destroy();, a specifier is now passed to say what the source of the destruction is.  Example logs of a shutdown through ctrl + c on property while in edit mode are below.
Fixes #361
Tested shutting down the server with ctrl+c while being in edit mode on a property with newly earned …
> Dramatically speed up server shutdown and specify database destruction source in logging message

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/installation_issue.yaml
- .github/ISSUE_TEMPLATE/performance_issue.yaml
Tries to improve the GitHub issue templates by:
- Requesting the DarkflameServer version
This makes it later easier to find out which version was affected, and whether the bug might have already been fixed.
- Requesting environment information for performance issues reports
Information about the environment might be quite useful when analyzing performance issues.
Feel free to close this pull request in case you do not think that these changes are useful.
> Improve GitHub issue templates

- dGame/Entity.cpp
- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/PetComponent.h
- dGame/dGameMessages/GameMessages.cpp
Previously due to an error, pets were given item components even when pets need to be excluded from having item components.  This would cause serialization issues on the client and the client would lag when loading pets in Nimbus Station and Forbidden valley.  This also fixes the issue with the "You got X number of bricks out of Y!" error.  This was happening because the client does all the work for checking the bricks and if the bricks are all correct, only then does the server send a TrybuildResult.  Otherwise nothing should be sent.  
All work is verified against packet captures from live, lcdr's toolset, and testing.
testing involved 2 clients and various combinations of taming pets and loading pets from bags.  No behavior has changed for pets besides no more lag in the critical …
> Pets no longer cause client hitches in Nimbus Station and Forbidden Valley

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/UserManager.cpp
- dGame/dComponents/InventoryComponent.cpp
- dGame/dMission/Mission.cpp
- dWorldServer/WorldServer.cpp
Addressed a couple of issues with vaults:
1) The players item vault was being initialized to the incorrect size.  According to live data, the player started with 40 slots in the vault for models and items, not 240 for items and 40 for models.
2) Earning bank inventory slots previously did not increase the number of model vault space you had.  This has been corrected and the player now correctly earns model inventory slots for completing bank missions.
3) A retroactive check has been added to ensure the the model vault size matches the item vault size.  
Tested creating a new character and opening the vault and then completing various vault missions that granted size to the vault and the size was updated to all correctly.
> Addressed vault issues

- dGame/dUtilities/SlashCommandHandler.cpp
Removes hard-coded valid zones and checks against the map file exists.
(ignore all the white-space, my linter was overly aggressive, can remove all that if wanted)
Tested with valid maps, invalid maps with no file path in cdserver, and invalid maps with a file path in cdserver but no map on disk
> Dynamically check if zone is viable from existence of file

- dGame/dComponents/RacingControlComponent.cpp
- dGame/dMission/MissionTask.cpp
* Try, Try Again achievement now progresses when the player gets last place in a race of 3 or more players, or when solo racing is enabled.
* Race Series 1 mission from Velocity Lane now progresses correctly.
Tested all changes on a local WSL instance.  Missions progressed as intended from my testing.  Try, Try again checks whether your placing is equal to the number of players loaded(aka last place) Race Series 1 is a bitmask and has some funky checks and logic to make it work, but it works now.
Fixes #501
> Fixed Racing Missions Try, Try again and Race Series 1

- dGame/dGameMessages/GameMessages.cpp
Previously, the only check that the user wasn't trashing more items than they had was clientsided, and this could be bypassed by contacting the server to remove items via a console or the like, and then trashing them before the server could respond, resulting in the count for the items being less than iStackCount. This check prevents that underflow.
> Prevent integer underflow in item removal

- dGame/dComponents/ScriptedActivityComponent.cpp
This pull request fixes solo_racing for Frostburgh's Space Blizzard Racetrack by adding the mapID 1261 to line 31 in ScriptedActivityComponent.cpp. The mapID was taken from here: https://github.com/DarkflameUniverse/DarkflameServer/pull/508/files#diff-37c34a25fc8323cfd31309141b8efee4e67be125b7b0f51fe41b08c244a5f82bR56. Previously enabling solo_racing only affected all other racetracks and not Frostburgh's Space Blizzard Racetrack.
The pull request was tested on a remote Ubuntu server with Frostburgh and Space Blizzard added to cdclient.fdb and CDServer.sqlite.
> Fix solo_racing for Frostburgh's Space Blizzard Racetrack

- dGame/dComponents/DestroyableComponent.cpp
- dGame/dMission/Mission.cpp
The popup for earning a life container in live now shows up.  The one for imagination does as well, however due to a client bug it doesnt show up on re-logs.
> Pop up now appears for life containers

- dGame/dBehaviors/BasicAttackBehavior.cpp
- dGame/dBehaviors/BehaviorContext.h
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/DestroyableComponent.h
- dGame/dComponents/SkillComponent.cpp
- dGame/dComponents/SkillComponent.h
- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dMission/MissionTask.cpp
Addressed an issue where the Spinjitzu Initiate achievement would not progress.  This also allows mission tasks that specify that the player must get a kill on an enemy with a skill to progress.  
Tested mission 1935 (Equip trial faction gear) and 1139 (Spinjitzu Initiate) and both missions progressed and completed as intended and did not progress each other incorrectly.
Fixes #517
> Skill Task changes (also fixes Spinjitzu Initiate)

- dGame/dBehaviors/OverTimeBehavior.cpp
- dGame/dBehaviors/OverTimeBehavior.h
It was recently discovered by Krysto that the OverTime behaviors' action is actually a skillID and not a behaviorID.  This is addressed and corrects the behaviors for all items that use OverTime behaviors.
Tested the following items and they all functioned as expected
Samurai bow 3
Daredevil flareguns 3 (Fig on Fire and DareDevil bullet)
clod chucking shovel
net of bees
bag of glitter
Sorcerer hat 3
These items all now function as expected.
> Corrected action for OverTimeBehavior

- dGame/dBehaviors/AndBehavior.cpp
- dGame/dBehaviors/AndBehavior.h
- dGame/dBehaviors/Behavior.cpp
- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dBehaviors/LootBuffBehavior.cpp
- dGame/dBehaviors/LootBuffBehavior.h
- dGame/dComponents/ControllablePhysicsComponent.cpp
- dGame/dComponents/ControllablePhysicsComponent.h
This PR adds the functionality for the LootBuff behavior for passive abilities and for items / item skills.  Details can be found in commit comments
Tested equipping all variations of the LootBuff behavior (passive skills, items, item skills) and all functioned as intended. Tested equipping multiple items with a loot buff and then unequipping them in different orders. Tested adding pickup radii of different values and the server correctly adjusted the pickup radius to the largest one currently equipped.
Fixes #423
> Added LootBuff behavior and serialization

- dScripts/BaseEnemyApe.cpp
When apes were stunned they were not being serialized immediately after getting their armor back, which would cause some de-syncs on the client.  We simply serialize the entity after changing its armor value so the clients know it was changed and dont phantom kill an ape.
Tested on a couple apes on Crux Prime and Gnarled forest and they got their armor back faster than the default (every 5 seconds update from base combat AI component)
> Serialize ape when changing armor value

- dGame/dComponents/RebuildComponent.cpp
- dGame/dComponents/RebuildComponent.h
Corrected an error where the builder was erronously changed to an empty lwoobjid when a quickbuild was completed, causing the builds to no longer jump on completion (if configured to do so.)  Packet captures from live show that we do not want to get rid of the builder during resetting or during completion of the build so the file has been changed to not clear the builder in those cases.
Tested on a few quickbuilds on Avant Gardens and all jumped when completed as expected.  Will be testing other builds as well to see how they work now.
Edit: Tested various builds across Crux Prime and Nexus Tower and the ones that are configured to jump on completion now do so.  Fairly certain there isn't more to test so will merge this in the morning.
Fixes #446
> Quickbuilds jump fix

- dGame/EntityManager.cpp
Simple PR, noticed this while working on the rocket holding one.
Whitespace in here is so inconsistent, please send help.
> Exclude space blizzard from Zone ghosting

- dGame/dComponents/CharacterComponent.cpp
- dGame/dComponents/CharacterComponent.h
- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/PropertyEntranceComponent.cpp
- dGame/dComponents/RocketLaunchLupComponent.cpp
- dGame/dComponents/RocketLaunchpadControlComponent.cpp
- dGame/dComponents/RocketLaunchpadControlComponent.h
- dGame/dGameMessages/GameMessages.cpp
- dGame/dInventory/EquippedItem.h
- dWorldServer/WorldServer.cpp
Implement proper rocket holding at launchpads.
Tested all world launchers with and without rocket.
Tested all property launchers with and without rocket.
Tested LUP launcher with and without rocket.
Tested double clicking or dragging rocket on to each type of launcher as well and interacting with them through <shift>.
In the scenarios above, when the player has a rocket, the launcher works as expected.
World launcher launch immediately
Prop and LUP launchers open then menu and waits, then launch when a selection is made.
When the player has no rocket, no launch sequence happen and no menus are opened.
Tested quitting the game/killing the server while player is holding rocket. Upon next login, player is not stuck holding rocket.
> Proper rocket Holding

- Docker.md
Add link to enabling docker buildkit. Add note to remember to clone submodules.
Cloning submodules note addresses this issue: https://github.com/DarkflameUniverse/DarkflameServer/issues/454
Docker buildkit is required when running this docker compose and will fail without it.
> Update Docker.md with buildkit and submodule notes.

- dGame/dComponents/ScriptedActivityComponent.cpp
Resolves #467 
Tested with mini-games where
* you can enter as one player (no team made)
* Enter with multiple players (with 2 or more a team was made)
* multiplayer racing (with 2 or more a team was made)
* single player racing (no team made)
Things behaved as expected and the minigames played as expected
> Only make teams for minigames if we have more than one participant

- dCommon/LDFFormat.cpp
- dDatabase/Tables/CDItemComponentTable.cpp
- dScripts/BaseFootRaceManager.cpp
- dScripts/NjMonastryBossInstance.cpp
- dScripts/SpawnPetBaseServer.cpp
For Windows, the definition for a long is 32 bits, not 64 bits like on other operating systems.  This caused an issue on Windows only where a number larger than 32 bits was attempted to be converted to a long, the WorldServer would crash.  This commit replaces all instances of `stol` with `stoull` to further define a long and reduce ambiguity of number length.
Tested changes on Windows and WSL servers and no issues were found.
Fixes #572 
If one of the two requested reviewers could review these conversions to make sure I interpreted the types correctly and am correctly converting them, that'd be great.
> Corrected ambiguous string to number conversion 

- dGame/dComponents/DestroyableComponent.cpp
Mover owner override to be earlier so that we dont try to get the team of an entity that doesnt have a team and may be a child entity of a player.  Tested changes with a team of two players and players were correctly given credit for kills
> Address issue with player spawned abilities not getting team

- dGame/dComponents/InventoryComponent.cpp
This fixes an issue where the item would get overwritten and would effectively fetch a "random" item in the inventory to move instead of the requested one.  Tested moving various items of various stack sizes to and from a vault and the sell inventory and the expected count of items was correctly moved.
> Address issue with selling/moving items grabbing a "random" item

- dGame/dComponents/InventoryComponent.cpp
Bricks have a stack size of zero in the cdclient so we need to make sure to give them a full stack size of 999 as we do for the bricks inventory with the selling inventory. Tested selling a stack of bricks and only 1 stack was generated on the vendors inventory. Taking the bricks back correctly put them in a stack. Tested buying and selling a full stack as well and all behaved correctly.
> Address issue with bricks selling 1 at a time

- dScripts/ActivityManager.cpp
- dScripts/ActivityManager.h
- dScripts/BaseWavesServer.cpp
Address an issue on Brick Mesa where Battle of Nimbus Station was dropping activity loot.  Tested completing Battle of Nimbus Station and ending early and was not given loot as is expected.
> Don't give activity loot for Battle of Nimbus Station

- dGame/dUtilities/SlashCommandHandler.cpp
- docs/Commands.md
Add the /setlevel slash command.  Command accepts parameters of the requested level and a player to set the level of.  This also adjects the uscore of the player accordingly.  The player must re-log upon using the command to see any updates to themselves or others.
Tested setting the developers level as well as setting another players level by username.  Both worked as intended and set the players level.  As is expected for this, the reciever of the edited level _must_ relog to see changes.  This is what had to be done in live as well.
> Add setlevel command

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dComponents/RebuildComponent.cpp
Address an issue where quickbuilds would become unbuildable.  The main issue lied within serializing parent/child info too often for some reason / serializing it when the info wasnt dirty.  Only serializing this info when it is actually dirty and has changed has addressed the issue and allows quickbuilds to never break.
Since this PR changes how Parents and Children work the following was tested.
First I tested the 100% consistent reproduction in Avant Gardens (finish a build, spawn a build, finish the spawned build, original build respawns, serialize spawned build) and the build never became unbuildable.  The engineers turret that is spawned with the helmet with the 50% consistent reproduction had never encountered the issue where it was unbuildable.  Racing still works as well as …
> Fix an issue where quickbuilds were sometimes unbuildable

- dGame/Entity.cpp
- dGame/Entity.h
We need to make sure we are actually deleting children from the vector of children when they are deleted as entities.  From my observations this caused the second bug with builds where they would be attached to the player for some reason.  Tested regression vs new head and out of 999 imagination no builds broke with engineer helmets on head and many broke on regression  testing.
> Fix child entities not being removed from their parents correctly on deletion

- dGame/Entity.cpp
- dGame/EntityManager.cpp
- dGame/Player.cpp
- dScripts/NjMonastryBossInstance.cpp
- dScripts/SGCannon.cpp
Fixes #464 
Addresses an issue where leaving instances would not call their respective OnPlayerExit methods.  This was due to an error with the order of destroying the entity due to the player being destroyed before the entity class called the methods, causing them to always be false.  This change also resolves and issue where instanced activities would continue running even after all their players would leave.  
Tested leaving Battle of Nimbus Station and Frakjaw and the methods and actions specified in them have been called as expected.  Instances stop script functionality when all players leave and properly resize their variables to allow teams of smaller sizes to ready up and not need to wait for phantom players.
> Address order of deletion of entities on server to allow scripted activities to properly remove players

- dGame/dInventory/Item.cpp
Added item precondition checks for items so players who do not meet the conditions cannot use the items.  tested with the faction bag tokens and they only gave the tokens when a player met all the preconditions or was a Game Master of level 6+
Fixes #374
> Added item precondition checks

- dScripts/AmDropshipComputer.cpp
- dScripts/AmDropshipComputer.h
The dropship computer now no longer gives a player a second mission item should they interact with it again after mission completion.  Tested a player with the mission and after the mission completed and the item is only earned once during the mission and never otherwise.
> Fix issue with dropship computer

- dScripts/BaseWavesServer.cpp
Address an issue in Battle of Nimbus Station where if a player were to click the ready button and then leave via the exit button, the WorldServer would crash.  This was due to no bounds check being in place when attempting to find a player in the waiting players iterator.  Since the player was no longer waiting, attempting to find them in the vector caused the iterator to point the the end of the vector, which the server would attempt to erase.  This has been replaced with proper bounds checks to ensure the iterator erases a valid element.
Tested the repro that caused the crash does not happen anymore as well as ensured the previous methods of leaving do not also cause a crash.  No crash is exhibitted when a player leaves the instance after readying up.
> Address players leaving Battle of Nimbus Station causing a crash that won't save

- dScripts/CppScripts.cpp
- dScripts/FireFirstSkillonStartup.cpp
- dScripts/FireFirstSkillonStartup.h
Adds the FireFirstSkillonStartup script to allow for scripts that use this to function.  This change addresses an issue where the valiant weapons ability would do no damage.  This is due to its skill being cast by the script and not by the object itself.  This PR implements the script and allows items that use this script to function correctly.
Fixes #241 
Tested that the monkey and beehive now correctly deal the damage they dealt in live and properly function without crashes, as well as making sure loot drops for the player who owns the monkey.
> Address issue with Inventor Beehive and Buccaneer Monkey ability on valiant weapon

- dScripts/QbEnemyStunner.cpp
This PR fixes an issue where the growl speakers would play the incorrect skill stun.  Each object that has this script is supposed to get this from the Happy Flower config but the values there are incorrect and need to be collected from the objectSkills table.  
Tested the Growl speaker and the skeletons now dance as intended and the siren still plays the correct animation.
> Address incorrect stun played by growl speakers

- dGame/dBehaviors/Behavior.cpp
- dGame/dBehaviors/VentureVisionBehavior.cpp
- dGame/dBehaviors/VentureVisionBehavior.h
- dGame/dComponents/CharacterComponent.cpp
- dGame/dComponents/CharacterComponent.h
Add the Venture Vision behavior and associated functionality.  Pet digs still do not show up however.
The Kit bonus for factions have been tested and properly grant and take away the buff when it is casted and uncasted.  Tested as well using multiple Venture Vision behaviors at once and the vision only went away when there were zero equipped at once.
Fixes #165 
Fixes #287
> Add Venture Vision Behavior

- dGame/dUtilities/Preconditions.cpp
Fixed an issue with some builds that had preconditions not taking items from the players due to the evaluate costs parameter not being passed to nested conditions.
Tested the build in Avant Gardens and it now correctly takes items from the player upon completion.
> Fix nested preconditions not evaluating costs

- dDatabase/CDClientManager.cpp
- dDatabase/Tables/CDBehaviorParameterTable.cpp
- dDatabase/Tables/CDBehaviorParameterTable.h
- dDatabase/Tables/CDBehaviorTemplateTable.cpp
- dDatabase/Tables/CDBehaviorTemplateTable.h
- dGame/dBehaviors/Behavior.cpp
- dGame/dBehaviors/Behavior.h
- dGame/dUtilities/Preconditions.cpp
This PR addresses the immense number of queries that were run against the CDServer when loading a behavior to now, instead, load the data from an internal data structure so we dont need to run useless queries against the CDServer.  This speeds up the load time of behaviors to near instantaneous where as before they would cause lots of lag on Ninjago, Frakjaw Battle Instance and Crux Prime.
Tested some various skills and behaviors and all of them loaded and used their skills as expected.  Will be testing more thoroughly to ensure that most behaviors still work.  Since this is basically a query caching PR, no functionality is expected to be impacted.
> Added caching for behavior parameter table

- dMasterServer/MasterServer.cpp
We need to wait for the message that the world has shutdown before saying its been shutdown and allowing a new one to be created.  Assuming it has shutdown does not verify that the process was actually stopped an its better to play it safe than sorry and possibly lose player save data
> Address poor communication between Master and World servers

- dChatServer/ChatPacketHandler.cpp
- migrations/dlu/4_friends_list_objectids.sql
Fixes #267 
Fixes #249 
Fixes #469 
Address an issue where the incorrect player IDs were being sent into the friends database, as well as address the issue where you couldnt remove friends.  The former allows our database to follow the foreign key restraint setup by the initial mysql and also allow us to cross reference this table with others in the database without needing to convert to the character id.  A new migration is added this patch to convert the player LWOOBJIDs back into char IDs.  In the server however, they are still stored and used as LWOOBJID.  
Tested changes with 3 clients, all sending multiple requests and only 1 entry was added to the database per player<->friend pair.  Removing a friend also does not cause issues and removes the correct entry from the database.
> Address friends list IDs and removal of friends

- build.sh
- dMasterServer/MasterServer.cpp
Same intentions as in https://github.com/DarkflameUniverse/DarkflameServer/pull/645 , but implemented requested changes.
Checks are now done in MasterServer as requested. 
Tested in the following environments:
- Fully setup system (has all client files, mysql installed and database setup)
- Half setup system (no client files. mysql installed, but database NOT setup)
- Not setup system (no client files, and mysql NOT installed)
For the first environment, it compiled and ran the migration runner. MasterServer also ran with no crashes (with and without a migration history)
The last two environments compiled and skipped running the migration runner as expected.
> Adding migration command to build script (updated)

- CMakeVariables.txt
This allows for better crash logs at a ~2MB binary size increase on WSL and a fraction of a percent on Windows.  Crash logs will now show a better description of the stack trace and methods that were active at the time.  
Server still compiles and runs on Windows and WSL
Example snippet screenshotted below of running /crash which correctly shows the trace from Handle Packet to HandleChatCommand
> Enable _dynamic by default

- CMakeLists.txt
Someone on windows try this out please.
See: https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170
> MSVC: set source / target encoding

- dCommon/GeneralUtils.cpp
- dCommon/GeneralUtils.h
- tests/CMakeLists.txt
- tests/TestEncoding.cpp
> Better Unicode support in GeneralUtils

- dGame/dComponents/RacingControlComponent.cpp
Fixes #463 
Just a small change to properly track lap times on the first and second lap for races
Tested with logs and the correct time was reported for the first, second and third lap.
> Fix racing lap times

- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/RacingControlComponent.cpp
NPCs are supposed to equip the sub items of items they equip and were not doing so.  This PR adds this functionality and fixes and issue where Neido on Crux Prime was not wearing their sword.
Tested that Neido has their sword and that other NPCs that wear proxies also get their proxies equipped.  Had no issues with any other world crashing.
> Fix NPC Proxy items

- migrations/dlu/2_reporter_id.sql
Removes parentheses from the `ADD reporter_id` statement in [migrations/dlu/2_reporter_id.sql](https://github.com/DarkflameUniverse/DarkflameServer/compare/reporter_id_fix?expand=1#diff-cf744faf89bba96f349dfaded7e41503511067b9fb4d1bcd7ef5d5337ad8abc7). This statement will error with parentheses on stock MariaDB.
> Remove parentheses from ADD reporter_id

- dCommon/dLogger.cpp
This removes the requirement for a strlen implementation at the top of the function.
> Replace the vsprintf used in the logger with vsnprintf.

- dChatServer/ChatPacketHandler.cpp
- dChatServer/PlayerContainer.cpp
- dCommon/LDFFormat.cpp
- dDatabase/Tables/CDRailActivatorComponent.cpp
- dGame/LeaderboardManager.cpp
- dGame/dComponents/CharacterComponent.cpp
- dGame/dComponents/PetComponent.cpp
- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/PropertyDataMessage.cpp
- dGame/dGameMessages/PropertySelectQueryProperty.cpp
- dGame/dUtilities/Mail.cpp
- dGame/dUtilities/SlashCommandHandler.cpp
As suggested in #658, this replaces `ASCIIToUTF16` with the new `UTF8ToUTF16` in a few places where it seems appropriate. I haven't tested this ingame yet, so would appreciate if someone does, incase we missed a spot where the input encoding is actually Latin-1 / windows-1521
> Use UTF8ToUTF16 in more places

- dNavigation/dNavMesh.cpp
- dPhysics/dpWorld.cpp
- dPhysics/dpWorld.h
Add a few checks before calling free on some Detour objects
> Implement missing null checks on destruction of the navigation mesh

- dNavigation/dNavMesh.h
- dPhysics/dpWorld.h
This PR fixes the check for if the physics world is loaded and therefore repairs the navigation of ships in the Gnarled Forest shooting gallery.
> Fix checks for if the physics world is loaded

- dWorldServer/WorldServer.cpp
Fixes #716 
Reverts changes made to World initialization that caused issues with PhantomObjects.  Tested POI missions and expected death volumes properly kill the player now.
> Revert ZoneManager initialization order to before #711

- dGame/dComponents/CharacterComponent.cpp
Address an issue where the landing animation no longer played when it was expected to.  Tested travelling from Nimbus Station to Gnarled Forest and the animation played.  Tested travelling from Nexus Tower to Crux Prime and no animation played.  Tested loading into a character and no animation played.
> Fix landing animation not playing

- dGame/dComponents/PhantomPhysicsComponent.cpp
Fixes #707 
Adds a much more accurate and larger Phantom Physics sphere as opposed to the default rectangle.  Previous collider was 2x2x2 whereas the new collider is a sphere of radius 4.5.  
Tested that the physics sphere properly registers the player having entered it if they touch the edges of the sphere.
Tested that the player still has to jump into the orb and cannot trigger it from on the elevator floor.
> Add physics volume for property orb to increase its radius

- Docker.md
* Update Docker.md 
Changed note to recursively update git submodules, otherwise would lead users into #728
Following the old command set would initialize all submodules except for required submodules of mariadb-connector-cpp. This was fixed by using a recursive tag.
This shows that there's additional content not included by the initial command suggestions
Close #728
> Update Docker.md submodule note

- build.sh
Added "intelligence" to the build script to run different build commands if on Windows.
Also, given this uses the OSTYPE variable, the ability to run different commands for different OS's could be added in the future.
> Added windows build commands  to build script

- dGame/dComponents/PhantomPhysicsComponent.cpp
The death plane file size is not in units but is actually in 4x2 tiles.
Fixes #301 
Fixes #195 
Fixes #141
> Fix death planes

- dGame/Character.cpp
- dGame/dComponents/ControllablePhysicsComponent.cpp
Don't save the map and char location info if we are in an instanced Zone
tested going to a prop and making sure everything else saved but I got put back in the origin world.
> Selective saving for map and location

- README.md
The following has been updated on the README
- Flow of the database section has been updated to account for the migration command needing the `ini` files to be configured before execution.
- Changed the bolded headers to actual headers. Now you can link to them. This one was bugging me for some time.
- Updated the Linux build command to reflect the recent changes to the build script
> Updated README (Formatting and flow)

- thirdparty/CMakeLists.txt
Reverts back to file globing for libbcrypt to fix building on Windows Only
Windows compiles now.  Checking other platforms
> Fix Windows not working due to libbcrypt not working on Ninja

- dGame/dInventory/Item.cpp
A change was made in the mounts pull request that broke consumables without correctly marked types such as the picnic basket, this PR resolves that by just checking if it has a package component instead of checking if it is marked as such.
> Resolve incorrectly marked consumables being unusable

- dChatServer/ChatPacketHandler.cpp
Fix an issue where players could friend themselves.  Also stops yourself as appearing as a friend on your own friends list.
Tested adding myself as a friend using the [GM] workaround.  Was not able to.  Tested logging in and our and I did not show up as a friend on my own friend list.
Fixes #771
> Address being able to friend yourself

- build.sh
Given migrations are now run on server start, I have removed it from the build script
> Removed migration runner from build script

- .gitmodules
- CMakeLists.txt
- README.md
- dDatabase/CDClientDatabase.cpp
- dDatabase/CDClientDatabase.h
- dDatabase/MigrationRunner.cpp
- dDatabase/MigrationRunner.h
- dMasterServer/MasterServer.cpp
- migrations/cdserver/0_nt_footrace.sql
Add support to automatically migrate and update CDServers with new migrations.  Also adds support to simplify the setup process by simply putting the fdb in the res folder and letting the server convert it to sqlite.
This reduces the amount of back and forth when setting up a server and also allows us to fix bugs by using cdclient migrations as opposed to special case code.
It is likely up for debate whether we should handle converting the database to sqlite or require the user to do this.  Since we already require python and are cloning a repository which has tools to convert to sqlite from fdb.
Tested that starting a server with just the fdb in ./build/res properly copies and converts the database to sqlite and applies all migrations.  Went into Block yard and was able to open the …
> Add automatic cdclient migration runner support and setup

- .github/workflows/build-and-test.yml
- dCommon/AMFFormat.cpp
- dCommon/AMFFormat.h
- tests/AMFDeserializeTests.cpp
- thirdparty/CMakeMariaDBLists.txt
All tests still pass and these tests are the only place these functions are used at the moment.
Also fixed matrices cancelling each other when one fails.
> Change AMFArray getters to use Templates and fix CI halting when one matrix fails

- CMakeLists.txt
- dGame/CMakeLists.txt
- dGame/dGameMessages/GameMessages.cpp
- dGame/dPropertyBehaviors/CMakeLists.txt
- dGame/dPropertyBehaviors/ControlBehaviors.cpp
- dGame/dPropertyBehaviors/ControlBehaviors.h
Implements the basic functionality and parsing of property behaviors.
Unhandled messages and logged and discarded for the time being.  The only implemented message is a basic one that sends the needed info the the client side User Interface to pop up.
Tested that the User Interface shows up with zero behaviors on it.  No other functionality is changed.
> Implement basic window UIMessage of Property Behaviors 

- dPhysics/dpEntity.cpp
Fixes #256 
im too tired to write a meaningful message - Nexus Tower beam now properly stops regenerating imagination when the player leaves the radius.  Lord knows how many other Gargantuan objects are affected by this change.  Will test more later.  Nothing else seems adversely effected in Forbidden Valley.  Also fixes the Avant Gardens bus to no longer not go up when the player approaches from a certain angle
> Modularize gargantuan objects

- dCommon/GeneralUtils.cpp
- dDatabase/Database.cpp
- dDatabase/MigrationRunner.cpp
- dMasterServer/MasterServer.cpp
- Replace all interaction of std::string and sqlString.
> Make changes to allow Windows to run under a debug environment 

- dChatServer/ChatPacketHandler.cpp
Fixes #756 
Tested that two clients that are private messaging each other read the full message
Tested that two clients on teams can message each other
> Fix chat message reads

- dGame/dComponents/CharacterComponent.cpp
Fixes #781 
tested and it works
Fixes the issue of spawning in incorrectly on the Space blizzard racetrack
> Add Frostbrugh Race Track to the disable landing animation switch case

- dNet/AuthPackets.cpp
- dNet/AuthPackets.h
Tested by setting auth port to 2001 and using nginx to redirect port 2001 to 1001. Successfully authenticated and loaded char.
> Fix server type advertisement in handshake with custom auth port

- dGame/dInventory/Item.cpp
- dGame/dUtilities/BrickDatabase.cpp
- dGame/dUtilities/SlashCommandHandler.cpp
- dZoneManager/Zone.cpp
to avoid crashing
Tested that this fixes crashing on non-existent macros.
When ahead and added checks where this is used to avoid accidental crashes.
Tested that those places are handled gracefully as well
> Add checks to AssetBuffers before they are used

- dZoneManager/Zone.cpp
- dZoneManager/Zone.h
fix for movement path config reading
Tested that this has no functional changes. There may can be changes made since this data is more clearly defined.
This is also in prep for npc movement pathing
reference: https://github.com/lcdr/lu_formats/blob/master/files/luz.ksy
> cleanup and define all unknowns in zone reading

- dGame/Entity.cpp
This is preparation for npc pathing. 
All entities that have an attached_path should not have moving platform components as they do now, so only add a moving platform comp if the path type is for a moving platform
> Prevent adding movingplatform components to all entites with an attached_path

- dZoneManager/Zone.cpp
Not every scene has triggers, that is normal
Quell the onslaught of meaningless logs
Tested that loading zones still works and triggers that do exist get loaded
> Quiet logs of non-existent lutriggers files unable to be loaded

- build.sh
Verified that running `build.sh` with a build error causes the script to exit with a non-zero, while normally the script succeeds
> Make build script fail if any command fails

- dZoneManager/Zone.cpp
- dZoneManager/Zone.h
Fixed reading speed from rail paths
Made the config of rail paths be read in sanely due to not having a type
Fixes #835
Tested loading all other worlds as well
> Fix ninjago crashes

- README.md
- dGame/dGameMessages/GameMessageHandler.cpp
This addresses the Avant Gardens Survival bug and allows users to no longer need to edit their clients in order to play the minigame
Update README to reflect the change
> Fix Avant Gardens Survival

- dCommon/dClient/AssetManager.cpp
Fixes https://github.com/DarkflameUniverse/DarkflameServer/issues/839 
Tested a res dir:
- with `CDServer.sqlite` only
- with  `CDServer.sqlite` and `cdclient.fdb`
- with `cdclient.fdb` only
> Fixed server failing to start without a cdclient.fdb being present

- .github/workflows/build-and-test.yml
This fixes deprecation warnings as seen in the annotations for instance here: https://github.com/DarkflameUniverse/DarkflameServer/actions/runs/3518570052
Node.js 12 has been marked as deprecated for GitHub workflow actions and everyone should switch to Node.js 16 as soon as possible. This PR bumps all deprecated actions to their newest respective version.
> Update workflow actions

- dGame/UserManager.cpp
This is due to AssetManager not being used, so the character names were being pulled from build/res, which may not exist.
Tested by running the server with a custom client path and creating a character, which successfully set the three-part name instead of setting it as INVALID
This is split out from #834 as it is a distinct bug fix critical for servers with a custom client path
> Fix three-part names coming across as INVALID with custom client path

- dGame/dComponents/InventoryComponent.cpp
Increase brick stack size and don't make new stacks of bricks
Tested by adding bricks to the inventory and giving uint_max of a brick several times and only one stack was created
> Make brick stacks live accurate

- dGame/Entity.cpp
- dGame/dGameMessages/GameMessages.cpp
- dScripts/ai/FV/FvNinjaGuard.cpp
- Give entities that have a script component ID of zero a script component still
- Progress scripted entity missions within the for loop as we do for script calls
Tested that Boogie Down is (finally) completable.
Tested that Mission 737 is still completable
Checked that missions progressed inside OnEmoteReceived scripts to not double trigger progression
Fixes #278
> Fix Boogie Down

- dGame/dComponents/InventoryComponent.cpp
new brick stacks currently get discarded.  This PR addresses that issue.
Tested giving myself thousands of faction tokens, new stacks were created correctly.
Tested giving myself thousands of new bricks, all new bricks were given correctly.
Tested that bricks are still discarded if the stack goes above the uint cap
Fixed #859
> Fix new brick stacks

- migrations/dlu/7_make_play_key_id_nullable.sql
Since there is an option not to use play_keys
Tested that things still work, logging in with and without keys and that the authconfig option is repsected
> Add migration to make play_key_id nullable

- dDatabase/MigrationRunner.cpp
This pull request seeks to add functionality to move the cdserver migration history from the main database to the cdserver database.
Has been tested and is backwards compatible with the current system. The server will copy over cdserver migrations history table entries from the main database to the cdserver database, and any new migrations will go into the cdserver database.
This will make it easier to switch out the cdserver database for the purpose of modding and alike.
Fixes:  #866
> Move CDServer migration history table

- dGame/dComponents/InventoryComponent.cpp
- dGame/dGameMessages/GameMessages.cpp
Tested opening the vault, storing a racecar and a pet with a name in it, then moving them both back.  The pet still retained its name between worlds, the racecar was still able to be edited in a car editor.  None of these items showed up as ? in either inventory.  Tested that rockets retain their config with the move as well.
> Allow pets, rockets and racecars to be stored in vault.

- dCommon/dConfig.cpp
- dCommon/dConfig.h
- dGame/dComponents/ScriptedActivityComponent.cpp
- dGame/dComponents/ScriptedActivityComponent.h
- dGame/dUtilities/SlashCommandHandler.cpp
- dMasterServer/MasterServer.cpp
- dPhysics/dpGrid.cpp
- dPhysics/dpGrid.h
- dPhysics/dpWorld.cpp
- dPhysics/dpWorld.h
- dWorldServer/WorldServer.cpp
Adds reloading of the config support.  This required making some changes to the physics world so that you could reload the physics world seamlessly.  Tested that I did not lose imagination when spawning a pet with that setting turned off, but then when using `reloadconfig`, I am successfully able to reload the config file and lose imagination after turning the flag to true.  Tested that in crux prime I am able to run the command while fighting enemies and they will not stop aggroing, and also tested that other non-aggroed enemies are still able to aggro to the player.
Tested that the server still shuts down normally without a segfault from changes in dpWorld.
Tested that reloading config properly toggles whether or not solo racing is enabled
Tested that reloading grants extra backpack …
> Add support to reload the config

- dCommon/CMakeLists.txt
- dCommon/FdbToSqlite.cpp
- dCommon/FdbToSqlite.h
- dCommon/dEnums/eSqliteDataType.h
- dDatabase/MigrationRunner.cpp
- dMasterServer/MasterServer.cpp
Implement a class to convert an FDB file to SQLite, removing any need for a python dependency for setting up and running a server (the python dependency removal will be in #806)
Tested that from the build directory and from 1 directory up from build, that the server starts, and converts the fdb file in the res path to CDServer.sqlite and properly applies the migrations.
ran a `SELECT * FROM BehaviorParameter query;` with LCDR's tool and the new converter and there was no difference between either of two with the table results
Tested that migrations ran as expected and I was able to load into the game and check my mail (requires migrations to be run to succeed)
> Implement FDB to SQLite

- migrations/dlu/7_make_play_key_id_nullable.sql
Fixed a typo in the mysql migration 7 causing it to error when ran.
Was set to table `account` instead of `accounts`
Resulted in the following error when ran
`[MigrationRunner] Encountered error running migration: (conn=6) Table 'darkflame.account' doesn't exist`
--
Tested by running the migration without errors.
> Fixed typo in migration 7 that prevented its execution 

- dGame/dBehaviors/ForceMovementBehavior.cpp
This fixes the bug with the schooner hitting twice, since it was calling that behavior twice.
This probably fixes other behaviors hitting twice.
Tested that the schooner only hits once
> Fix typo in forcemovement behavior

- dGame/dInventory/Item.cpp
- dGame/dUtilities/Preconditions.cpp
- First change removes the precondition bypass for gm9 players.  
- Second change improves the package opener to not allow partial opening of packages.
- Implemented a GM send when the client fails a precondition when trying to use an item
- Implemented a GM send when the client used an item which sends whether that usage was successful or not
- I did not confirm this, but the previous code would also allow you to open packages even if you did not have the space for them.  This has been addressed and you are unable to use a package if the items would not fit in your inventory.
- Tested using an Ultra Mega Faction Token Bag and was unable to get faction tokens when the precondition (level 6 and mission 474) were not met and was able to use the bag when the conditions were met.
- Tested …
> Add back precondition check for packages and remove GM 9 bypass for preconditions

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dCommon/Game.h
- dMasterServer/InstanceManager.cpp
- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
- tests/dGameTests/GameDependencies.cpp
Initialize dConfig first, before logger so we know whether or not to log to console
This also incidentally fixes an issue brought up by @luxaritas about master not logging some initial server info to the console
Initialize namespace Game variables to nullptr so they are a known value if accessed before initialization. Removed unused Game variables
Replaced config with a pointer instead of referencing something on the stack.  Saves us memory used on the stack since this is used until the program shutsdown.
Assign return values to system calls to silence warnings.
Tested that the server still compiles, runs and allows me to load into the game.
> Resolve warnings, change config init order and remove unused Game variables for all servers

- dGame/dBehaviors/BasicAttackBehavior.cpp
- dGame/dBehaviors/BasicAttackBehavior.h
- dGame/dComponents/SkillComponent.cpp
Address the BasicAttackBehavior reading out of bounds memory and reading bits that didnt exist, which occasionally caused crashes and also caused the behavior to do undefined behavior due to the bad reads.
Tested that attacking a wall anywhere with a projectile now does not crash the game.  Tested with logs that the behavior correctly returned when there were no allocated bits or returned when other unserialized states were not met.
No observed issues from about 10 minutes of attacking things, both grouped and not grouped.
Fixes #430
> Fix crash in BasicAttackBehavior

- dGame/dComponents/SkillComponent.cpp
This fixes behaviors not ending when the client sends an interrupt to the player.
This will infinite speed stacking when it was additive to the multiplier (or rather, permanent speed boost once that PR is merged what removes stacking speed boosts).
Tested several different scenarios behaviors for the player being interrupted to make sure they are handled sanely
> Allow player skills to be interrupted

- dNet/dServer.cpp
LEGO Universe uses a lower datagram / MTU size so we are also going to use this.  May also address other issues, we'll see.
Tested that the server compiles and boots.  
Will test that I can login with a substantially sized Create Character packet in the morning
> Implement lower cap datagram / MTU size

- dGame/dBehaviors/SwitchMultipleBehavior.cpp
- dGame/dBehaviors/TacArcBehavior.cpp
No expected behavior change in tacarc since everything was false and 0 to begin with so nothing would happen, however being explicit here and returning early is more ideal.  
Tested that the server still compiles but don't know how to purposefully trigger a bitstream overread.
> add missing returns in tacarc and switch multiple

- dGame/dGameMessages/GameMessages.cpp
item is null if there is only 1 item, so this was undefined behavior and now properly progresses the mission if there is only 1 item in the stack
Tested that having 1 hot dog in the inventory properly progresses the Quit yer bellyachin' mission when consumed
Fixes #204
> Fix using last item in a stack not counting towards mission

- dGame/TradingManager.cpp
When trading, we need to take the item by ID and not by lot.  This caused the wrong item to be taken.
Tested that trading properly takes items by ID and not by lot.
> Fix trading taking the wrong item

- dGame/dBehaviors/AttackDelayBehavior.cpp
- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dBehaviors/BehaviorContext.h
- dGame/dBehaviors/ProjectileAttackBehavior.cpp
- dGame/dBehaviors/ProjectileAttackBehavior.h
When this reading existed, the logic failed with the number of unread bits being exactly 64.  A NiPoint3 is 96 bits (3 floats) so this reading is not correct and caused the plunger gun in Avant Gardens to not work.
Tested that the plunger gun now correctly destroys targets.
> Fix overread in projectile behavior and address broken stuns

- dGame/dComponents/ScriptedActivityComponent.cpp
Addresses an issue where lobbies did not reset their timer if all players left that lobby.
Fixes #530
Tested that a player joining a lobby, readying up, leaving that lobby, and joining a new one properly deletes the old, unpopulated lobby.
Tested the following scenario:
2 players in one spider queen lobby and a third in a second lobby
the 2 players leaving their lobby properly delete the lobby and the single player is still able to join theirs
all players leaving their lobbies deletes the two lobbies.
> Fix lobbies not resetting the timer if all players leave

- dGame/dUtilities/SlashCommandHandler.cpp
- dNet/dServer.cpp
- dNet/dServer.h
- resources/sharedconfig.ini
Fixes #896 
Tested that if the value is not there, the default live value is used.  If the value is there then this config option takes effect.
> Add MTU config option

- dGame/dComponents/RacingControlComponent.cpp
- dGame/dComponents/RacingControlComponent.h
From looking at the LUZ file, the entity 4843 is used in racing with the LDF data `placement` with the corresponding position to place the player in based on the value of the key.
Tested that a player at position 1 and at position 6 both spawned at the positions specified by this lot.
> Fix racing spawn positions

- dGame/dGameMessages/GameMessages.cpp
- dScripts/02_server/Enemy/General/BaseEnemyApe.cpp
Live LUA script called CancelSkillCast, which I presume is to stop the ape from casting its skills since the ape cannot have any of their skills interrupted.
Also addresses an issue where IdleFlags was not being serialized correctly.  Idle flags have defaults as seen in Reverse Engineered source code and as is documented [here](https://lcdruniverse.org/lu_packets/src/lu_packets/world/gm/client/mod.rs.html#1363-1368)
Tested that no longer do their ground pound silently upon getting out of stun, even if they were stunned while winding the skill up.
Fixes #905
> Fix baseEnemyApe stuns and fix IdleFlags serialization

- dGame/dBehaviors/MovementSwitchBehavior.cpp
- dGame/dBehaviors/MovementSwitchBehavior.h
Fixes #491 
Addresses movement switch disagreements between the client and the server.
Tested that I am able to fight a dragon and use the firework after getting hit by the ground pound aoe.
Tested that I can use The Big One! shortly after falling off a ledge.
Tested that no other unexpected disagreements showed up with existing movement states.
Some notes:
Yes, you must use a behavior or id zero if it it explicitly specified. See [this behavior](https://explorer.lu/skills/behaviors/37108/37108) for more info. It is unable to be used while in jetpack mode on the client so i've mimicked that behavior on the server.
If a parameterID does _not_ exist for a movement type, you must default to the ground behavior.  This is what was done in the live client.
We got Falling and Air action …
> Make Movement Switch Behavior more Live accurate

- dCommon/dEnums/eBasicAttackSuccessTypes.h
- dGame/dBehaviors/BasicAttackBehavior.cpp
- dGame/dBehaviors/BasicAttackBehavior.h
The motivation behind this change is to ensure we are sending exactly what we need to when serializing behaviors to the client.  The Basic Attack Behavior was correct before in what bits went where, however the client would be expecting less information than what we were sending which caused disagreements between the client and the server with certain variables.  Handles and Calculations were updated to have a wrapper class that handles the reading / writing of the size offset variable that is serialized in the bitStream.  An enum was added to clarify what success states are what, as well as the switch case statement being changed to be how the client handles the behavior.  The unknown in the bitStream was proven to be armor damage taken, both through deserialization and also through …
> Basic Attack Behavior Live Accuracy Improvements

- dDatabase/Tables/CDBehaviorParameterTable.cpp
- dDatabase/Tables/CDBehaviorParameterTable.h
- dGame/dBehaviors/Behavior.cpp
Fixes and issue where the fire sword would deal the incorrect amount of damage.
Reduces hashing time by instead hashing 2 numbers instead of a string and a number.
new limit for the hashes is the uint32 max for both behaviorID and parameterID
> Fix Hash Collisions in CDBehaviorParameter table

- dGame/dBehaviors/SpeedBehavior.cpp
- dGame/dBehaviors/SpeedBehavior.h
This is to fix speedbehaviors that are onEquip ending when unequiped, such as with the faction crate disguises.
Tested that this properly ends the speedbehavior when unequiping the faction crates
also moved the timer function up to match the order in the header
> add uncast to speed behavior

- migrations/cdserver/5_serratorizer_chargeup_fix.sql
The Serratorizers charge up time is limited at 20 as shown [here](https://explorer.squareville.org/skills/behaviors/20933/20999) however its following switch multiples' value 2 is limited at 2, which is not in line with any other valiant weapon which have value 2 at 20.  This migration addresses this issue.
Tested that the serratorizer can be used after charging for longer than 2 seconds
> Fix serratorizer chargeup time

- dGame/dComponents/SkillComponent.cpp
Simple change, just serializes the target with an echo sync skill.  Tested that you now properly get knocked back when hitting the beam in Battle of Nimbus Station and the laser in avant gardens properly shows the damage animations past the first hit
> Address Battle of Nimbus Station Central beam and Avant Gardens laser not playing animations past the first time you take damage

- dGame/dGameMessages/GameMessages.cpp
- dGame/dInventory/Item.cpp
I don't like how this is done, but there is literally 1 singular mission that uses this feature, so i implemented this the best I could using the information of that one mission
Tested that you need to swap precisely the 6 possible unique parts in order for the mission to complete and that you have to have put a car into the build first in order to allow the mission to complete.
> Fix Complete Overhaul

- dGame/dComponents/BaseCombatAIComponent.cpp
Fixes #305 
Tested that Hitting an admiral with a bullet causes them to stun for that next frame and that next frame only, mimicking the current behavior of all other weapons and ensuring they are stunned for at least one frame.
> Fix Stuns of duration zero

- dGame/dComponents/BaseCombatAIComponent.cpp
- dGame/dComponents/BaseCombatAIComponent.h
- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/PlayerForcedMovementComponent.cpp
Address some easy fixes for components:
Implement Delta Compression for the BaseCombatAIComponent to save data sent over the wire.
Only serialize the PetComponent tamed pet name on construction
Serialize PlayerForcedMovement on construction
Tested that no serialization errors appeared in the client logs.
Tested that pet names still show up for myself and other players
Tested that enemies have no combat change
> Serialization fixes for Components

- dCommon/dLogger.cpp
debug logs properly put a new line at the end of a line
> Fix debug logging newline

- dGame/dComponents/DestroyableComponent.cpp
- dGame/dMission/Mission.cpp
- dGame/dUtilities/Mail.cpp
- dZoneManager/WorldConfig.h
- dZoneManager/dZoneManager.cpp
- dZoneManager/dZoneManager.h
Loads the entire WorldConfig into memory and uses a struct to hold all of the world config information.  This eliminates several uses of magic numbers across the codebase and simplifies some ZoneManager variables all into one object.  
Tested that values used by DLU match what they were before, but instead get this value from this new method call.
> Eliminate WorldConfig Based Magic Numbers

- dGame/dComponents/DestroyableComponent.cpp
Verified via Packet capture `GruntMonkey\Crux Prime\Sterland Powers rebuild computer to get data(ProtoStrongHulk asked me to join team of him,MuslcualrSkysurfer, and JetGothicRaven and asked to be friends but I had to leave after)` that an object was smashed at packet interval `8936` by `ProtoStrongHulk` and credit was given to ShastaFantastic, who was on a team with that person at that time.
Tested that teams properly progress smash missions
> Fix smashables not counting towards whole team

- dGame/dComponents/DestroyableComponent.cpp
- resources/worldconfig.ini
adds a "hardcore mode" to DLU. 
All it does is set through the worldconfig, where you can enable/disable the mode entirely (off by default), or certain parts of it.
Includes:
- Drops coins and item inventory on death (can be picked up again if you make it in time)
- Loses u-score on death. By default, 10%
- Awards u-score per kill. Calculated by taking the enemies' max HP * the multiplier from the config.
> Hardcore mode

- dMasterServer/MasterServer.cpp
Let finalizeShutdown take care of it with `atexit()`
While this affected no functionality, the server now doesn't crash when you create an account.
> Fix misleading crash

- dGame/dComponents/AchievementCacheKey.h
- dGame/dComponents/MissionComponent.cpp
- dGame/dComponents/MissionComponent.h
Addresses the above issue by using an overloaded operator== and a custom implementation of hash<T> to allow the stl to handle hash collisions instead of needing to implement our own method instead.  There is an expected performance hit here due to string comparisons in some cases, but there is not much that can be done here since we cannot assume the hash is good and should verify that the lookup actually gives us the correct and expected result.
Tested that after a full playthrough of Avant Gardens, the player properly is given the Nexus Force Explorer mission and is not given racing missions which the previous collision would do.  A future PR will address issues that were caused by a result of the collision.
> Fix hash collisions causing the wrong achievements to not be accepted

- dGame/dComponents/CharacterComponent.cpp
Fixes #975 
Live footage of the landing:
https://www.youtube.com/watch?v=kdLvEMP09PM&list=PL9EFB8500E625ADC7&index=42
> Allow landing animation in Return to the Venture Explorer

- dGame/dComponents/SkillComponent.cpp
- dGame/dComponents/SkillComponent.h
- dScripts/EquipmentTriggers/CoilBackpackBase.cpp
- dScripts/EquipmentTriggers/CoilBackpackBase.h
- dScripts/EquipmentTriggers/GemPack.h
- dScripts/EquipmentTriggers/ShardArmor.h
- dScripts/EquipmentTriggers/TeslaPack.h
This is to reduce magic numbers in the code base
Only updated one use of this to demo that this works. Will be do more in a separate PR.
Also, inadvertently fixed damage stacking and self-damage in the tesla pack
Tested that all the coil based backpacks work as intended
> Make wrapper for casting skills

- dScripts/02_server/Map/AG/AgMonumentRaceGoal.cpp
prevents this crash
```c++
[15-02-23 21:30:34] [Diagnostics] Encountered signal 11, creating crash dump crash_World_22979.log
[15-02-23 21:30:34] [Diagnostics] [00] /home/user/dlu/build/WorldServer(_Z14CatchUnhandledi+0x1e8) [0x5626a0d02a38]
[15-02-23 21:30:34] [Diagnostics] [01] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f3a58e6d980]
[15-02-23 21:30:34] [Diagnostics] [02] /home/user/dlu/build/WorldServer(_ZN18AgMonumentRaceGoal17OnProximityUpdateEP6EntityS1_SsSs+0xc4) [0x5626a0ecd994]
[15-02-23 21:30:34] [Diagnostics] [03] /home/user/dlu/build/WorldServer(_ZN6Entity20OnCollisionProximityElRKSsS1_+0x116) [0x5626a0d94b06]
[15-02-23 21:30:34] [Diagnostics] [04] /home/user/dlu/build/WorldServer(_ZN25ProximityMonitorComponent6UpdateEf+0xc4) [0x5626a0e03cc4]
[15-02-23 21:30:34] …
```
> add bounds check to prevent crashing on AG monument race goal

- dGame/dComponents/TriggerComponent.cpp
Fix trigger missions as previously they were all compared as lowercase, but the code was change to be uppercase.  To keep consistent with the value in the mission and the value in the lutriggers file
Tested that Discover the Orange Path, Cobwebs!, and Insect Music all progressed correctly (they are all trigger progression)
> Fix Trigger Missions

- dScripts/02_server/Map/GF/MastTeleport.cpp
Fixes #706 
Tested that the animation is not interrupted while the player is in the animation.  Tested that the player can correctly take damage afterwards.
Also correct the animation priority as the script from live used 4.0f and not 1.0f
> Fix stuns with mast teleport

- dScripts/02_server/Map/NS/Waves/ZoneNsWaves.h
- dScripts/BaseWavesServer.cpp
Fixes #1016 
Tested that players who are alive no longer are teleported to the bons respawn area
> Dont respawn players at end of bons

- dScripts/02_server/Map/NS/Waves/ZoneNsWaves.cpp
> Up end of match timer for Battle of Nimbus Station to 60 seconds

- dGame/dBehaviors/BasicAttackBehavior.cpp
With newfound modding work, we have gotten a skill debugger working for the live client and can observe many debugging features in the live client. With this information, we have learned that every Calculated behavior from the server writes an extra bit on the calculation so I have removed this extra bit write.
The client no longer complains that the read offset mis-matches where it should be.  No other observed changes.
> Remove extra bit in BasicAttackBehavior Calculate write

- dGame/dUtilities/SlashCommandHandler.cpp
Typo when compared to actual setting, compare with greater than equal instead of greater than
> Fix nameplate command

- dGame/dInventory/Item.cpp
Tested that the LOTs 14709 and 9629 can be trashed into bricks now whereas 14709 could not previously.
> Fix models not disassembling into bricks

- dGame/dBehaviors/ChangeOrientationBehavior.cpp
- dGame/dBehaviors/ChangeOrientationBehavior.h
Tested that this works as intended.
to_angle in unused in behaviors in live but has handling in the client.
to_point in unused in both, so not implementing it, even in where it is used in the cdclient, it doesn't make sense sine there i no point associated with it to orient to.
Tested that this works as intended now.
See Epsilon or the Sentinel Guards in AG. they will look at what they are shooting at now
> Fix and fully implement ChangeOrientation behavior

- dGame/dBehaviors/InterruptBehavior.cpp
- dGame/dBehaviors/SwitchMultipleBehavior.cpp
The client calculates the SwitchMultiple action as follows:
take your value and compare it to the list of values associated with this behavior.  If you encounter a value that is lower than your current, save it as the next to be executed.  If you find a value that is greater than break and execute the saved value.  Because of this, we would attempt to do behavior logic that was not intentional but was stopped in some cases, namely the wormholer due to the BitStream being empty.
Tested that the WormHoler no longer erroneously logs unable to read from BitStream errors.
Tested that the WormHoler still does damage with its long charge up attack
Tested that the WormHoler still does damage with its short charge up attack.
This also means we can technically delete one of the migrations (the …
> Fix SwitchMultiple incorrect handling

- dGame/dBehaviors/AttackDelayBehavior.cpp
Resolves several newly introduced invisible enemy issues.  Does not affect TacArc.
Tested that the Mosaic Jester Cap now properly can use all 10 of its attacks as opposed to only 3 before
> Fix copy paste error with AttackDelayBehavior which caused more invisible enemies than before

- dGame/Entity.cpp
Resolves Brig Rock not rendering in until you get extremely close.
Tested that Brig Rock properly doesn't ghost when you are outside its range.
> Patch ghosting exclusions

- dGame/Entity.cpp
- dGame/dComponents/SkillComponent.cpp
- dGame/dComponents/TriggerComponent.cpp
- dGame/dComponents/TriggerComponent.h
- dScripts/ai/AG/AgJetEffectServer.cpp
This PR implements the timer command handlers (settimer and canceltimer) as well as the ontimerdone event
Additionally, the AGJetEffect Server has been cleaned up and made 100% live accurate, which is the main reason for adding the timer trigger stuff since the beacons use them
Tested that it works properly and doesn't crash.
After delving into the triggers more, the Jeteffect is the only place it was used in Live, the rest are remnants from older versions of worlds
> Implement Timer handlers in triggers and ontimerdone trigger event

- dGame/dInventory/Inventory.cpp
Reverse Engineering in the client has revealed that this is the precise correct inventory type mapping for items by item type.
Will test that LUP_MODELS appear in the models inventory as opposed to items
> Correct incorrect inventory types

- dPhysics/dpGrid.cpp
Regressed and crashed as expected when travelling far outside of Crux, added back the changes here and the crash did not happen anymore.
> Fix bounds check for dpEntity moving

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
Fix Chat Crash
Tested that servers are still functional and handle packets as normal.
> Fix chat crash and reinforce other servers handling packets

- dGame/EntityManager.cpp
- dGame/EntityManager.h
- dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.cpp
Makes crash logs more apparent for what stage they crashed in for the engine updating.
Also no need to cast an entity to a player.  The virtual destructor takes care of that for us.
I walked around the worlds and things were getting updated
> Add more null checks and split out code

- dChatServer/ChatPacketHandler.cpp
- dChatServer/PlayerContainer.cpp
- dCommon/dEnums/dCommonVars.h
- dNet/ClientPackets.cpp
- dWorldServer/WorldServer.cpp
- tests/dCommonTests/CMakeLists.txt
- tests/dCommonTests/HeaderSkipTest.cpp
Seeing 
```
inStream.Read(playerID);
inStream.Read(playerID);
```
is very unclear what is going on, and a comment is difficult to maintain.  This macro skips the header, or the whole packet, whichever is less.
Tests are attached and in-game worked all fine from doing test chats and friend requests
> Make header skips more obvious

- dGame/Entity.cpp
- Fixes deserialization errors for MovingPlatforms that did not have an `attached_path`, but had a MovingPlatform component >= id 0.
- Fixes #884 
Tested that the following lots no longer have deserialization errors when they used to:
16141 and 14478 in Ninjago Monastery
9265 and 9266 in Forbidden Valley
12047 in Crux Prime
> Fix deserialization errors for MovingPlatforms

- dGame/dComponents/MovementAIComponent.cpp
Fixes #1030 
The client seems to do the following for getting the speed from the ControllablePhysics table (of which there is only ever 1 fetch of this field and it is in a ControllablePhysicsComponent):
Default speed set to 10.0f
Check the PhysicsComponent table for the column speed and if it exists set speed to that value and if the value was null set it to the default again.
Tested that the birds of the Wingreaper now properly move towards their enemy.  Tested that the dragons in Forbidden Valley dragon battle still do not move (since they have null speed too).  Tested that enemies with specifically zero speed remain at zero speed as set in their PhysicsComponent entry.
> Fix Wingreaper birds not moving

- dGame/Entity.cpp
This PR reverts #1088 and fixes what #1088 was trying to fix, but without breaking every entity with an attached path, since not everything with a path is a moving platform. Most are just NPC's that will follow a movement path, once that server side logic is implemented.
Tested to make sure that the entities tested in #1088 still serialize correctly and do not generate deserialization error on the client
> fix: not everything attached to a path is a moving platform

- .github/workflows/build-and-test.yml
[Here](https://github.com/DarkflameUniverse/DarkflameServer/actions/runs/4968581928#artifacts) is a run of it in a seperate branch as to not dirty the commity history.
This simply uploads all CI runs to Github storage to allow for them to be downloaded, nothing is different as far as how we run CI we just now save the runs.
> Enable artifact uploading and replace upload parameters

- dWorldServer/ObjectIDManager.cpp
- dWorldServer/ObjectIDManager.h
Not sure why this happens, but it does.  Original code was inefficient anyways so this is a net gain.
fixes #1100
If they reply that the bug is fixed on their end I will consider this tested enough
> Fix: Some platforms not using the same RNG for every roll

- dCommon/AMFDeserialize.cpp
Per ISO C++ standard 9.7.1 clause 8,
"For an enumeration whose underlying type is fixed, the values of the enumeration are the values of the
underlying type" it is not undefined behavior to set a scoped enum to a value outside of its constant range because all values of the underlying type can represent the scoped enum
> Correction: Remove intermediate read from bitstream in AMFDeserialize

- dPhysics/dpGrid.cpp
Fixes an issue where we would try to access an array out of the physics bounds
Same fix as #1070, but for all NUM_CELL defines
> Fix more out of bounds access in physics grid

- dGame/dUtilities/VanityUtilities.cpp
> fix: make vanity npc's use default equipment if none is specified

- dGame/dComponents/InventoryComponent.cpp
Fixes an issue where you could use some rocket launchpads before you met the prerequisites
Tested that the Nimbus Station -> Nexus Tower launch pad no longer allows you to use it if you do not have the pre-requisite met.
> Fix prereq bug with rockets

- dGame/dComponents/VehiclePhysicsComponent.cpp
- dGame/dComponents/VehiclePhysicsComponent.h
- dNet/ClientPackets.cpp
- Add missing frame stats reading
- correct the inversion of rotation
- correct serialization order
- use proper dirty flags
Tested that racers are no longer sideways on certain vertical slopes and stay in sync throughout the whole race.
Observe how in the image players are no longer eating the track.
Fixes #753
> Fix vehicle serialization during races

- dGame/Character.cpp
- dGame/Character.h
Whoops!  Looks like we missed this one in QA.  
Fixes weird mission progression when passing in -1 as a flag to check.
Tested that on main a mission that would progress 2 now correctly progresses only once.
Fixes #1128
> Revert playerflags functions to uint

- dGame/dComponents/InventoryComponent.cpp
- dGame/dUtilities/SlashCommandHandler.cpp
Tested that equipping and spawning work as intended
fixes #1131
> fix: remove hardcoded rotations now that vehicles orient correctly

- dGame/dUtilities/SlashCommandHandler.cpp
DESCRIPTION: Changed freemoney gmlevel 9 command to parse 64 bit integers as opposed to 32 bit.
MOTIVATION: Messing with admin commands and realizing it was originally 32 bit.
TYPES OF CHANGES: Changing variable type.
TESTING: Running freemoney gmlevel 9 command with values between 32 and 64 bits.
> freemoney type fix

- dGame/dComponents/RacingControlComponent.cpp
DESC: Added player rewards for solo racers. 
MOTIVATION: Solo racing currently does not give rewards to solo racers. This hinders the experience for those who do race alone, whether on a solo racing enabled server or local server.
Types of Changes:Modified how score is calculated in the case of solo racing in order to give solo racers rewards
Testing: Tested racing solo prior to this change, and did not receive coin or faction tokens. After making the change, faction tokens and coins were given as a reward for completing a solo race.
Thanks to EmosewaMC for contributing
Fixes #999
> Added Player Rewards for Solo Racing

- dGame/dComponents/PetComponent.cpp
Description: Slightly increased the distance for pet digs which should help combat the issue with skeleton dragons being unable to dig up bones on Crux.
MOTIVATION: Currently there is an issue with bone digs on crux due to the navmesh. This is a small fix to help combat that issue
DESCRIPTION: Increases dig distance slightly
TESTING: Tested using the dragon to dig up bones over time
Thanks to flamethrower for reporting the issue
> Pet Dig Distance Slightly Raised to Help Combat Skeleton Dragon Dig issue on Crux

- dScripts/02_server/Map/NT/NtCombatChallengeServer.cpp
DESC: Fix for dual instance starting when two players hit start on the challenge at the same time.
MOTIVATION: Want to fix issue for any future occurances
TESTING: Will test tomorrow/later
Fixes #1135
> fix: Nexus Tower Combat Challenge can be started twice if two players start it at the same time

- dZoneManager/Zone.cpp
- dZoneManager/Zone.h
> fix: read and store the zone transition width properly

- dGame/dComponents/RebuildComponent.cpp
Tested that if you build a build with only 2 imagination and it takes 3 to complete, the build correctly shows it needs 1 more imagination to complete as opposed to now where it will let you keep building and then the build needs negative imagination
> fix: incorrect kick out of rebuilds that caused negative imagination to complete it

- dWorldServer/WorldServer.cpp
Tested that it loads and lets you into character selection if you have a good fdb
and that it kicks you back to login if you have a bad fdb
(I literally just moved that logic outside of that if zoneID!=0 block to after that if-else)
> fix: load fdbchecksum to verify, even on character selection (world 0)

- dCommon/NiPoint3.cpp
- dCommon/NiPoint3.h
- dNavigation/dTerrain/RawFile.cpp
- dNavigation/dTerrain/RawFile.h
Perf improvement of 1/3 to 1/10.  OBJs are in the correct format now as well and do not appear malformed.  Code also initializes a pointer to nullptr now and actually allocates an object to said pointer as right now the code will segfault.
Tested by overlapping an export from happy flower and an export from the code below and they lined up 1:1.
> fix: RAW to OBJ parsing

- dGame/dMission/Mission.cpp
- dGame/dMission/Mission.h
Fixes an issue where characters would lose mission progress due to a dangling pointer in mission data.
This was proven by adding a logging message to the destructor of all CD tables which revealed that when crashing, the tables and all their data are destroyed _first_ and then character data is saved.  This causes all missions to enter a state where their pointers are dangling and character data will enter an invalid state.
This is a quick patch to get character save data stable and remove the dangling pointer.
Tested that previously, I would lose my mission progress with 3 clients in world `1251 1` every time on multiple characters and after the patch I would never lose save data.
Image of save data with fragmented memory, as you can see, the missionID is a completely invalid number
> fix: dangling pointer in mission when saving character data

- dGame/dComponents/MultiZoneEntranceComponent.cpp
fixes #1195
Tested that the menu still works
> fix: MultiZoneEntranceComponent selection windows opening for everyone in the zone

- migrations/dlu/11_fix_cheat_detection_table.sql
Drop table incase it exists (which sometimes it doesn't) and then make it again without that foreign key
Tested on 10.11.5-MariaDB
Dropping table since there's little to no chance that data has gotten in it yet, on the chance it even exists
> fix: remove foreign key on name in cheat_detection table

- dCommon/dClient/AssetManager.h
Currently on line 116 of AssetManager.cpp, we have the following `*data = (char*)malloc(*len);`
however on line 45 of AssetManager.h we have `delete m_Base;` which is not the same allocator as we used to allocate the memory. This PR matches the deallocation to use the correct allocator type.
Tested that valgrind no longer reports errors about mis-matched allocators/free, delete etc.
> fix: Match deallocation for allocators

- dGame/dUtilities/CheatDetection.cpp
in earlier blocks, we check if player is null before accessing it.  In doing so I neglected to propogate the player access for who to report into said blocks.  This will resolve crashes from null accesses.
> CheatDetection: Move player access

- dGame/dComponents/RenderComponent.cpp
- dGame/dComponents/RenderComponent.h
fixes #1200 
replace scale with priority as it should be
remove the assert
> chore: cleanup FX component serialization

- dCommon/GeneralUtils.h
- dCommon/LDFFormat.cpp
- tests/dCommonTests/TestLDFFormat.cpp
Simplifies the work we are doing by using a common known working and tested function.
Tests still pass and server still reads all ldf data from luz files.
> chore: Use TryParse for LDF parsing

- dScripts/02_server/Enemy/General/BaseEnemyApe.h
- dScripts/02_server/Map/AG_Spider_Queen/ZoneAgSpiderQueen.h
- dScripts/02_server/Map/njhub/NjNPCMissionSpinjitzuServer.h
- dScripts/ActivityManager.h
- dScripts/BasePropertyServer.h
- dScripts/BaseWavesGenericEnemy.h
- dScripts/CppScripts.cpp
- dScripts/CppScripts.h
- dScripts/NPCAddRemoveItem.h
Fixes an issue where we needed a C style cast to save these scripts due the the diamond problem wherein the compiler was unable to determine which CppScripts base class to inherit from with multiple inheritance of the same base class.
Moved globals to unnammed namespace
removed empty script logging as missing
Tested that scripts still compile.
Also cache the script that was being raw returned
> Scripts: Fix ambiguous base class

- dGame/Entity.cpp
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/DestroyableComponent.h
- dScripts/ai/PROPERTY/AgPropguards.cpp
Fixes #1222
addresses an issue where the death behavior of a destructible component was not being respected and enemies with destroyable components that had special death animations were not able to play the animation on death.  This pr adds in the hardcoded constant the client uses for the same metric of 12 seconds.
Tested that claiming Nimbus Rock and completing the property guards mission allows him to vacuum away and then network the destruction packet 12 seconds later.
> fix: Animated deaths not playing

- dChatServer/PlayerContainer.cpp
- dChatServer/PlayerContainer.h
- dGame/TeamManager.cpp
- dGame/TeamManager.h
- resources/sharedconfig.ini
new feature to default teams to ffa as 99.999% of the time you use this anyways.  Config option added to use live accurate default shared loot should you want that.
Tested that when default_team_loot is 0, shared loot is used by default and when default_team_loot is 1, free for all loot is used by default.
> fix: Default team loot to ffa

- dMasterServer/MasterServer.cpp
Fix a race condition that would overwrite the port of zone 0 with the auth server port or a chat server port which would cause a domino effect of desynced server ports
Tested that a sleep(5) in auth still allows a player to connect and login without issues
> fix: Address race condition

- dGame/Entity.cpp
Adds a missing edge case on the client where you may have the is_smashable flag set, but dont actually have a destroyable component.  In this case you should create only a destroyable component and add it to the component and serialize it last after all other data.  We also needed to add the set_faction var reading and setting as this is how Oliver Sudden actually gets their faction since they have no actual information in the database, it is all stored in ldf keys.
Tested that Oliver Sudden no longer logs Unable to unserialize logs when serialized or constructed.
> Entity: Add missing destroyable case

- dScripts/02_server/Enemy/AG/BossSpiderQueenEnemyServer.cpp
unsure how to reproduce the actual bug, however we can see that with the following crash dump
```
Entity::GetComponent(eReplicaComponentType) const(+0x4) [0x56095665e634]
BossSpiderQueenEnemyServer::OnDie(Entity*, Entity*)(+0x28d) [0x560956795d0d]
Entity::Kill(Entity*)(+0xf8) [0x5609566637a8]
ZoneAgProperty::BaseTimerDone(Entity*, std::string const&)(+0x89b) [0x56095683736b]
Entity::Update(float)(+0x2b6) [0x560956662676]
EntityManager::UpdateEntities(float)(+0x2e) [0x56095667305e]
```
that the actual crash issue starts at
```
Entity::Kill(Entity*)(+0xf8) [0x5609566637a8]
ZoneAgProperty::BaseTimerDone(Entity*, std::string const&)
```
BaseTimerDone calls Kill, and there is only 1 call to Kill in the function which calls Kill no arguments, meaning the killer is a nullptr.  This propogates …
> Scripts: Fix possible nullptr access

- dCommon/Diagnostics.cpp
Tested that a crash now prints to the error file the demangled names
new logs look like this following
```
Error: signal 11:
[00] CatchUnhandled(int)(+0x2f2) [0x7f29e5fb0f12]
[01] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f29e5dd1420]
[02] WorldShutdownSequence()(+0x3c) [0x7f29e5fa851c]
[03] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f29e56d3090]
[04] /mnt/f/Users/EmosewaMC/Documents/GitHub/DarkflameServerMain/build/WorldServer(+0x4d5524) [0x7f29e62fb524]
[05] CppSQLite3Query::fieldIndex(char const*)(+0x4a) [0x7f29e62f15ca]
[06] CppSQLite3Query::getIntField(char const*, int)(+0x16) [0x7f29e62f1756]
[07] CDBehaviorParameterTable::LoadValuesFromDatabase()(+0xe4) [0x7f29e5fc8e94]
[08] CDClientManager::CDClientManager()(+0x82) [0x7f29e5fbf202]
[09] …
```
> Diagnostics: Fix error file

- dGame/EntityManager.cpp
While we were no longer modifying these std containers in these loops directly, this did not stop external code from accessing and modifying the containers, invalidating the contained iterators.
Tested that servers still start up, and that zones like bons no longer hard crash when all players have left the world.
> fix: iterator invalidation in EntityManager

- dGame/Character.cpp
Tested that on windows debug, you no longer crash when logging into a character that was just logged into.
> fix: deleted memory access in Character Select

- dChatServer/ChatPacketHandler.cpp
Fixes a possible nullptr access in the chat server.  This is the only call to GetPlayerData where we do not check the result for some reason, so this PR adds in the check and a resulting log line.
Code compiles, unsure how to reproduce the issue, however here is the crash dump I used to deduce this being the possible issue
```
Error: signal 11:
[00] CatchUnhandled(int)(+0x316) [0x561469100336]
[01] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f65e8e45520]
[02] /DarkflameServer/build/ChatServer(+0x32719) [0x5614690fa719]
[03] HandlePacket(Packet*)(+0x2a0) [0x5614690fcfb0]
[04] /DarkflameServer/build/ChatServer(main+0x92e) [0x5614690fb75e]
[05] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f65e8e2cd90]
[06] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f65e8e2ce40]
[07] …
```
> fix: possible nullptr access in chat server

- dGame/dGameMessages/GameMessages.cpp
fixes a crash
crash from being in a team and trying to drop loot to a member of that team no longer crashes
> fix: Add null check for loot drops

- dChatFilter/dChatFilter.cpp
Tested that the string pictured here
no longer has `prime` marked as all red except the ending e, resulting in `prim` being marked as rejected.  This was because we used the regexed string for the length and not the original one.
> fix: ChatFilter incorrect segment highlighting

- dScripts/02_server/Map/NT/NtCombatChallengeExplodingDummy.cpp
Fixes #1263 
Tested that even with uber hammer, only 1 dummy can spawn at a time and Die isnt fired multiple times
Changed behavior to be 2 hits to kill exploding target instead of 1 as this is what the live script did.
> fix: Nexus Tower Combat Challenge exploding dummy

- dGame/dGameMessages/GameMessages.cpp
Optimized writes and reads to use aligned reads and writes to save time not looping.
Removed async code as the destructor of a std::future will block at the end of the function, causing it to block and removing its purpose, the code being run by it is async anyways, so it served no purpose anyways
Removed second persistentid generation that is unnecessary for ugc models as we overwrote it anyways with something new.
The pictured model well above a singular sd0 chunk size was able to be built, saved and downloaded when requested without issues.
> fix: Ugc Remove async and second id usage

- dGame/dGameMessages/GameMessages.cpp
Enables cars and rockets to actually be able to load images for their preview icons in the inventory.  _does not handle image generation.  This will need to be handled by the end user or a 3rd party._
Tested that, if a user has followed the guide and turned UGCUSE3DSERVICES from 1 to 0, the do not get booted to login for having a rocket or a car with a subkey in their inventory; in this case, the rocket or car will never try to load an image and will always use the default.
If however, UGCUSE3DSERVICES is set to 1, the following behavior is correct as per the live client (and a sample from an old client with a rocket image).
Tested that, given a subkey of `1152921508901867691`, the client expects a file called UserMade/691/01152921508901867691.dds in the UserMade folder and when a dds is …
> fix: Ugc Add subkey for rockets and cars

- README.md
- dMasterServer/MasterServer.cpp
> fix: Onedrive log message

- dGame/dComponents/PetComponent.cpp
Fixes #535. Tested by playing character at Pet Cove who had not completed mission, and then switching to another character who had. Pet would not dig up treasure on the first character, but would on the second. Also took the first character to the Advent Gardens pet bouncer dig and found it was unable to dig (which is desired behavior).
> Fix: Pets can no longer dig treasure without completing Bella Pepper's "Lost Tags" mission

- dGame/dInventory/Item.cpp
Fix a massive memory leak by deleting the doc after we are done using it.  Tested that the memory does not leak in the megabytes everytime you dismantle a model to bricks.
> fix: Models leak

- dDatabase/Tables/CDZoneTableTable.cpp
- dDatabase/Tables/CDZoneTableTable.h
- dGame/Character.cpp
- dGame/dComponents/ControllablePhysicsComponent.cpp
- dGame/dInventory/Item.cpp
- dWorldServer/PerformanceManager.cpp
- dZoneManager/dZoneManager.cpp
- dZoneManager/dZoneManager.h
Allow setting framerate for the zone
Allow setting if pets are allowed in the zone
Allow setting if mounts are allowed in a zone
Allow disabling saving location to a zone
Tested all of these by editing cdclient and changing them then loading a fresh zone
> feat: use more zoneTable options

- dGame/Player.cpp
- dGame/UserManager.cpp
- dGame/dUtilities/SlashCommandHandler.cpp
use case insensitive compare
use character name for kill instead of account name
tested that both still function.
> fix: Slash commands update compares

- dGame/dComponents/PropertyManagementComponent.cpp
fix ugc models so they cannot be picked up on the property at all, as opposed to right now when they disappear and the user loses all their work for mis-pressing a button.
Tested that you can still make a new ugc model, place regular models, edit existing ugc models and trying to pick up an existing ugc model does nothing.  The user must manually dismantle the model in edit mode instead.
> fix: Ugc model pickup

- dGame/dComponents/VehiclePhysicsComponent.h
Yes i should have made this first
no this wouldnt have happened with rust
I have NO clue why the new AddComponent caused this.  I dug into this for about 10 hours and it was specifically having the PossessableComponent go through the new AddComponent and nothing else.  Using the inline variant resulted in the same effect.  The RemoteInputInfo in the previous case was always initialized to 0 0 0 1, whereas with the new AddComponent for Possessable, it was UB.  
Tested that the client no longer logs HAVOK CRASH ON FRICTION multiple times per frame
> fix: UB in remote input info

- dGame/dComponents/RacingControlComponent.cpp
- dGame/dComponents/RacingControlComponent.h
- dGame/dComponents/VehiclePhysicsComponent.h
Tested that with two players, both players see the others time at the end of the race and all other metrics are shown correctly.
Technically the `outBitStream->Write(static_cast<uint16_t>(m_RacingPlayers.size()));` should only be written once but how we do it now it is written as we load players in and this is the cheap option compared to the number of bits we are supposed to waste at the end of races
Removed an unused function and linted the file.  Hide whitespace if you don't want to see those changes.
> fix: Racing end of race leaderboards now work

- dGame/Entity.cpp
Tested that the crate near the venture league now smashes
> fix: nexus tower smashable

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dComponents/DestroyableComponent.cpp
Tested that pets now despawn again after being put away (still no animation)
Tested that Red Blocks builds no longer can stack
> Entity: Fix death behavior of 0

- dGame/dGameMessages/GameMessages.cpp
Fixed off-by-one error in the PlayerReachedRespawnCheckpoint GM bitstream (thanks aron) and removed some unnecessary code that set player rotation and position (which was promptly overwritten by the client anyway).
> fix: respawn rotation

- dGame/dBehaviors/TacArcBehavior.cpp
Tested in crux that enemies attack normally while on the ground, but skeleton engineers use the knockback attack when up on the tower to knock you off.
tested with other enemies around crux to make sure they felt accurate as well.
Also did some other cleanup to make it more readable
Fixes #956
> fix: tacarc not using offset or checking upper/lower bounds

- dGame/UserManager.cpp
Untested.  Should fix not being able to rename a character at character create
> fix: backwards name check

- dGame/dComponents/PropertyManagementComponent.h
- dScripts/BasePropertyServer.cpp
will test later, should allow you to get credit for visiting player A's block yard and player A's other properties instead of just 1 of player A's properties.
> fix: visiting multiple owned by same person

- dGame/User.cpp
- dGame/User.h
- dGame/dGameMessages/GameMessages.cpp
- dNet/ClientPackets.cpp
- dWorldServer/WorldServer.cpp
- dZoneManager/dZoneManager.cpp
fix crash with chat filter
fix ldf_config being empty in database on windows debug
fix windows crashes on shutdown
fix zonemanager crash on shutdown
Tested that the ldf_config column has data in it in the database now on windows debug
tested that you cannot crash the server as per #1335 
tested that no more crashes happen on world shutdown with players in the world on windows
fixes #1335 
fixes #1244
> fix: general crashes

- dGame/dComponents/MissionComponent.cpp
- dGame/dComponents/MissionComponent.h
Tested that new achievements progress exactly once
Tested that already accepted achievements progress as expeected
Tested that tiered achievements only count the progress to the current tier and not the next one as well
Tested that missions that require an item progress as expected
> fix: achievements counting twice when accepted

- dGame/dComponents/RebuildComponent.cpp
- dGame/dComponents/RebuildComponent.h
Fixes #1285 by adding a check to see the remaining quickbuild imagination cost. If the remaining quickbuild imagination cost is not greater than zero, the quickbuild interaction is not cancelled when a player reaches 0 imagination, allowing them to finish the quickbuild correctly.
> fix: Imagination costs that equal your capacity no longer abort quickbuilds unneccessarily

- dGame/dUtilities/SlashCommandHandler.cpp
- resources/worldconfig.ini
Since fixing this bug makes me feel a little like the fun police, I also added a config option to allow a server owner to intentionally retain this bug if they so choose.
> fix: Using 'leave-zone' in Return to the Venture Explorer allows players to return to the original Venture Explorer map

- dGame/dUtilities/SlashCommandHandler.cpp
Players do not need access to leave Return to the Venture Explorer (rttve) via a slash command.  They can leave through the usual method.
Tested that you cannot leavezone in rttve and you can leave other instanced zones
> fix: leavezone allowing players to go from Return to the Venture Explorer to Avant Gardens

- dCommon/GeneralUtils.h
- dCommon/dEnums/StringifiedEnum.h
- dGame/Entity.cpp
- dGame/dBehaviors/BasicAttackBehavior.cpp
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/RebuildComponent.cpp
- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dGameMessages/GameMessages.cpp
- dNet/MasterPackets.cpp
- dNet/WorldPackets.cpp
- dWorldServer/WorldServer.cpp
- tests/dCommonTests/CMakeLists.txt
- tests/dCommonTests/CastUnderlyingTypeTests.cpp
- tests/dCommonTests/dEnumsTests/MagicEnumTests.cpp
This is kind of a grab-bag of miscellaneous changes I've wanted to do. Most of them do not affect functionality, except for one fairly large change which I will elaborate on below.
I've altered the StringifiedEnum::ToString() function to attempt to evaluate as a constexpr. However, doing this requires the use of a poorly-documented compiler flag and might break things. Part of why I'm making this PR is to check how the other compiler builds handle it. If y'all want that stripped out and/or it breaks things, I can do so. Otherwise, everything in here should be pretty non-controversial.
EDIT: Ended up dropping that particular change due to compiler portability issues, as seen in commit 57e274d below. The performance benefit was pretty much purely hypothetical anyway: I couldn't even measure …
> chore: miscellaneous code, formatting, and syntax cleanup

- dZoneManager/Level.cpp
Fixes an issue when players cannot load into Avant Gardens Survival and other script based minigames with more than 1 zone control object in the level files.  (why are there 26 zone control objects in BoNS and AGS)
> fix: more than 1 zone control object causing issues with scripted minigames

- dCommon/dClient/AssetManager.h
Tested that if a file is missing, the service does not halt.
> AssetManager: fix deleting no file

- dGame/dComponents/MissionOfferComponent.cpp
- dGame/dComponents/MissionOfferComponent.h
- dGame/dMission/Mission.cpp
O7fixes an issue where NPCs would offer the incorrect missions which caused odd blocks.  Consolidated logic for mission offering and removed redundant code.
Tested that not having the Find the Sentinels Mission but having the mission Anchor Management complete no longer shows Find the Sentinels for completion instead of Anchor Management.
Tested that 
if both of these missions are active, I can cycle between them instead of having to do one first, and then the other.
Fixes #1360
> fix: Mission offering for NPCs

- dMasterServer/CMakeLists.txt
- dMasterServer/InstanceManager.cpp
- dMasterServer/MasterServer.cpp
- dMasterServer/Start.cpp
- dMasterServer/Start.h
I want to try out ways to spawn the server binaries on a different host at some point, and this would make it easier to swap out the existing implementation without breaking anything or having diffs in too many places.
Also de-duplicates the two places where "WorldServer" is called right now, which seem like slightly out of sync copy-paste code.
> feat: Split out system() calls from the rest of MasterServer

- dCommon/dConfig.cpp
This allows users to override ini config with environment variables. This will cut down the amount of weird pre-processing required for a docker / kubernetes setup even more. For now, we just check the uppercase version of the config key agains the environment (windows is case-insensitive, linux isn't), so e.g. `MYSQL_HOST` can be used as an env var to specify where the DB is at.
> feat: Allow env var override for game config

- dCommon/Diagnostics.cpp
This improves the linux diagnostics code to print the current exception if there is one. This would probably work on windows as well, but this matches the `std::set_terminate` call, and as far as I can tell, the windows code does something else entirely.
c.f. <https://en.cppreference.com/w/cpp/error/exception_ptr>
> feat: get & print std::current_exception

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dCommon/dConfig.cpp
- dCommon/dConfig.h
- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
This introduces a new env var `DLU_CONFIG_DIR` that can be set to be an absolute path or relative to the server binary where dConfig will look for its ini files. This is mostly useful for docker/k8s setups with mounted config files, everything else can keep using the main directory.
> feat: add DLU_CONFIG_DIR env var

- dGame/LeaderboardManager.cpp
It was possible for the query to get the leaderboard info to cause an unhandled exception in WorldServer and crash it. Based on my testing, this one-liner mitigates it, though in the long term handling any potential database exceptions might be useful.
> Fix edge case where leaderboard viewing would cause unhandled exception

- dGame/dComponents/ActivityComponent.cpp
Tested that lobbies do not fill up with half the players allowed.
> fix: joining lobby twice

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dCommon/CMakeLists.txt
- dCommon/Game.cpp
- dCommon/Game.h
- dCommon/Logger.cpp
- dMasterServer/InstanceManager.cpp
- dMasterServer/MasterServer.cpp
- dMasterServer/Start.cpp
- dNet/AuthPackets.cpp
- dNet/dServer.cpp
- dNet/dServer.h
- dWorldServer/WorldServer.cpp
This PR improves graceful shutdown of the server binaries in the following ways:
- Fix signal handling (e.g. SIGTERM, Ctrl-C), so that we do as little as possible in the handler itself. This is mandated by POSIX because handlers might be called while inside functions like printf and it's not safe to call a logger or almost anything in there.
- Flush the logger in more places, including immediately before the server loops and in its destructor.
- Add SIGINT and SIGTERM handling to Auth and Chat.
WorldServer hasn't been updated completely yet, because I haven't gotten around to test that.
> fix: signal handling

- .gitignore
- CMakeLists.txt
- cmake/Utils.cmake
Appends a new option to the specified file which contains the same contents as the old option, but with the updated name specified in the high level cmake.
Tested that I can run the cmake multiple times and a singular extra config option is generated with the same value as was in the previous option.
> feat: Add config update function

- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
Tested that my characters position and data saves on shutdown now and that master no longer hangs on shutdown
> fix: nullptr access for logger in master

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dMasterServer/InstanceManager.cpp
- dMasterServer/InstanceManager.h
- dMasterServer/MasterServer.cpp
- dNet/AuthPackets.cpp
- dNet/dServer.cpp
- dPhysics/dpWorld.cpp
- dPhysics/dpWorld.h
- dWorldServer/WorldServer.cpp
remove not starting if ini's aren't present since everything can run from env vars now
tested running a server with no ini's and the db connector game proper feedback
tested running with only the MYSQL_XXXX configs set as env vars and the server ran perfect and I was able to connect with a client
> fix: don't crash if some configs values aren't present

- CMakeLists.txt
- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dCommon/AmfSerialize.h
- dCommon/GeneralUtils.h
- dCommon/ZCompression.cpp
- dCommon/dClient/AssetManager.cpp
- dGame/Character.h
- dGame/Entity.cpp
- dGame/User.h
- dGame/UserManager.cpp
- dGame/dComponents/ActivityComponent.cpp
- dGame/dComponents/BaseCombatAIComponent.cpp
- dGame/dComponents/BouncerComponent.cpp
- dGame/dComponents/BuffComponent.cpp
- dGame/dComponents/CharacterComponent.cpp
- dGame/dComponents/Component.h
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/PropertyEntranceComponent.cpp
- dGame/dComponents/QuickBuildComponent.h
- dGame/dComponents/RenderComponent.h
- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dGameMessages/GameMessages.cpp
- dNet/AuthPackets.cpp
- dNet/PacketUtils.h
- dNet/ZoneInstanceManager.h
- tests/dCommonTests/dCommonDependencies.h
tests pass
Looked through the codebase for `#include "..` and `(#include <)(.*)(\.h>)` and updated include paths to what we use across the codebase.
> fix: make include paths consistent

- dChatServer/ChatIgnoreList.cpp
- dChatServer/ChatPacketHandler.cpp
- dChatServer/ChatPacketHandler.h
- dChatServer/PlayerContainer.cpp
- dChatServer/PlayerContainer.h
- dCommon/dEnums/dCommonVars.h
- Remove storing PlayerData as a ptr
- Implement mutable and const getters
- add a bunch of constiness
- fix issue where no reply was sent to the client if their ignore list was empty
tests performed:
ignore list - load add remove
friends - load, add (doesnt exist, offline, from both ends), addbff, remove(online, from both ends, remove each offline)
team - create team, leave team, promote to leader change loot option
> chore: Remove pointer management in PlayerContainer

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dEntity/EntityCallbackTimer.cpp
- dGame/dEntity/EntityCallbackTimer.h
- dGame/dEntity/EntityTimer.cpp
- dGame/dEntity/EntityTimer.h
add comments as to why logic may seem confusing.
Tested that Spider queen battle can be completed without crashing and that schooner can also be used without error
> chore: change timers to not use ptrs

- dCommon/PositionUpdate.h
- dGame/Entity.cpp
- dGame/Entity.h
- dGame/UserManager.cpp
- dGame/dComponents/HavokVehiclePhysicsComponent.h
- dNet/CMakeLists.txt
- dNet/ClientPackets.cpp
- dNet/ClientPackets.h
- dNet/WorldPackets.cpp
- dNet/WorldPackets.h
- dWorldServer/WorldServer.cpp
- Add structs to communicate between the various functions so the data can be easily passed around to the correct handler
- Remove code that was dependent on other libraries linking against dNet by using the variables passed into the function instead, inlining the code to the one place it is used (A new issue should be created tracking this code so we can find a proper place for it later) and in one case inlining without a TODO or a struct due to the amount of data needed to be passed between the interfaces, and the fact that Character is a dGame class with multiple serialization types.
Tested that
- I can still load into worlds
- See other player positons update with and without mounts or racecars
- save data is in tact when delivered to my client
- bad words are rejected from civilians …
> chore: make dNet only depend on dCommon libraries

- .env.example
- README.md
- docker-compose.yml
This PR moves the Docker Compose section of the README before the Standalone version and updates `.env.example` and `docker-compose.yml` to require minimal user intervention to get a server up and running.
To try out, follow the new instructions at https://github.com/DarkflameUniverse/DarkflameServer/blob/fix/docker-readme/README.md#compose
> fix: Docker Compose README

- dChatServer/ChatIgnoreList.cpp
- dGame/UserManager.cpp
- dMasterServer/MasterServer.cpp
- dNet/AuthPackets.cpp
- dNet/BitStreamUtils.h
- dNet/MasterPackets.cpp
- dWorldServer/WorldServer.cpp
- tests/dCommonTests/TestLUString.cpp
- tests/dCommonTests/TestLUWString.cpp
since that's the most common lenght
Was doing this on other places, but not the main one.
Tested that things still work
> chore: default size to 33 on LU(W)Strings 

- dGame/Entity.cpp
- dGame/Entity.h
Updated timers to use a clever erase such that we swap this timer with the last one if there are 2 and we arent deleting the last timer.
Fixes an issue where mechs in Avant Gardens Survival wouldn't attack you and probably more.
> fix: Remove pending timer logic

- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
- dWorldServer/WorldServer.cpp
- resources/worldconfig.ini
adds an announcement sent to the system address which had the mismatched FDB to let the developer know they have a mis-matched one.
Tested that if a civilian tries to login without a gm level > developer, they are kicked. Tested that if a GM is found to have a mismatched FDB, they are let in but have an announcement sent to them.
> feat: Add announcement for mismatched fdb

- dGame/LeaderboardManager.h
- dGame/dComponents/BaseCombatAIComponent.cpp
- dGame/dComponents/ControllablePhysicsComponent.cpp
- dGame/dComponents/MovementAIComponent.cpp
- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/PhantomPhysicsComponent.cpp
- dGame/dComponents/ProximityMonitorComponent.cpp
- dGame/dUtilities/SlashCommandHandler.cpp
- dPhysics/dpWorld.cpp
- dPhysics/dpWorld.h
- dScripts/02_server/Enemy/General/BaseEnemyMech.cpp
- dWorldServer/WorldServer.cpp
- dZoneManager/Zone.cpp
Removes the singleton inheritance from dpWorld.
Remove non cstdint data types
Tested that crux prime, nimbus station, avant gardens and nexus tower still use navmeshes and physics and that physics volumes are still collided with.
> chore: remove singleton for dpWorld

- dCommon/dEnums/StringifiedEnum.h
Another export from the test branch. I'll be honest: I just like reference syntax better than pointer syntax.
> chore: Use references instead of pointers in StringifiedEnum.h

- README.md
Add warning about docker-compose on windows, c.f. DarkflameUniverse/NexusDashboard#92
> Add warning about docker-compose on windows

- dGame/Entity.cpp
- dGame/Entity.h
fixes an issue where enemies who would have their faction changed would not update their aggro targets since they will have already been forgotten in the previous iteration.  New version adds all colliding entities, but returns a trimmed list so that an enemy faction can be changed on the fly and not affect targetting for enemies who now have new enemies.
Returning a container not by reference will barely add any overhead since no copy or move is done since ive used copy elision to construct the vector in the previous stack frame instead of this one, so cost increase here is low.  No reference on the id as a LWOOBJID fits in a cpu register so a reference is more expensive than just copying the value.
Tested that stromling mechs and ronin/horsemen in forbidden valley still aggro on spawn …
> fix: faction changes not allowing updated targets

- dGame/dComponents/RenderComponent.cpp
- dGame/dComponents/RenderComponent.h
Noticed I wasn't correctly forwarding the arguments to emplace_back in #1429. It bothered me.
> chore: nitpicks on rendercomponent changes

- dNavigation/dNavMesh.cpp
- dNavigation/dNavMesh.h
- dPhysics/dpWorld.cpp
Moves DetourExtensions.h to the 1 cpp file that uses it and locks down its header to not even expose the navmesh object since nothing has a use for it.
Still compiles and links.
> chore: Remove transitive include for Detour, remove unused fields

- dGame/dUtilities/SlashCommandHandler.cpp
- dScripts/02_server/Enemy/AG/BossSpiderQueenEnemyServer.cpp
- dScripts/02_server/Map/AG/NpcCowboyServer.cpp
- dScripts/02_server/Map/AG/NpcWispServer.cpp
- dZoneManager/Spawner.cpp
Tested that the target next to the plunger gun dude now spawns its target without needing to leave the area if it is spawned
Tested that spiders still spawn in Spider Queen battle
Tested that macros work
> fix: Remove hard coded groups for spawners

- dGame/TradingManager.cpp
- dGame/TradingManager.h
- dGame/dGameMessages/GameMessages.cpp
Tested that someone closing the trade window now echo's this to the other player
> fix: close trade window when one player ends the trade

- dGame/EntityManager.cpp
if we DON'T find it, we want to kill/delete it.  not the other way around where if we find it we try to delete it again.
tested that you no longer crash when trying to login
tested that bird monument issues are fixed
> fix: EntityManager incorrectly inverted statement

- dCommon/GeneralUtils.cpp
- dCommon/GeneralUtils.h
Anonymous namespaces in header files do not actually prevent access to the enclosed functions in corresponding .cpp files and having one here is therefore pointless
> chore: Remove anonymous namespace from GeneralUtils.h

- dCommon/Amf3.h
folding out another one of the AMF3 changes from the way-too-big AMF3 PR
> chore: Update Amf3.h member naming scheme

- dGame/dComponents/BuffComponent.cpp
- dGame/dComponents/BuffComponent.h
Tested that smashes while iterating through buffs or stunning race conditions where you die the same frame the buff is to be removed no longer causes double removals of a buff
> fix: Use set for buff removal

- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dComponents/SkillComponent.cpp
- dGame/dGameMessages/GameMessageHandler.cpp
Made some heap allocated variables that never leave the stack frame into stack-allocated variables.
> chore: Remove unnecessary heap allocations

- dCommon/AMFDeserialize.cpp
- dCommon/AMFDeserialize.h
- dCommon/GeneralUtils.cpp
- dCommon/GeneralUtils.h
- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dGameMessages/GameMessageHandler.h
- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
- dGame/dGameMessages/RequestServerProjectileImpact.h
- dGame/dGameMessages/StartSkill.h
- dGame/dGameMessages/SyncSkill.h
- dWorldServer/WorldServer.cpp
- tests/dCommonTests/AMFDeserializeTests.cpp
- tests/dGameTests/dGameMessagesTests/GameMessageTests.cpp
As part of ongoing raw pointer reduction efforts, convert game messages to use references to raknet bitstreams instead of raw pointers.
> chore: Convert game message bit stream raw pointers to references

- dGame/dComponents/SkillComponent.cpp
- dGame/dGameMessages/DoClientProjectileImpact.h
> chore: Convert DoClientProjectileImpact to use bitstream refs

- dGame/LeaderboardManager.cpp
- dGame/LeaderboardManager.h
- dGame/dGameMessages/GameMessages.cpp
> chore: Convert LeaderboardManager to use BitStream refs

- dGame/dComponents/MovingPlatformComponent.cpp
- dZoneManager/Zone.cpp
- dZoneManager/Zone.h
Speed is used in more waypoints than not so we may as well reduce repeated references.
tested that the data is still loaded as normal in avant gardens
> chore: remove extra speed class

- dGame/dUtilities/VanityUtilities.cpp
Tested that the logs now show the name and lot of the not spawned npc.
> chore: add info to debug logs

- dGame/dComponents/AchievementVendorComponent.cpp
- dGame/dComponents/AchievementVendorComponent.h
- dGame/dComponents/VendorComponent.h
We never set the HasStandardCost flag in the AchievementVendor.
"Why are you calling RefreshVendor again in the most derived class constructor?  Wont the one in VendorComponent call it?"
No because at that point in time, the vftable for the AchievementVendor has not been assigned yet and as such a call to the virtual function is impossible.  We do need the function to be virtual to prevent the regular refresh from going through as the work is unnecessary for this entity
Tested that you can complete missions from the AchievementVendor and still buy still.
> fix: commendation vendor cant accept missions

- dCommon/GeneralUtils.h
- dNet/AuthPackets.cpp
- tests/dCommonTests/CMakeLists.txt
- tests/dCommonTests/ToUnderlyingTests.cpp
Having actually needed to use this helper function fairly extensively for a commit on the PetFixes branch, I propose switching it to use a slightly shorter name that's still descriptive
> chore: Less verbose name for enum underlying type casts

- dGame/dComponents/ControllablePhysicsComponent.cpp
- dGame/dComponents/ControllablePhysicsComponent.h
Tested that players show up as normal on each others screens, tested that money magnet still works with item 8600, tested that gravity still works in Moon Base.
This should also resolve an issue (if one exists) where sometimes gravity or money magnet would not be active for a specific player based on the order they loaded in.  Now the correct data will be sent every time.
> fix: update serialization, remove unused variable

- dGame/dBehaviors/Behavior.cpp
- dGame/dBehaviors/Behavior.h
- dGame/dBehaviors/SkillEventBehavior.cpp
Could remove all the this-> since everything is prefixed with m_, but meh, too much change for this pr, getting rid of the news is a better fix
Tested that GrowingFlowers still have their SkillEvent fired with the correct parameters, gftikitorch works, sharks eating stinky fish still work
> chore: Remove `new`s in Behavior members

- dChatServer/PlayerContainer.cpp
Prevents a bad actor from possibly spamming the server with sequential IDs and allocating a bunch of memory.
Tested that I can still send and receive friend requests.  Tested that I can send and complete a best friend request while the other player is offline
> fix: remove extra access of PlayerData

- dGame/dBehaviors/InterruptBehavior.cpp
Should be 100% live accurate as far as logic and bitstream reads goes.
Tested with all valiant weapons and crux prime weapons (drops from dragons) that combat does not desync and that the client reports the same level and amount of skill deserialize issues as before.
Would like Wincent or the last person who worked on this part of the behavior system to give this a once over due to that guess... and it dating back to pre-foss DLU.
> fix: update InterruptBehavior to current knowledge

- dCommon/GeneralUtils.h
given that fp is only on 2 compilers, it would make sense to only do the custom impl for not those two compilers.
Still compiles on my machine which has gcc-11 and does not error if I insert an error macro inside the if block.
> fix: more restrictive std::from_chars for floating point

- dGame/dComponents/BaseCombatAIComponent.cpp
- dGame/dComponents/PhantomPhysicsComponent.cpp
- dGame/dComponents/ProximityMonitorComponent.cpp
- dGame/dComponents/ProximityMonitorComponent.h
- dPhysics/dpEntity.cpp
- dPhysics/dpEntity.h
- dScripts/02_server/Map/AM/WanderingVendor.cpp
- dScripts/ai/AG/AgBusDoor.cpp
Fixes #1522. Tested by going into AG and checking that the bus raises and lowers in the Sentinel base
> chore: Remove dpEntity pointers from collision checking

- dPhysics/dpEntity.h
Forgot to remove the 'const' on the return types here and only now noticed it. Super nitpicky, but it's not good practice to have 'const' on non-reference returns
> chore: const return oversight

- CMakeLists.txt
Discovered this at work the other day. By default, MSVC treats all volatile variables as if they were atomics on x86 and x64 architectures, and requires this use of an obscure compiler flag to disable this.
https://learn.microsoft.com/en-us/cpp/build/reference/volatile-volatile-keyword-interpretation?view=msvc-170
This is, needless to say, very much not portable and it makes me worried it could potentially cause odd behavior between the platforms. While there's no evidence it has at the moment, I'd rather nip this in the bud. This PR adds said obscure compiler flag to CMake and thus brings MSVC inline with gcc and clang's treatment of volatile in accordance to the C++ standard.
> chore: disable non-standard volatile behavior on MSVC

- dCommon/GeneralUtils.h
tested that Not the Boss of Me progresses normally (its cdclient entry is `7805,11225,11226, 11217, 11220, 11214, 11982, 11987, 11989, 12005, 11999, 12467, 12468, 12469, 12591, 12600, 12609, 14381,16047,16048,16049,16050`
> fix: ignore whitespace in TryParse

- dCommon/Diagnostics.cpp
- thirdparty/SQLite/CppSQLite3.h
Allows this to be caught in our exception handler by name.  Fixes the try catch re-throw to catch any exception if the exception re-thrown does not inherit std::exception.
Tested that replacing a dummy query.bind with a non-existent field
- prints `Caught unknown exception.` when not inheriting from std::exception
- prints `SQLITE3_ERROR...` when inheriting from std::exception
> fix: Add exception inheritance for CppSQLite3Exception, harder try catch re-throw in exception handler

- dScripts/02_server/Map/General/TokenConsoleServer.cpp
- dScripts/02_server/Map/NS/NsTokenConsoleServer.cpp
Tested that turning in bricks in Nexus Tower now correctly plays a sound.  The change in the other script is merely a formality as that path is unused in the Nimbus Station console
fixes #527
> fix: console sound in Nexus Tower

- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/PetComponent.h
swap out the petcomponent precondition expression for an optional
doing this here because the petfixes PR is already big enough
> chore: Convert heap allocation to optional

- CMakeLists.txt
- cmake/FindJSON.cmake
> feat: add nlohmann/json lib

- docker-compose.yml
I initially used the bind mount because it's arguably easier to back up and move around than a volume, but turns out with https://github.com/DarkflameUniverse/NexusDashboard/issues/92 it's nothing we can recommend for Docker Desktop on WSL, which unfortunately is the primary setup newcomers will try this with. So changing the default to be a volume should address that (presumably by hosting the volume within the WSL Docker VM, as opposed to the host NTFS filesystem)
> Use volume for mariadb persistence

- dWorldServer/WorldServer.cpp
fixes an issue where physics entities were not given a chance to be marked as sleeping, causing a initial sleeping calls to be missed and causing objects that collided with one another to not register new collisions since they were sleeping at the time the new collision fired off.
Tested that Brick Fury now corectly aggros the _first_ spawn of enemies near by to him. Tested that the turrets in crux prime now correctly shoot the _first_ wave of enemies that spawn.
> fix: out of order physics updates

- dGame/dUtilities/CheatDetection.cpp
This is not quite implemented correctly and as such needs to be re-tooled to only track if specific gms should track their origin.  This doesnt affect gameplay but stops us from flooding the database with useless info.  Any current solution to check the correct GMs would be too slow to actually use so i am opting to just remove this for a future implementation.
> chore: Remove anti-cheat break savings

- dGame/dGameMessages/GameMessages.cpp
SetCount is cursed...  other methods of freeing the memory should be explored
no longer has ub when deleting an item from the inventory and makes it so if you delete items that are apart of gather tasks, the progress is now properly undone
> fix: use after free in mission progression after removing item from inventory

- dGame/dUtilities/Mail.cpp
fixes an issue where, if a mail of a long enough subject/description/sender would serialize mail to the client, it would crash from trying to write an absurdly large packet.
Tested that mail no longer crashes with string fields that are too long and that mail is still correctly serialized to the client and multiple mails still showed up with their items.
Documented fields that were undocumented and removed extraneous functions
> fix: mail crash from underflow and document variables

- CMakeLists.txt
workaround for #815 
Good enough for now.  Tested that the inverse logic `if(NOT "${CMAKE_SOURCE_DIR}" MATCHES " ")` fails to build in a path without spaces.
> fix: prevent building in a folder which contains spaces

- dGame/dUtilities/SlashCommandHandler.cpp
feat: Command Organization
Description: Changed CommandInfos to be a map rather than a vector, which allows for easy alphabetization of the different commands available when running /help.
Motivation and Context: Found it hard to sort through the list of commands as it was, so this should be helpful for users to find the commands they are looking for.
How Has This Been Tested?: Running my server and using the help command, for it to show the resulting command list in alphabetical order
> feat: Command Sorting

- dGame/dGameMessages/GameMessages.cpp
Platforms that are spawned when the world is joined by others will now be in different positions based on when they loaded in, but now players cannot have the platforms teleport out from underneath them whenever someone loads into a world.
Tested that joining a world with a platform no longer resets it back to the starting position
> fix: moving platforms resetting on each player entering a world

- dGame/dComponents/PetComponent.cpp
- dNavigation/dNavMesh.cpp
- dNavigation/dNavMesh.h
Issue #547 
Description: Modified PetComponents.cpp, dNavMesh.cpp and dNavMesh.h to include a new function nearest point which helps to prevent players from falling off a cliff or an edge when taming a pet. It will instead try to keep the player on the nearest navMesh (terrain)
Motivation and Context: Linked issue from EmosewaMC to work on
Type of Changes: Added new function to dNavMesh and its respective includes in dNavMesh.h. Made changes to petcomponent OnUse (which is used to start a player taming pet interaction).
How Has This Been Tested? : Taming a pet, such as the Goat in Forbidden Valley while on the edge of a cliff, which resulted in keeping the player as close to the edge as necessary to prevent them from falling off. This allows (assuming the camera angle and perspective does …
> fix: Falling Off Edge in Pet Puzzle

- dGame/dUtilities/SlashCommandHandler.cpp
feat: Help Command Pagination
Description: Changed HelpCommand to now be sorted into different pages for commands, which should help to further help users to find the correct commands they are looking for without having to scroll through a list of 92 commands.
Motivation and Context: Recommendation from Aron, and my own experience reading through the /help command list.
How Has This Been Tested?: Running my server and using the /help command will return page 1 of the command list. Running /help 1 will as well, but /help 2 and so forth will return that respective page number of commands (currently 10 commands per page). If a user tries to enter a command higher than the number of pages, it will say it is an invalid page number. Additionally, commands will only show up given the user has …
> feat: Help Command Pagination

- dGame/dUtilities/SlashCommandHandler.cpp
- dGame/dUtilities/SlashCommands/GMZeroCommands.cpp
- dGame/dUtilities/SlashCommands/GMZeroCommands.h
FEAT: Implementing client commands
Description: Implemented a list of commands which are used by the client rather than the server. Essentially made an empty command for the server which parses the command through to the client, which then does its thing (this mostly includes things like emotes and a few config options)
Motivation and Context: Adding the ability to use these commands to continue fleshing out our current command palette and help command.
Type of Changes: Changes made to SlashCommandHandler.cpp to include additional command attributes for client commands, added a declaration in GMZeroCommands.h and definition in GMZeroCommands.cpp
How Has This Been Tested: Running commands in game, which triggers their respective emotes and or other functionality. Additionally, these client …
> Client commands implementation

- dGame/dMission/Mission.cpp
Tested that you always get reputation rewards if they exist.  Confirmed with research that this is what was intended.
> fix: Reward reputation always if possible

- dCommon/LDFFormat.h
- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/InventoryComponent.h
- dGame/dInventory/Item.cpp
- dGame/dInventory/Item.h
Tested that the modular assembly LOTs extra data still saves rockets and cars correctly and loads them as well.
This is necessary for future PRs relating to properties which heavily rely on this feature.
> feat: add remaining item extra save data to saving

- dGame/dComponents/VendorComponent.cpp
tested that random vendors now correctly add items into their inventory instead of adding the next item in line
> fix: vendor item stale reference

- dScripts/CppScripts.cpp
Fixes #746 
Added `scripts\ai\AG\L_AG_SENTINEL_GUARD.lua` to the ignore list in CppScripts.cpp, as it was determined that the lua was not necessary to be included. A note will be made regarding this.
This fix obviously only addresses this single script, not the entirety of Issue #746
Tested that the script is ignored when running debug mode using sharedconfig.ini
no screenshots for you i had witnesses
> fix: Ignore Script L_AG_SENTINAL_GUARD.lua

- dGame/dComponents/RacingControlComponent.cpp
No its not live accurate but i've no clue how live did this after a ton of static analysis.  
Tested that players can no longer use a Dancin' hat or imagination potions to gain imagination at the start of a race.
Tested that after dying, players still cannot use skills at the start of a race
Tested that players can still smash imagination crates, collect orbs, use boost, smash smashables on the track and collect flags without issues
> fix: players using non-car skills in a race

- dScripts/CppScripts.cpp
- dScripts/ai/AG/AgShipShake.cpp
- dScripts/ai/AG/AgShipShake.h
- dScripts/ai/AG/AgSpaceStuff.cpp
- dScripts/ai/AG/AgSpaceStuff.h
- dScripts/ai/AG/CMakeLists.txt
Issue #746 
Splitting AgSpaceStuff into AgSpaceStuff and AgShipShake to match their respective luas.
This is based on their LUA counterparts, rather than the current combination of the two which was previously AgSpaceStuff.
Added AgShipShake.cpp and AgShipShake.h, and incorporated them in CppScripts.cpp.  
Tested by compiling, going to venture explorer, and witnessing the intended shake and explosion fx behaviors. 
Did not mess with lot 33 lego piece, will do that laters
> Chore: split VE script up

- Dockerfile
The current COPY directives in the Dockerfile that add the vanity files have an unintended trailing asterisk, causing only root.xml's contents to be in there under the filename '*'.
This is obviously unintendend as this causes the vanity to be non-functional in the default docker setup.
> fix: Dockerfile vanity COPY

- dChatServer/ChatServer.cpp
- dCommon/Diagnostics.cpp
- dGame/Character.cpp
- dGame/Character.h
- dGame/User.cpp
- dGame/dComponents/BaseCombatAIComponent.cpp
- dGame/dComponents/InventoryComponent.cpp
- dMasterServer/MasterServer.cpp
- dWorldServer/WorldServer.cpp
fixes errors spotted in valgrind when logging into the server
UnEquipItem works fine for sending a proxy, however PurgeProxies unfortunately deletes the item you are unequipping silently, causing a use after free when calling UnEquipScripts.  For now i have moved UnEquipScripts call up so there is no use after free.
Initialized some structures and variables that were used uninitialized.
Checked packet length for incoming packets to ensure we're not reading garbage memory.
Tested that
- I can login and load into Avant Gardens
- Valgrind no longer reports use after free for the purged items
- Valgrind no longer reports reading undefined memory when handling packets of too small of a size or when forwarding a packet to chat server
- Valgrind no longer reports using of uninitialized memory …
> fix: use after free and uninitialized memory

- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dBehaviors/BehaviorContext.h
- dGame/dComponents/SkillComponent.cpp
- dGame/dComponents/SkillComponent.h
From static analysis it appears that the client and server need to be keeping track of their own skillUIds as inside the client, there are GameMessages for CastLocalSkill which increment the client side skillUId counter `0x00d45300` alongside the same tracker being used for tracking the ones the client sends to the server `0x00d44980`.  With no way for the server to actually know the clients actual skill tracker value, I believe it is safe to assume that the two are ok to overlap and you just have to keep track of both.  This PR utilizes a multimap to accomplish this task.  
Tested that battling on Crux Prime using a wormholer, bat lord helm and picking up powerups constantly from boxes does not cause my character to become permanently slowed, nor do I permanently gain as money magnet. …
> fix: skill desync when picking up powerups or casting server side calculations

- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
- dGame/dUtilities/SlashCommandHandler.cpp
- dGame/dUtilities/SlashCommands/GMGreaterThanZeroCommands.cpp
- dGame/dUtilities/SlashCommands/GMGreaterThanZeroCommands.h
Allows moderators to spectate players.
Tested that it works properly with some unwilling guineapigs
> feat: spectate command

- dCommon/dConfig.cpp
- dNet/BitStreamUtils.h
- thirdparty/CMakeLists.txt
This pull request seeks to add a algorithms include in some places to fix a breaking change in g++ 14.
Also adds a precompilier definition to Glang / GCC to make sure strdup exists.
> Fix g++ 14

- dGame/dUtilities/SlashCommandHandler.cpp
- dGame/dUtilities/VanityUtilities.cpp
- dMasterServer/MasterServer.cpp
Tested with logs that queries to get soft and hard cap actually succeed now
Removed some very spammy logs
> fix: master not using table data, remove 2 noisy logs

- dDatabase/GameDatabase/ITables/IAccounts.h
- dDatabase/GameDatabase/MySQL/MySQLDatabase.h
- dDatabase/GameDatabase/MySQL/Tables/Accounts.cpp
- dMasterServer/MasterServer.cpp
Tested that creating accounts through CLI shows the option for setting admin access.
only `y` or `yes` allows for an account to be an admin, anything else results in a civilian account
updating an account now prompts for an updated gm level and updates it accordingly.
> feat: add admin account creation options from cli

- dGame/dBehaviors/BehaviorContext.cpp
- dGame/dBehaviors/DamageAbsorptionBehavior.cpp
- dGame/dUtilities/Preconditions.cpp
Tested that skills which have vfx now properly terminate.
> fix: echo skill cast down to client for some server skills

- migrations/dlu/16_big_behaviors.sql
You can make some big behaviors and TEXT doesn't allow for enough data to be stored.  Changes the column do big text can be stored.
> fix: add larger behavior fields for saving

- dGame/dMission/MissionTask.cpp
Tested that the cooking mission with johnny umami now no longer allows you to lose progress by deleting items.
> fix: Use the correct bit field for checking whether or not to decrement progress

- dWorldServer/WorldServer.cpp
Log no longer prints 100000.000000 and instead prints the correct time delta.
> fix: log in world server main loop

- dGame/dComponents/RacingControlComponent.cpp
- dGame/dComponents/RacingControlComponent.h
Tested that times are now saved, compared and shown on the client in millisecond format.  Tested that better lap times correctly update.
> feat: add millisecond tracking for racing

- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/PetComponent.h
Resolves an issue where item is null but is accessed but not doing that code and instead consulting the EntityManager for a valid Entity, alongside nullifying the m_Owner objectID should the pet be destroyed and timer still exist.
> fix: nullptr crashes in PetComponent AddDrainImaginationTimer and Deactivate

- dDatabase/GameDatabase/MySQL/MySQLDatabase.cpp
makes it so we can adjust many more settings since the segfault only happens in windows debug, why remove the functionality for all users? Tested that windows debug, windows RelWithDebInfo and ubuntu default all build and run without issues (will contact luxaritas about pipe testing)
> fix: use macros so we can use more properties with the mysql driver

- dWorldServer/WorldServer.cpp
pretend you are NinjaOfLU from the hit AAA video game LEGO Universe
please extend the following text with descriptors that bring it to 500 words
"Fixes an issue where deleting 2 characters would crash the game and also fixes an issue where the order of minifigures was incorrect after deleting a character"
ChatGPT:
ChatGPT
Certainly, let’s expand this to a full 500-word description, as if spoken by NinjaOfLU from the LEGO Universe game.
"Hello there, fellow adventurers! I’m here to share some exciting updates that are sure to make your journey through LEGO Universe smoother than ever before. We’ve been hard at work refining the game and making it more stable and enjoyable for all players. Here’s the scoop on the latest fixes!
First up, we’ve squashed a pesky issue that was causing a crash …
> fix: crash on character create screen; character order

- dChatServer/PlayerContainer.cpp
tested that sending an empty packet with this messageID no longer crashes the chat server
> fix: chat server crash

- dCommon/dEnums/eCharacterVersion.h
- dWorldServer/WorldServer.cpp
fixes an issue where the missions were completed prior to a bug fix, causing these items to remain in the inventory.
Tested that players with the mission completed have the item correctly removed from their inventory.
> fix: remove ninjago missions items for completed missions

- dGame/Character.cpp
Tested that removing an arbitrary character now logs the error info.  Will hopefully help track down a bug
> feat: add error reporting for failed charxml

- dCommon/Implementation.h
- dCommon/Observable.h
- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dComponents/DestroyableComponent.cpp
- dGame/dComponents/DestroyableComponent.h
This pull request seeks to add helper classes for observers as well as a way to optionally defer/override an implementation of a method or action.
These classes would in the future help with server-side modding. The observer class is very standard as observers go. Usually you would relay on something like a strategy pattern to switch between implementations — do not think that is quite the right solution here.
In the event of modding through library loading at runtime, they could set their observers and overrides through these classes.
In this pull request are examples of how these classes could be implemented into existing classes. These could be excluded if that would be preferred.
> feat: Observers and deferred implementations

- dGame/dComponents/ModelComponent.cpp
- dGame/dComponents/SimplePhysicsComponent.cpp
- dGame/dComponents/SimplePhysicsComponent.h
- dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.cpp
global fix correcting the initial physics motion state from 0 to 5 (confirmed in client).  packet captures from a few worlds (didnt scan more than 5 files) show that the value for simple physics was either 5 as the default, or 4 for property models, or 1 for property models with behaviors.
properties with pre-built models no longer lag and values of physics types should be correct across the board. Not sure what else this fixes but probably more stuff related to performance
> fix: laggy property models (and probably more)

- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/PetComponent.h
- dScripts/02_server/Map/General/PetDigServer.cpp
- dScripts/02_server/Map/General/PetDigServer.h
Basically title. Original pet treasure variables were Tresure, which was a misspelling. All I did was rename each instance to Treasure, and changed the associated methods as well. 
Tested by opening server and digging pet treasures to ensure nothing was conflicting. Pet treasure digs perform as intended still. 
motivation: clean up code a bit
> Fixed Misspelling for Treasure in PetComponent files

- CMakeLists.txt
idk man stack traces work again
-rdynamic is === -export-dynamic 
the former is the compiler passing the latter to the linker, dont know why the order matters for this one but this works
> fix: stack traces work again

- dGame/Entity.cpp
- dGame/dComponents/PetComponent.cpp
- dGame/dComponents/SwitchComponent.cpp
- dGame/dComponents/SwitchComponent.h
Tested that player activated switches are no longer activatable by pets and are no longer activated by something stepping in the vicinity.
Tested that pet switches have the same behavior as prior.
> fix: Player activated switches

- dNet/AuthPackets.cpp
fixes an issue where the console would halt because we printed a control code which did such
> fix: logging uninitialized memory

- dAuthServer/AuthServer.cpp
- dChatServer/ChatServer.cpp
- dCommon/BrickByBrickFix.cpp
- dDatabase/MigrationRunner.cpp
- dMasterServer/MasterServer.cpp
- dMasterServer/PersistentIDManager.cpp
- dWorldServer/WorldServer.cpp
further removes database specific code from the database.
Tested that all 4 servers hit their catch block with a non-running mariadb instance
Tested that a failed object_id_tracker fetch (i.e. missing table) hit the catch
Tested that a bad migration hit the catch.
> fix: use generic exception catching

- dDatabase/GameDatabase/GameDatabase.h
- dDatabase/GameDatabase/ITables/IUgcModularBuild.h
- dDatabase/GameDatabase/MySQL/MySQLDatabase.h
- dDatabase/GameDatabase/MySQL/Tables/CMakeLists.txt
- dDatabase/GameDatabase/MySQL/Tables/UgcModularBuild.cpp
- dDatabase/GameDatabase/TestSQL/TestSQLDatabase.h
- dGame/dGameMessages/GameMessages.cpp
Tested that trashing, placing for part swap, and crafting a new race car all insert and remove from the database the same as before
> fix: abstract ugc rockets and cars from GameMessages

- dGame/Entity.cpp
- dGame/dComponents/SwitchComponent.cpp
> fix: avant gardens switches

- .github/workflows/build-and-test.yml
- CMakeLists.txt
- CMakePresets.json
- dDatabase/CMakeLists.txt
- tests/CMakeLists.txt
- tests/dCommonTests/CMakeLists.txt
- tests/dGameTests/CMakeLists.txt
we were overwriting the users environment variable with the build directory always, resulting in inis always being placed in the incorrect spot if a preset was specified, or if the user had an environment variable where they stored the inis.
Also, assuming it passes ci, made it so we use the shared library in the binary directory as opposed to the one
mac please
> fix: use current binary directory mariadb shared object and dont override env variable

- dGame/Entity.cpp
- dGame/dComponents/ProximityMonitorComponent.cpp
- dGame/dComponents/ProximityMonitorComponent.h
- dGame/dUtilities/VanityUtilities.cpp
- dGame/dUtilities/VanityUtilities.h
tested that vanity npcs now chat when close, and then on a cooldown
> fix: better vanity checks

- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/InventoryComponent.h
- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
very hacky way to make it so player items are at the very least loaded after they close the news screen.
tested that closing the news screen too quickly no longer causes items in the inventory to be invisible.
performance impact from this is minimal and only happens on the initial login to a character. world transfers are unaffected.
yummy hacky code
> fix: (workaround for client bug) closing news screen too quickly making items not appear

- dGame/dPropertyBehaviors/ControlBehaviorMessages/MoveToInventoryMessage.h
- dGame/dUtilities/Preconditions.cpp
need to find something that uses that precondition
> fix: warnings

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dComponents/BaseCombatAIComponent.cpp
- dGame/dComponents/BaseCombatAIComponent.h
- dGame/dComponents/ControllablePhysicsComponent.cpp
- dGame/dComponents/ControllablePhysicsComponent.h
- dGame/dComponents/HavokVehiclePhysicsComponent.cpp
- dGame/dComponents/HavokVehiclePhysicsComponent.h
- dGame/dComponents/PhantomPhysicsComponent.cpp
- dGame/dComponents/PhantomPhysicsComponent.h
- dGame/dComponents/PhysicsComponent.cpp
- dGame/dComponents/PhysicsComponent.h
- dGame/dComponents/RigidbodyPhantomPhysicsComponent.cpp
- dGame/dComponents/RigidbodyPhantomPhysicsComponent.h
- dGame/dComponents/SimplePhysicsComponent.cpp
- dGame/dComponents/SimplePhysicsComponent.h
- dScripts/02_server/Map/General/CMakeLists.txt
- dScripts/02_server/Map/General/EnemyClearThreat.cpp
- dScripts/02_server/Map/General/EnemyClearThreat.h
- dScripts/CppScripts.cpp
this was supposed to be a small pr
tested that enemies that collide with this phantom collider tether to their spawn point and others tether as before.
> fix: implement enemy clear threat script

- dGame/dUtilities/SlashCommandHandler.cpp
- dGame/dUtilities/SlashCommands/GMZeroCommands.cpp
- dGame/dUtilities/SlashCommands/GMZeroCommands.h
- dNet/dServer.h
- dScripts/02_server/Map/AG/NpcAgCourseStarter.cpp
- docs/Commands.md
Tested in game by running the race and verified that mission 1884 is correctly marked as completed when race is finished
> feat: Remove reinterpret_casts from AG race timer script and add method and chat command to get current server uptime

- README.md
- dMasterServer/MasterServer.cpp
- dServer/Server.cpp
> fix: Create resServer and logs if it doesnt exist and update readme

- dCommon/GeneralUtils.cpp
tested that directories no longer crash the server
> fix: skip non-files for migrations

- resources/sharedconfig.ini
this value being set has no relation to any lag a client has with data.
> fix: remove bandwidth limit

- dCommon/BinaryIO.cpp
- dCommon/BinaryIO.h
- dCommon/FdbToSqlite.cpp
- dCommon/GeneralUtils.cpp
- dCommon/GeneralUtils.h
- dMasterServer/MasterServer.cpp
Tested that cafe corner no longer shows up with the incorrect text and now shows up as cafe corner.
@Xiphoseer said to "just hook up an iterator to the utf8 encoder" so I did just that by reading the string from binary as u8 (because if you try and convert a std::string it uses signed characters which utf8 did not like) and then run that through the exact same function that handled the utf16 to wtf8 conversion.
> fix: use encoding on latin1 strings from cdclient

- dCommon/FdbToSqlite.cpp
- dCommon/GeneralUtils.cpp
- dCommon/GeneralUtils.h
Still converts the cafe name
xipho is required to review this before it is merged.
> fix: use simpler converter for latin1

- dWorldServer/WorldServer.cpp
fixes #1698 
hide whitespace changes
Tested that a packed client no longer gets stuck in an infinite loop trying to calculate the checksum.
Additionally we dont try to process the file unless we actually _found_ one now and exit if one was not found and the option was enabled.
> fix: use correct res path for fdb check

- dDatabase/GameDatabase/MySQL/Tables/Property.cpp
Tested that the property entrance menu no longer crashes under windows debug
> fix: property entrance component optional

- dGame/dGameMessages/GameMessageHandler.cpp
Fixes #529 
Tested that my first attack on world transfers is no longer weaponless.
> fix: first attack being weaponless

- dScripts/CppScripts.cpp
> fix: ignore unused scripts from loading

- dMasterServer/MasterServer.cpp
Tested that we no longer have zombie instances after the process exits main
> fix: eliminate children properly

- dDatabase/GameDatabase/ITables/ICharInfo.h
- dDatabase/GameDatabase/MySQL/MySQLDatabase.h
- dDatabase/GameDatabase/MySQL/Tables/CharInfo.cpp
- dDatabase/GameDatabase/SQLite/SQLiteDatabase.h
- dDatabase/GameDatabase/SQLite/Tables/CharInfo.cpp
- dDatabase/GameDatabase/TestSQL/TestSQLDatabase.h
- dGame/UserManager.cpp
fixes #1746 
Tested that creating a character with an already existing name, and an already existing predefined name is still blocked
Tested that now trying to create a character with a name pending approval is now rejected.
> fix: pending names can be duplicates

- dCommon/dEnums/eInventoryType.h
- dGame/dComponents/InventoryComponent.cpp
- dGame/dComponents/InventoryComponent.h
- dScripts/02_server/Map/AM/AmTeapotServer.cpp
Tested that having 2 stacks of the flowers now still allows you to create the tea.  Tested that 10 in each inventory (vault and items) takes them as before.  logic is additive to the current becuause i am scared of item code
> fix: the wu man tea

- dDatabase/GameDatabase/SQLite/Tables/CharInfo.cpp
SQLite name in use checks currently do not function correctly. Inverting the result of this function causes them to work as intended
> fix: invert sqlite lookup result to fix name in use lookup errors

- dGame/dComponents/MissionComponent.cpp
- dGame/dMission/Mission.cpp
- dGame/dMission/Mission.h
fixes #1749 
Tested that done missions never leave the done xml child
Tested that when accepting as repeatable mission, it does not leave the done child and is correctly setup as its own mission in the cur xml parent
Tested that relogging with this mission active shows the correct rewards in the in-game uis
Tested that other missions are unaffected by the change
Tested that the mission can still be completed and progressed as normal.
Want to test a bit more
> fix: mission states being incorrect after world load

- dGame/Character.cpp
tested that news screen no longer shows up on every other world load
> fix: session flags not being loaded every other world load

- dScripts/BaseSurvivalServer.cpp
Tested that the buff station now waits for a player to build it and is alive for 25 seconds before moving positions fixes #1767
> fix: buff station dying and rotating too soon

- dChatServer/ChatIgnoreList.cpp
- dChatServer/ChatIgnoreList.h
Same values, different namespace and not duplicated
> chore: use client enum packet type instead

- dChatServer/ChatPacketHandler.cpp
- dChatServer/ChatPacketHandler.h
- dChatServer/PlayerContainer.cpp
- dChatServer/PlayerContainer.h
- dNet/ChatPackets.cpp
- dNet/ChatPackets.h
re-do team leave logic to send more accurate messages
Now sends a initial invite response to let players know their invite went through or if it didnt due to an error (they were blocked lol)
Players are still able to leave the team with the same results as before, however now the correct messages are sent to team chats (no fixes for local teams).
closes #1765
> feat: better responses to team actions on server

- dDatabase/GameDatabase/ITables/IProperty.h
- dDatabase/GameDatabase/MySQL/MySQLDatabase.h
- dDatabase/GameDatabase/MySQL/Tables/Property.cpp
- dDatabase/GameDatabase/SQLite/SQLiteDatabase.h
- dDatabase/GameDatabase/SQLite/Tables/Property.cpp
- dDatabase/GameDatabase/TestSQL/TestSQLDatabase.cpp
- dDatabase/GameDatabase/TestSQL/TestSQLDatabase.h
- dGame/dComponents/PropertyManagementComponent.cpp
Fixes #1774
Conducted testing on property changes and confirmed bug after saving button pressed no changes are made to Block yard UI.
I created a new query with `LastSaveUpdate()` under all db files that `UpdatePropertyDetails()`  apper in so that it can be used for the save() button but also for future uses down the line like `UpdatePropertyModerationInfo()` `UpdatePropertyDetails()` or 'SetPrivacyOption()'.
I can commit these changes if wanted but know my original task was to just bind it to save which is only called during `OnFinishBuilding()`
after applying changes tests came back as resolved:
> fix: lastUpdatedTime updating

- dCommon/DluAssert.h
- dGame/dComponents/ModelComponent.cpp
- dGame/dComponents/ModelComponent.h
- dGame/dComponents/PropertyManagementComponent.cpp
- dGame/dComponents/PropertyManagementComponent.h
- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
- dGame/dPropertyBehaviors/PropertyBehavior.cpp
- dGame/dPropertyBehaviors/PropertyBehavior.h
- dGame/dPropertyBehaviors/State.cpp
- dGame/dPropertyBehaviors/State.h
- dGame/dPropertyBehaviors/Strip.cpp
- dGame/dPropertyBehaviors/Strip.h
Have tested that the following behaviors function:
On Interact
Drop Life Powerup
Drop Imagination Powerup
Drop Armor Powerup
Spawn Stroming
Spawn Pirate
Spawn Ronin
Play Sound
Smash
Wait
UnSmash
The model resets its state correctly when entering build mode and ceases playing further Actions
The model is not able to be interacted with if there are zero strips which have an OnInteract next
The model is able to be interacted with when one or more strips have OnInteract next
The model executes only its own actions and does not start other strips actions
The models behaviors do not interfere with each other and operate independently from one another
> feat: Property behaviors partially functional

- dGame/dComponents/PetComponent.cpp
- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
(Fix #1342)
Thanks to @EmosewaMC 's suggestions,
I Created new structure for EmotePlayed with the `Game::MessageType::EMOTEPLAYED` that already exists in `DGame.h`
With the targetID for whom the emote is directed to and the emoteID for what type of emote is played which client handles with locale.xml (I believe atleast).
Then a serialize function was made in the GameMessage class to take advantage of boiler plate headers for serializing and sending.
implementation requires identifying the target through a 'LWOOBJID' of entity that started emote, the emoteID for emote type, and targetID if there is a target given.
For [PetComponent::Command] I forced targetID as 0 since I don't yet know if there are any emotes directed to other entities or if they are all just broadcast. If wanted I can …
> fix: playing an emote not showing on all clients

- dGame/dComponents/ActivityComponent.cpp
- dGame/dComponents/ActivityComponent.h
Fix: #1175
When the `PlayerLoadInstances()` was called it would call `TakeCosts()` to check if an item was taken before loading characters in. The problem with that is `TakeActivityCosts` is used for this exact thing after loading in when player start activity. Current solution is separate TakeCosts into a Check and Take function to be used for either purpose of either in TakeActivityCosts for starting activity or checking ability to pay for activity in PlayerLoadInstance.
> Fix: Double imaginite issue resolved on mini survival games

- dCommon/DluAssert.h
- dGame/dPropertyBehaviors/Strip.cpp
- dGame/dPropertyBehaviors/Strip.h
- dWorldServer/WorldServer.cpp
- dZoneManager/dZoneManager.h
Tested that behaviors with 1 start node and nothing else no longer crash
Tested that behaviors with 1 starting node and an unimplemented behavior no longer crash
Tested that placing 2 strips of actions followed by merging the first placed strip into the second no longer crashes
> fix: property behavior crashes

- dGame/dGameMessages/GameMessageHandler.cpp
- dGame/dUtilities/SlashCommands/DEVGMCommands.cpp
Tested that inspect now logs the object ID and that large inventories no longer have the chance of showing up with less items then there are.
> fix: large inventories and inspect not printing objectID

- dGame/EntityManager.cpp
- dGame/EntityManager.h
checked that the logs no longer have an error about zone control mismatched pointers
not sure yet if we should be ghosting zone control at all in the first place
> fix: don't construct zone control twice on player loadin

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dComponents/PhysicsComponent.cpp
- dGame/dComponents/PhysicsComponent.h
- dGame/dGameMessages/GameMessages.cpp
- dGame/dGameMessages/GameMessages.h
- dGame/dUtilities/Loot.cpp
fixes the slow calls to entity doing 5 lookups for components instead of sending one message.
adjusts quite a few variables to be const or const references
optimizes serialization
consolidate duplicate code
rename CanPickupCoins to PickupCoins since thats what it was doing
> fix: optimizations in Entity

- dGame/Entity.cpp
- dGame/Entity.h
- dGame/dComponents/CharacterComponent.cpp
- dGame/dComponents/CharacterComponent.h
- dGame/dGameMessages/GameMessages.h
- dGame/dUtilities/SlashCommands/DEVGMCommands.cpp
- dNet/WorldPackets.cpp
- dNet/WorldPackets.h
- dWorldServer/WorldServer.cpp
- docs/Commands.md
Move the -s and base features of inspect to the object debugger (this file is present in an unmodified, live client and works as-is)
Updates the components to use StringifiedEnum::ToString instead of printing the raw ID
An example of the window in usage is below. This window can be re-sized, moved around and closed when not in use.
> feat: debug features and implement ObjectDebugger

- tests/dGameTests/dGameMessagesTests/GameMessageTests.cpp
This is a remnant of a reverted change that slipped into a previous PR and no longer makes sense since ServiceType is a uint16_t, not a uint8_t
> Revert uint8_t in game message tests

- dCommon/dConfig.cpp
- dCommon/dConfig.h
- dGame/EntityManager.cpp
- dGame/EntityManager.h
- dGame/dComponents/DestroyableComponent.cpp
- resources/worldconfig.ini
Tested that reloading config picks up on new items to be excluded from drops
tested that uscore is removed from the player now
> fix: hardcore mode uscore dropping and other hardcore mode fixes

- dDatabase/GameDatabase/ITables/IPropertyContents.h
- dDatabase/GameDatabase/MySQL/MySQLDatabase.h
- dDatabase/GameDatabase/MySQL/Tables/Ugc.cpp
- dDatabase/GameDatabase/SQLite/SQLiteDatabase.h
- dDatabase/GameDatabase/SQLite/Tables/Ugc.cpp
- dDatabase/GameDatabase/TestSQL/TestSQLDatabase.cpp
- dDatabase/GameDatabase/TestSQL/TestSQLDatabase.h
- dGame/dComponents/PropertyManagementComponent.cpp
- dGame/dGameMessages/GameMessages.cpp
Tetsed that ugc models are saved and loaded with the correct bits (they showed up correctly in the first place just with weird ids)
> fix: Extend saved ugc id to 64 bits

- dGame/EntityManager.cpp
- dGame/EntityManager.h
- dGame/dComponents/DestroyableComponent.cpp
- resources/worldconfig.ini
tested weird quantities of coins never let you gain money (worst case the player loses a couple coins)
tested that very large quantities of coins drop (client limits to 15 drops per gm)
tested that small quantities are not susceptible to rounding errors
> feat: hardcore limit % coins dropped on death
