DarkflameUniverse/DarkflameServer

dGame/UserManager.cpp
=> Strip carriage return from text files

dZoneManager/Zone.cpp
Reverts DarkflameUniverse/DarkflameServer#44
=> Revert "Try to load from original zone path before a lowercased one"

dCommon/dLogger.cpp, dNet/WorldPackets.cpp
- "Fixed" segfault
- Fixed logger not actually logging time
=> Windows fixes

CONTRIBUTING.md
Added commit guidelines to CONTRIBUTING.md to aid people in writing proper
commits.
=> Update CONTRIBUTING.md to include commit guidelines

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/documentation_improvement.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/installation_issue.yaml, .github/ISSUE_TEMPLATE/performance_issue.yaml
Added issue templates to aid with the structural submission of issues.
=> Add issue templates

dChatServer/ChatPacketHandler.cpp, dGame/dComponents/InventoryComponent.cpp, dGame/dComponents/RacingControlComponent.cpp, dGame/dInventory/Inventory.cpp, dScripts/BossSpiderQueenEnemyServer.cpp, dScripts/ImgBrickConsoleQB.cpp
Fix spelling errors in logging
=> Fix spelling

dGame/Character.h, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/CharacterComponent.h, dGame/dUtilities/SlashCommandHandler.cpp
Uses character reconstruction to swap out minifig parts with commands
=> Allow on the fly minifig editing

dGame/Entity.cpp, dGame/Entity.h, dGame/Player.cpp, dGame/Player.h, dGame/dGameMessages/GameMessages.cpp
Stopped cheaters adding coins to their user that weren't actually present in the world.
=> Patched coin exploit

dGame/Entity.cpp, dGame/dComponents/ControllablePhysicsComponent.cpp, dGame/dComponents/ControllablePhysicsComponent.h, dGame/dComponents/PhantomPhysicsComponent.h
Gravity in Moonbase was broken at some point during the development of DLU and I don't think that it used to work the way I have just fixed it, can anyone think of any other solutions to the problem?
=> Moonbase fix

dAuthServer/AuthServer.cpp, dChatServer/ChatServer.cpp, dCommon/dLogger.cpp, dCommon/dLogger.h, dMasterServer/MasterServer.cpp, dScripts/CppScripts.cpp, dWorldServer/WorldServer.cpp, resources/authconfig.ini, resources/chatconfig.ini, resources/masterconfig.ini, resources/worldconfig.ini
This log was causing confusion and issues when in reality there was no problem present.
=> Add ship shake to not log about being missing

dMasterServer/MasterServer.cpp, dWorldServer/WorldServer.cpp
- MasterServer now respawns ChatServer on crash
- WorldServer now attempts to reconnect to ChatServer
=> ChatServer respawn after crash

.github/workflows/build-and-test.yml, CMakeLists.txt, CMakePresets.json, tests/TestLDFFormat.cpp, tests/TestNiPoint3.cpp
This PR contains:
- A fix for windows builds
- A new CI pipeline for windows
- Updates to `CMakePresets.json`
=> Add windows CI

dGame/UserManager.cpp, dGame/dComponents/ScriptedActivityComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dUtilities/SlashCommandHandler.cpp
Remove the logging of IPs to the console to make it easier to upload logs to Github
=> Remove IP Logging

dDatabase/Tables/CDMissionsTable.cpp, dGame/dMission/Mission.cpp, dScripts/NpcWispServer.cpp
Small change that fixes an off by one error for repeatable mission item rewards
Also: Clarified variable names for Wisp Lee script to match what they are in the NpcWispServer.cpp file
=> Fixed an issue where repeatable missions were not rewarding the items they should be rewarding

CMakeLists.txt, CMakePresets.json, README.md
=> Update CMake minimum requirement

dScripts/BaseWavesServer.cpp
Addressed an issue where all Battle of Nimbus Station time smash achievements were repeatable due to how the missions were handled.  For some reason unknown to me, these specific achievements on a fresh character start off as available and not as accepted which is why the original implementation accepts the mission every time you meet the requirements to complete it.
Previously, every time you beat the time smash time to earn the achievement, the mission would be accepted, whether or not you completed it before.  This caused the issue where you would get the uscore and money again, but not the items.  You wouldn't get the items because this mission has no repeatable item rewards and as such would not grant you any.
Now you can only complete the mission once for money and uscore.  
Started …
=> Fixed Battle of Nimbus Station achievements being repeatable

dGame/Character.cpp, dGame/Character.h, dScripts/NsGetFactionMissionServer.cpp, dWorldServer/WorldServer.cpp
Added logic to set the player flag for joining a faction as was done in live.  Tested on Ubuntu and had zero issues.
=> Added joined a faction flag

dGame/dMission/MissionTask.cpp, dGame/dMission/MissionTaskType.h, dScripts/SGCannon.cpp
Fully implemented all shooting gallery achievements and missions.  Maximum current streak is now kept track of properly as before it was always set to twelve.  I have tested all achievements to be properly working and various daily missions to confirm they were progressing properly.  
Fixes #303 
Fixes #143
=> Fully Implemented Shooting Gallery Mission and Achievement Fixes

dScripts/CppScripts.cpp, dScripts/FvPassThroughWall.cpp, dScripts/FvPassThroughWall.h
Added a mission script for the Friend of the Ninja mission.  Tested on local Ubuntu instance with Windows 10 client and was able to complete the mission only when I had a hood equipped and I passed through a gate.
=> Added script for Friend of the Ninja mission

dGame/dComponents/PropertyManagementComponent.cpp, dGame/dMission/Mission.cpp, dGame/dMission/MissionTask.cpp, dGame/dMission/MissionTaskType.h
With this PR, the Model Pickup and Reputation achievements are correctly tracked and progressed when their actions are done.  Tested on local Ubuntu instance and had no issues.
Fixes #297
=> Implemented Model Pickup and Reputation achievements

migrations/dlu/0_initial.sql, migrations/dlu/1_unique_charinfo_names.sql
Added UNIQUE for charInfo table for names.  Tested creating characters with the same name and had no issues.  Fixes #321 suggestion
=> Added UNIQUE to charInfo table for names

dZoneManager/dZoneManager.cpp
Fixes the ghosting issue in #251
=> fixed ghosting issue

dScripts/NpcCowboyServer.cpp
=> Fix Plunger Gun not being removed from inventory after completing mission

dWorldServer/PerformanceManager.cpp, dWorldServer/PerformanceManager.h, dWorldServer/WorldServer.cpp
Should fix bug causing double enter and exit events
=> Rehook dPhysics to main framerate

dGame/dComponents/PropertyEntranceComponent.cpp
No wonder my server never crashed...
=> Fixed a hard coded database issue

dScripts/CppScripts.cpp, dScripts/Darkitect.cpp, dScripts/Darkitect.h, dScripts/FvFong.cpp, dScripts/FvFong.h, dScripts/NtDarkitectRevealServer.cpp, dScripts/NtDarkitectRevealServer.h
Add the cutscene to play when interacting with Fong
As seen here:
https://www.youtube.com/watch?v=mZk8w1Ru6FM&t=872s
Resolves: #526
=> Fong darkitect

dGame/dComponents/PetComponent.cpp
Similar to RebuildComponent
Resolves #540
=> Add precondition get and set to PetComponent

dWorldServer/WorldServer.cpp
(not that anything can load in the in-game browser anyway)
=> replace the survey link with the repo link

dScripts/AmTeapotServer.cpp, dScripts/AmTeapotServer.h, dScripts/CppScripts.cpp
Resolves #224
Test with:
* no flowers in inv
* not enough flowers in inv
* just enough flowers in inv
* more than enough flowers in inv
=> Add AM Teapot server

dScripts/ActMine.cpp, dScripts/ActMine.h, dScripts/CppScripts.cpp
=> Implement Mine Script for boom trap

dGame/dComponents/RocketLaunchLupComponent.cpp
Get setting from the lvl file instead of cdclient
=> Lup launcher setting from lvl

dGame/LeaderboardManager.cpp, dGame/LeaderboardManager.h, resources/worldconfig.ini
This is a resubmit of https://github.com/DarkflameUniverse/DarkflameServer/pull/288 as original maintainer is no longer active. Contains the fixes I mentioned in the original pull request. 
Has been running on my server for months now with no issue
=> (Resubmit) Leaderboard Updates and Bug Fixes 

dScripts/ActMine.h
missed this, helps quiet compile warnings
=> Fix overrides in ActMine

docker/AccountManager.Dockerfile, docker/brickfix.Dockerfile
Added cURL to brickbuildfix and account-manager docker containers. Now docker should report these as healthy.
=> Fix unhealthy docker containers

dScripts/ActivityManager.cpp, dScripts/ActivityManager.h, dScripts/BaseWavesServer.cpp
Reverts DarkflameUniverse/DarkflameServer#581
=> Revert "Don't give activity loot for Battle of Nimbus Station"

dCommon/dCommonVars.h, dGame/Entity.cpp, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/CharacterComponent.h, dGame/dComponents/InventoryComponent.cpp, dGame/dComponents/PossessorComponent.cpp, dGame/dComponents/PossessorComponent.h, dGame/dComponents/RacingControlComponent.cpp, dScripts/SGCannon.cpp
Use the correct component for possessor
cleanup scripts that were using possessor improperly
Tested racing and shooting gallery, testing GM driving in worlds
everything behaves as it was before
=> breakout possessor from char comp

CMakeLists.txt, dGame/dBehaviors/BehaviorSlot.h, dGame/dComponents/InventoryComponent.h, dGame/dGameMessages/PropertySelectQueryProperty.h, dGame/dInventory/Inventory.h, dGame/dMission/Mission.h, dGame/dMission/MissionLockState.h, dGame/dMission/MissionTask.h, dGame/dMission/MissionTaskType.h, dPhysics/dpCollisionGroups.h
This commit adds 5 Precompiled Headers to dramatically speed up compile time  This PR sped up compile time from 20 minutes system time to 5 minutes system time.
=> Implement Precompiled Headers to speed up compile time

dGame/dUtilities/SlashCommandHandler.cpp
tested testmap command, it works
=> Simplify testmap code

dMasterServer/MasterServer.cpp
Reverts DarkflameUniverse/DarkflameServer#624
=> Revert changes in poor master & world communication

dCommon/dCommonVars.h, dCommon/eItemType.h, dGame/dComponents/InventoryComponent.cpp, dGame/dComponents/InventoryComponent.h, dGame/dInventory/Inventory.cpp
=> Split itemType enum into it's own header

dWorldServer/WorldServer.cpp
Repair issue from PR earlier, crucial fix.
=> Resolve missing RakNet replacement

README.md
Me, since I've started to work on implementing mounts again.
Simon for his work in Reverse engineering the client which has been helping over the years.
Venture Vision and moving platforms/simple movers being two recent things that his RE has helped fix.
moved the special thanks out a header at the suggestion of Xipho and Max, since these people have not directly contributed to the DLU codebase.
made a section under the DLU team recognizing Blaster for the Logo that DLU uses
bumped up the credits header to make formatting make more sense
=> Added Aronwk and Simon to the readme

dGame/dComponents/BaseCombatAIComponent.cpp
Self explanitory.  Its how it was done in live.
=> Override radii only when one is present and not otherwise.

dGame/EntityManager.cpp
if we are deleting entities, and we add an entity to delete, don't throw it out, instead delete it for real
=> Refactor UpdateEntities to not lose items if we add them while processing

dGame/Entity.cpp, dGame/dComponents/BuffComponent.cpp, dGame/dComponents/BuffComponent.h, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/CharacterComponent.h, dGame/dComponents/ControllablePhysicsComponent.cpp, dGame/dComponents/ControllablePhysicsComponent.h, dGame/dComponents/DestroyableComponent.cpp, dGame/dComponents/DestroyableComponent.h, dGame/dComponents/LevelProgressionComponent.h
Tested that things get loaded properly
=> make LoadFromXml usage consistent across comps

dDatabase/MigrationRunner.cpp, dGame/dGameMessages/GameMessages.cpp, dScripts/CppScripts.cpp, dWorldServer/WorldServer.cpp
Cleans up some older log calls that use string concatenation instead of format strings for security.
=> Clean up format logs

.gitattributes
this just tells git to play nice, the .editorconfig already is set to this and everything is formatted to this ~~since linux is the best OS~~
=> standardize line endings

CMakeLists.txt, dGame/dComponents/BaseCombatAIComponent.cpp, dGame/dComponents/MovementAIComponent.cpp, dGame/dComponents/PetComponent.cpp, dGame/dUtilities/SlashCommandHandler.cpp, dNavigation/CMakeLists.txt, dNavigation/DetourExtensions.h, dNavigation/dNavMesh.cpp, dNavigation/dNavMesh.h, dPhysics/dpWorld.cpp, dPhysics/dpWorld.h, dScripts/BaseEnemyMech.cpp, dWorldServer/CMakeLists.txt
This PR moves code for loading and reading navigation mesh data from the navmeshes to a new library to better divide the 2 systems as I plan to expand them.
=> Move Navmesh code away from dPhysics

dCommon/Diagnostics.cpp
This was caught as a warning in CI
=> Fix size_t format marker

CMakeLists.txt, dNavigation/CMakeLists.txt, dNavigation/dNavMesh.cpp, dNavigation/dTerrain/CMakeLists.txt, dNavigation/dTerrain/RawChunk.cpp, dNavigation/dTerrain/RawChunk.h, dNavigation/dTerrain/RawFile.cpp, dNavigation/dTerrain/RawFile.h, dNavigation/dTerrain/RawHeightMap.cpp, dNavigation/dTerrain/RawHeightMap.h, dNavigation/dTerrain/RawMesh.h, dWorldServer/WorldServer.cpp, dZoneManager/Zone.h
Implement partial reading of the `.raw` file type for implementation along side `.hkx` reading in future for dynamic navmesh genereation.
=> Implement terrain file reading to generate navmeshes in the future

README.md
I completely overlooked it, so I thought it was a good idea to mention it in the README.
=> Mention option to use Docker in README.md

.git-blame-ignore-revs, dChatServer/ChatPacketHandler.cpp, dGame/dGameMessages/GameMessageHandler.cpp, dGame/dGameMessages/GameMessages.cpp, dNet/ChatPackets.cpp, dNet/MasterPackets.cpp, dNet/WorldPackets.cpp, dWorldServer/WorldServer.cpp, tests/AMFDeserializeTests.cpp
=> Macro formatting consistency

dGame/Character.h, dGame/dBehaviors/JetPackBehavior.cpp, dGame/dUtilities/SlashCommandHandler.cpp, docs/Commands.md
=> Implement flying command

docker/Dockerfile
=> Dockerfile: Copy dNavigation to build dir

dGame/dGameMessages/GameMessages.cpp, dScripts/MailBoxServer.cpp, dScripts/MailBoxServer.h
Just something I noticed while looking at scripts.  Will test this later.
=> Move mailbox closing to its script

dScripts/CppScripts.cpp
and return early if it's an ignored script
tested that ignored scripts are still ignored and not ignored scripts still load properly.
=> ignore empty.lua and empty scripts

dZoneManager/Zone.cpp
This fix is based on lcdr's luzviewer
https://github.com/lcdr/utils/blob/master/utils/luzviewer.pyw#L111-L113
=> fix loading scene transitions in some older formats

dZoneManager/Level.cpp
this fixes reading in the respawn timer on some old maps
=> fix reading respawn for older maps

dZoneManager/Zone.cpp
fixed referencing https://github.com/lcdr/lu_formats/blob/master/files/luz.ksy#L173-L211
=> Add missing property path checks for old zones

dGame/dComponents/PropertyManagementComponent.cpp, dGame/dGameMessages/GameMessages.cpp, migrations/dlu/6_property_behaviors.sql
Add migration for behaviors.  Also simplify some inserts that previously specified columns.
Tested that the tables get altered correctly, names are set correctly.
Tested that I can place models, both regular and Brick-by-Brick ones and that they get deleted properly.  Tested that picking up models and re-placing them down properly updates them in the tables.
=> Add property behaviors migration

dCommon/dClient/AssetManager.cpp
fix slashes for hasfile for unpacked client checking
Tested with unpacked client on linux
Tested with packed on linux
=> simplify  path fixing for packed vs unpacked

dCommon/dClient/AssetManager.cpp, dGame/dComponents/PetComponent.cpp, dGame/dUtilities/BrickDatabase.cpp
~~**THIS IS UNTESTED**!!!  Unit tests reveal this change worked however an integration test has not been run quite yet.  If someone would like to prop the build and test pet taming please let me know what is needed to address the issue~~
=> Fix Pet Taming causing seg fault

dGame/dComponents/PropertyManagementComponent.cpp
Tested claiming props and they now have the correct default values for name and description that they would have in live
=> Use Property_Path name and description when claiming a property

dZoneManager/Zone.cpp
Fixes #836
tested that all triggers are getting loaded properly when the zone is read in
=> Fix trigger loading

dCommon/Diagnostics.cpp
Improve diagnostics to write the file name and signal to the log file should there be a crash.
Tested that on Linux, a raised supported signal is properly caught and logs are written to the log file.
Testing windows now...
=> Improve Diagnostics logging

dScripts/ActivityManager.cpp
non-functional change, these logs are annoying
If they should just be removed entirely, let me know and I can do that
=> Quiet activity mananger timer logs

dAuthServer/AuthServer.cpp, dChatServer/ChatServer.cpp, dGame/dUtilities/SlashCommandHandler.cpp, dMasterServer/MasterServer.cpp, dNet/dServer.cpp, dNet/dServer.h, dWorldServer/WorldServer.cpp, resources/sharedconfig.ini
I havent tested this yet but @DarwinAnim8or said just uncomment it so yeah ill test in morning unless someone else does
=> Add bandwidth limit

dGame/dUtilities/SlashCommandHandler.cpp, docs/Commands.md
These are unneeded now since the missions now work.
I havent tested anything here but if its really needed ill test that you cant use the commands or something
=> Remove unneeded commands

dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.cpp
This should make the cannon actually super charge its attack speed as well, as it did in live.
This is untested but if someone wants to test this feel free to do so.  Until then I will comment when this is tested.
=> Fix cannon super charge speed

README.md, vanity/CREDITS.md
- README now has proper capitalization for categories in the credits.
- New layout with former contributors moved to below active contributors.
- LEGO Universe credits linked for the special thanks.
- Aronwk properly recognized as DLU team member after mistakenly not included.
- Vanity credits updated to more closely mirror categories in README's credits.
=> Updated README and CREDITS

dDatabase/MigrationRunner.cpp
Caused an issue where a column wasnt properly added to the database.
Tested that migrations run
=> Update sd0 migration name in migration runner

dScripts/02_server/Enemy/AM/AmDarklingDragon.cpp, dScripts/02_server/Enemy/FV/FvMaelstromDragon.cpp
Same as #914 but for the dragons.
Tested that dragons like butter and borborygmus no longer retain their skills through their stuns.
=> Fix dragon stuns

dGame/dComponents/RebuildComponent.cpp
When a QB is done when someone is on a team, given every member mission/achievement credit for doing so
=> Qb team credit

dGame/dComponents/BuffComponent.cpp
Tested with the adventurer hat that this works correctly.
Resolves #918
=> Use new logic for applying speed changes via ApplyBuff

dGame/dGameMessages/GameMessages.cpp
Tested that you no longer can dupe items by selling them in bulk.
=> Fix duping issue with selling

dGame/dGameMessages/GameMessages.cpp, dGame/dInventory/Item.cpp, dGame/dInventory/Item.h
Tested that packages open properly when intended
=> sanity check on opening packages

dGame/dUtilities/VanityUtilities.cpp, dGame/dUtilities/VanityUtilities.h
and make vanity npc use more forgiving
=> Add ldf controlls to vanity npc tools

dGame/EntityManager.cpp, dGame/EntityManager.h, dGame/dComponents/DestroyableComponent.cpp, dGame/dComponents/DestroyableComponent.h
load values once so that it doesn't check every time
don't return, just skip
don't relaad char
waiting on test fixes to be done
=> Hardmode cleanups

dScripts/02_server/Map/AM/AmTeapotServer.cpp
Tested that the behavior of the script mimics live
=> Take flower if it is in the vault

dGame/EntityManager.cpp
=> Don't enable HC on minigame worlds

dCommon/AMFFormat.h
=> Fix warning for overrides 

dScripts/02_server/Objects/StinkyFishTarget.cpp, dScripts/02_server/Objects/StinkyFishTarget.h
Fixes #575 
Tested that the shark now properly spawns and eats the fish.
The issue with the coins spawning is a larger issue that will go unaddressed.
=> Fix stinky fish animation on death

dMasterServer/MasterServer.cpp, migrations/dlu/8_foreign_play_key.sql
add some more utility to the masterserver -a command
fixes #1009
=> fix compatibility with nexus dash

dScripts/CppScripts.cpp, dScripts/EquipmentScripts/CMakeLists.txt, dScripts/EquipmentScripts/StunImmunity.cpp, dScripts/EquipmentScripts/StunImmunity.h
several summons use this script to be immune to stuns
=> add stun immunity script

dCommon/GeneralUtils.cpp, dCommon/GeneralUtils.h, dGame/dUtilities/SlashCommandHandler.cpp
Tested that /lookup sword of fire and /Lookup sword of fire both logged a chat message.
=> Allow case insensitive commands

dScripts/CppScripts.cpp, dScripts/ai/WILD/CMakeLists.txt, dScripts/ai/WILD/WildAmbientCrab.cpp, dScripts/ai/WILD/WildAmbientCrab.h, dScripts/ai/WILD/WildAndScared.cpp, dScripts/ai/WILD/WildAndScared.h, dScripts/ai/WILD/WildGfGlowbug.cpp, dScripts/ai/WILD/WildGfGlowbug.h, dScripts/ai/WILD/WildPants.cpp, dScripts/ai/WILD/WildPants.h
=> Add scripts for a few wild creatures

dCommon/AMFFormat_BitStream.cpp, dCommon/Diagnostics.cpp, dCommon/dClient/AssetManager.cpp, dCommon/dClient/Pack.cpp, dGame/dComponents/RebuildComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dUtilities/Mail.cpp, tests/dCommonTests/AMFDeserializeTests.cpp
Server compiles still.  Most fixes are extra switch statements that were missing or saving return values
=> Resolve all but one compiler warning

dGame/dComponents/VehiclePhysicsComponent.cpp, dGame/dComponents/VehiclePhysicsComponent.h
for the different animation types
=> Add random end of race behavior

README.md
Turns out this just disables the need for the ugc server
=> Update Brick-by-Brick notes

dGame/dGameMessages/GameMessages.cpp
=> Prevent setting over the max value of stats on revival

dScripts/02_server/Map/AG_Spider_Queen/ZoneAgSpiderQueen.cpp, dScripts/02_server/Map/Property/AG_Med/ZoneAgMedProperty.cpp, dScripts/02_server/Map/Property/AG_Small/ZoneAgProperty.cpp, dScripts/BasePropertyServer.cpp, dScripts/ai/PROPERTY/AgPropguards.cpp, dScripts/ai/PROPERTY/AgPropguards.h, dScripts/zone/PROPERTY/FV/ZoneFvProperty.cpp, dScripts/zone/PROPERTY/GF/ZoneGfProperty.cpp, dScripts/zone/PROPERTY/NS/ZoneNsProperty.cpp
Mainly on properties
Tested that the spider queen mission can now be progressed
=> Fix typing of some player flag variables

dNet/PacketUtils.h
Fixes chat server crashes
Fixes #1072
=> Reinforce packetutils writing

dGame/dComponents/RacingControlComponent.cpp, dGame/dComponents/ScriptedActivityComponent.cpp, dGame/dUtilities/SlashCommandHandler.cpp, dGame/dUtilities/SlashCommandHandler.h, dZoneManager/dZoneManager.cpp, dZoneManager/dZoneManager.h
Including return world and what activity ID to use for rewards
Tested that single player racing still works and that proper racing rewards are given
=> Removed some hardcoded logic for racing

dGame/dComponents/RacingControlComponent.cpp, dGame/dComponents/RacingControlComponent.h, dGame/dGameMessages/GameMessages.cpp
Fixes #1048 
Tested that closing the dialog via esc, the x in the top right, or the big red x doesn't exit the race 
Tested that the green check button does exit the race
=> Fix race exit dialogue always exiting

dScripts/02_server/Map/AG/AgLaserSensorServer.cpp, dScripts/02_server/Map/AG/AgLaserSensorServer.h, dScripts/02_server/Map/AG/AgMonumentLaserServer.cpp, dScripts/02_server/Map/AG/AgMonumentLaserServer.h
Fixes #598 
Tested that lasers work when beam is red hot
Tested that no burning happens when there is no glowy doom ray
Tested that the hurt machine starts working again when the laser respawns
=> refactor: removed hardcoded ag laser logic

dScripts/02_server/Map/AM/AmBlueX.cpp
=> fix: update type in am blue x script

dGame/dComponents/VendorComponent.cpp, dGame/dComponents/VendorComponent.h, dGame/dGameMessages/GameMessages.cpp
Tested that I can still buy items from the commendation vendor in Nexus Tower and from a sentinel vendor in Nimbus Station.
=> Fix being able to buy an item from a vendor even if they dont sell it

dGame/Entity.cpp
Time to just get it over with and solve the issues
=> Remove the this null check in get position

dGame/dComponents/RacingControlComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dGameMessages/GameMessages.h, dScripts/02_server/Map/GF/MastTeleport.cpp
- Fixes all incorrect teleports in the game
- remove hacks in mast teleport
- ...
- ......
=> Fix incorrect serialization of SendTeleport

docker/Dockerfile
=> fix: bump gcc container image

dNavigation/dTerrain/RawFile.h, dScripts/ai/ACT/FootRace/BaseFootRaceManager.cpp, dZoneManager/LUTriggers.h
and include fixes that popped up from seemingly nowhere
=> fix: foot race player flag

README.md
Hopefully I did this correctly.
=> Update link to my GitHub profile

dGame/dComponents/PetComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dGameMessages/GameMessages.h, dGame/dUtilities/BrickDatabase.cpp, dGame/dUtilities/BrickDatabase.h
This did not need to be a class.
=> Convert BrickDatabase to namespace

dCommon/NiPoint3.cpp, dCommon/NiPoint3.h, tests/dCommonTests/TestNiPoint3.cpp
=> fix: Nipoint3 Operator+=

dGame/Entity.h, dGame/dUtilities/VanityUtilities.cpp
Don't setup talk for vanity npc's if they are no phrases
noGhosting ldfkey for vanity npc's
=> chore: cleanup some vanity npc logic

dZoneManager/Zone.cpp, dZoneManager/Zone.h
Tested that nothing breaks, also correct some types
=> fix: Properly read in scene metadata

dChatServer/PlayerContainer.cpp
after being invited
Tested that the server compiles and does not crash
=> fix: Limit the number of players that can join a team

dChatServer/ChatPacketHandler.cpp, dChatServer/PlayerContainer.cpp, dCommon/dEnums/dCommonVars.h, dGame/UserManager.cpp, dGame/dBehaviors/BehaviorContext.cpp, dGame/dComponents/RocketLaunchpadControlComponent.cpp, dGame/dComponents/ScriptedActivityComponent.cpp, dGame/dComponents/SkillComponent.cpp, dGame/dGameMessages/GameMessageHandler.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dUtilities/Mail.cpp, dGame/dUtilities/SlashCommandHandler.cpp, dMasterServer/InstanceManager.cpp, dMasterServer/MasterServer.cpp, dNet/AuthPackets.cpp, dNet/BitStreamUtils.h, dNet/ChatPackets.cpp, dNet/MasterPackets.cpp, dNet/PacketUtils.cpp, dNet/PacketUtils.h, dNet/WorldPackets.cpp, dNet/ZoneInstanceManager.cpp, dNet/dServer.cpp, dWorldServer/WorldServer.cpp, tests/dCommonTests/CMakeLists.txt, tests/dCommonTests/TestLUString.cpp, tests/dCommonTests/TestLUWString.cpp
and add methods for reading
remove redundant "packet" from packet reading helpers move write header to bitstreamutils since it's not packet related add tests for reading/writing LU(W)Strings
Tested that it compiles and that you can login and do the basic things related to the changes, such as chat
=> chore: cleanup LU(W)string writing

dGame/dGameMessages/GameMessages.cpp
Tested that you can no longer run slash commands as another online player
=> Strengthen checks for slash commands

dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.cpp, dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.h
Tested that the gallery does not crash anymore when trying to access index 5 of a 5 size vector.
=> fix: Address crash in Cannon Cove Shooting Gallery

dDatabase/Tables/CDLootTableTable.cpp
Missed this step from the previous speedup.
`rollloot` numbers match within margin of error to numbers pre-cache improvement.
=> Loot: Fix rarity sorting

dGame/Entity.cpp
fixes crash, @EmosewaMC can explain
=> fix: adding a proximity monitor when one exists already

dScripts/NtFactionSpyServer.cpp
Tested that NT actually loads now
=> fix: Script unupdated new component

dCommon/dEnums/ePermissionMap.h, dGame/Character.cpp
and remove unused softban perm
RIP DLU beta
=> chore: remove uneeded old perm map check

dDatabase/Tables/CDLootTableTable.cpp
=> chore: remove rarity table debug log

README.md, systemd.example
Added note for running the server as a system service
=> chore: Notes for running as system service

dGame/dGameMessages/GameMessages.cpp
Fixes #1282. Tested by jumping off the cliff repeatedly.
=> Fix: Falling from Spider Cave now smashes you

dChatServer/ChatServer.cpp, dChatServer/PlayerContainer.cpp, dChatServer/PlayerContainer.h
=> fix: ChatServer crash on startup

dGame/dInventory/Item.cpp
fix ninjago and other models not dismantling into bricks due to inconsistent file path
fix crash for lxfml that have scenes
pencil rocket 16582 and skyscraper
The above have been tested and work
=> fix: general issues with dismantling

dDatabase/CDClientDatabase/CDClientTables/CDFeatureGatingTable.cpp
Can now queue into Battle of Nimbus Station
=> fix: gating comparison was in reverse

dGame/dGameMessages/GameMessages.cpp
Fixes #984. Working on more features over in the PetFixes branch, but I figure we may as well just push this one out since it's so simple.
=> fix: pet emotes

dCommon/dEnums/eReplicaComponentType.h, dGame/Entity.cpp, dGame/dComponents/CMakeLists.txt, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/HavokVehiclePhysicsComponent.cpp, dGame/dComponents/HavokVehiclePhysicsComponent.h, dGame/dComponents/InventoryComponent.cpp, dGame/dComponents/RacingControlComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dUtilities/SlashCommandHandler.cpp, dNet/ClientPackets.cpp
since that is it's true name
and there's another VehiclePhysics component that is simply named that
Tested that things still work as expected
there are no functional changes
=> chore: rename VehiclePhysics to HavokVehiclePhysics

dGame/dGameMessages/GameMessageHandler.cpp
this fixes the crafting menu on johny umami not being there on the initial interaction
=> feat: implement handling vendorStatusRequest

dGame/dComponents/LUPExhibitComponent.cpp, dGame/dComponents/LUPExhibitComponent.h
=> fix: LUP Exhibit component type and use delta compression on serialization

dGame/dUtilities/VanityUtilities.cpp
Don't return early if there are no party phrases
=> fix: optional party phrases

CMakeLists.txt, dGame/UserManager.cpp, dGame/dComponents/ActivityComponent.cpp, dGame/dComponents/RacingControlComponent.cpp, dGame/dInventory/Item.cpp, dZoneManager/Spawner.cpp, tests/dCommonTests/TestEncoding.cpp, thirdparty/raknet/CMakeLists.txt
Service compiles on all platforms without extra warnings or errors.
=> feat: Bump standard to 20

dMasterServer/MasterServer.cpp
and try to make resServer as well if it doesn't exist
Tested that this works
=> fix: dont crash if resServer doesn't exist

tests/dCommonTests/dEnumsTests/MagicEnumTests.cpp
=> chore: replace macro with anonymous namespace function

dChatServer/ChatIgnoreList.cpp, dGame/Entity.cpp, dGame/EntityManager.cpp, dGame/UserManager.cpp, dGame/dComponents/QuickBuildComponent.cpp, dGame/dComponents/RenderComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dUtilities/Mail.cpp, dMasterServer/MasterServer.cpp, dNet/AuthPackets.cpp, dNet/ChatPackets.cpp, dNet/MasterPackets.cpp, dNet/WorldPackets.cpp, dNet/ZoneInstanceManager.cpp, dNet/ZoneInstanceManager.h, dNet/dServer.cpp, dWorldServer/WorldServer.cpp
tested that logging in, deleted a char, renaming a char, creating char, and transferring to a zone all work still
=> chore: continue work on removing raw packet reading

dCommon/dEnums/eGameMessageType.h, dGame/dComponents/ActivityComponent.cpp, dGame/dComponents/PropertyManagementComponent.cpp, dGame/dGameMessages/GameMessageHandler.cpp, dGame/dGameMessages/GameMessages.cpp, dNavigation/dTerrain/RawFile.cpp, dScripts/ScriptComponent.cpp
Just changes them to have more helpful information.
=> chore: update noninformative comments to be informative 

dGame/Entity.cpp, dGame/Entity.h
Reverts DarkflameUniverse/DarkflameServer#1416
There's an infinite loading issue in NS that was introduced in this PR
Reverting till it can be resolved
=> Revert "fix: Remove pending timer logic"

.github/workflows/build-and-test.yml, CMakePresets.json
=> chore: Upgrade Ubuntu to 22.04 for CI runs

dGame/UserManager.cpp
Multiple characters would not be allowed to be made since they would both have the name INVALID, that is no longer the case
=> chore: make predefined name unique when the name files are not provided

dGame/Entity.cpp
fixes an issue where powerups wouldn't play effects when picking them up
=> fix: fix no effect playing when picking up item

dNet/AuthPackets.cpp, dNet/AuthPackets.h
=> chore: Change AuthPackets to use BitStream references

dGame/dBehaviors/BehaviorContext.cpp, dGame/dGameMessages/EchoSyncSkill.h, dGame/dGameMessages/GameMessageHandler.cpp
=> chore: Convert EchoSyncSkill to use BitStream references

dGame/dComponents/SkillComponent.cpp, dGame/dGameMessages/EchoStartSkill.h, dGame/dGameMessages/GameMessageHandler.cpp
=> chore: Change EchoStartSkill to use BitStream reference

dCommon/LDFFormat.h, dGame/Entity.cpp, dGame/dComponents/InventoryComponent.cpp, dNet/WorldPackets.cpp, dScripts/ScriptComponent.cpp
=> chore: Change LDFFormat to use BitStream references

dCommon/AmfSerialize.cpp
=> chore: Convert AMFSerialize to use bitstream references

dChatServer/ChatIgnoreList.cpp, dChatServer/ChatServer.cpp, dChatServer/PlayerContainer.cpp, dCommon/dEnums/dCommonVars.h, dGame/EntityManager.cpp, dGame/dBehaviors/BehaviorContext.cpp, dGame/dComponents/RocketLaunchpadControlComponent.cpp, dGame/dComponents/SkillComponent.cpp, dGame/dGameMessages/GameMessageHandler.cpp, dGame/dUtilities/Mail.cpp, dGame/dUtilities/SlashCommandHandler.cpp, dMasterServer/InstanceManager.cpp, dMasterServer/MasterServer.cpp, dNet/AuthPackets.cpp, dNet/MasterPackets.cpp, dNet/dServer.cpp, dNet/dServer.h, dWorldServer/WorldServer.cpp, tests/dGameTests/GameDependencies.h
This is the last of the changes as far as I can tell. I will be testing the combined reference changes in game and will report back on their status.
=> chore: Change dServer and related code to use BitStream references

dGame/Entity.cpp
whole function can probably be removed but im not tryna work on that rn
tested that red blocks still has boxes
=> fix: remove void*

dGame/dComponents/CharacterComponent.h, dGame/dUtilities/Loot.h, dNet/AuthPackets.cpp
Tested that the server builds.
=> fix: Specify path for included files in Loot and CharacterComponent

dGame/EntityManager.cpp, dGame/EntityManager.h
Add a constant reference override to SerializeEntity
=> feat: Provide SerializeEntity constant reference overload

dCommon/dEnums/eWaypointCommandType.h, dGame/dComponents/TriggerComponent.cpp, dGame/dComponents/TriggerComponent.h, dZoneManager/Zone.cpp, dZoneManager/Zone.h
tested that zone loading code loads and reads the correct values using logs.  other ldf data is unaffected as I walked around crux and dragons/apes can still spawn and be killed.
=> feat: add further MovementAI skeleton

dScripts/02_server/Map/General/StoryBoxInteractServer.cpp
tested that a plaque in nimbus station now loses its blue face when interacted with.
=> fix: plaques not giving progress

dGame/dComponents/BaseCombatAIComponent.cpp, dGame/dComponents/MovementAIComponent.cpp
tested that a pet and stromling in nimbus station can still move around
=> fix: movement ai remove goto, do todo, remove unused call

dCommon/GeneralUtils.cpp
=> fix: update if check in object

dCommon/GeneralUtils.h
safer code.  tested that missions still progress
=> chore: update check to check size in loop

dGame/Entity.cpp, dGame/dBehaviors/BehaviorContext.cpp, dScripts/02_server/Objects/AgSurvivalBuffStation.cpp
fixes an issue where the sirens would not be destroyed correctly fixes undefined behavior in buff station
tested that the sirens now correctly stop stunning enemies when they die
=> fix: undefined behavior in scripts and sirens issue

dScripts/02_server/Enemy/AG/BossSpiderQueenEnemyServer.cpp
Tested that every player in the world (just how the live script does it) now has the mission progress instead of just the killer
=> fix: I Can Do It On My Own not being completable for anyone except the killer of the spider queen

dScripts/CppScripts.cpp
Tested that dragons now have their build spawn in front of them
=> fix: add back missing scripts from scripts refactor

dGame/dUtilities/Preconditions.cpp
=> fix: compiler issue on newer gcc versions

thirdparty/SQLite/sqlite3.h
Downloaded the new amalgamation and dropped it in place of our current code.  works fine on the sqlite branch
=> fix: update sqlite

.gitignore
so people can have custom stuff
c.f. https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
=> fix: ignore CMakeUserPresets.json

dWorldServer/WorldServer.cpp
This loop is redundant since we're looking for the file in the client res directory
=> fix: remove dead loop

dGame/Entity.cpp, dGame/Entity.h, dGame/dGameMessages/GameMessages.h, dScripts/02_server/Map/AM/AmSkullkinTower.cpp, dScripts/02_server/Map/AM/AmSkullkinTower.h, dScripts/02_server/Map/General/QbSpawner.cpp, dScripts/02_server/Map/General/QbSpawner.h, dScripts/02_server/Map/NT/NtCombatChallengeServer.cpp, dScripts/02_server/Map/NT/NtCombatChallengeServer.h, dScripts/CppScripts.h
Tested that the NT combat challenge, am skullkin towers and qa wall in avant gardens all function as before.
fixes #1705
=> fix: add child loading

README.md
=> fix: add minimum g++ version

dChatServer/ChatPacketHandler.cpp, dChatServer/ChatServer.cpp, dChatServer/PlayerContainer.cpp, dChatServer/PlayerContainer.h
Tested that database table correctly gets the left world update
#1703 
fixes #666
=> fix: update player container on shutdown

dChatServer/ChatPacketHandler.cpp, dChatServer/ChatServer.cpp, dChatServer/PlayerContainer.cpp, dChatServer/PlayerContainer.h
Tested that the notification will only be sent now when the player has been offline for 20 seconds.
Tested that the friends list does not have multiplying friends list numbers.
Fixes #468
=> fix: online notification playing even when a player hasnt fully logged out

dGame/dGameMessages/GameMessageHandler.cpp
=> fix: weaponless world load

dGame/Character.cpp, dGame/Character.h, dGame/Entity.cpp, dGame/Entity.h, dGame/dGameMessages/GameMessages.cpp, dGame/dGameMessages/GameMessages.h, dScripts/CppScripts.cpp, dScripts/CppScripts.h, dScripts/EquipmentTriggers/CMakeLists.txt, dScripts/EquipmentTriggers/ImaginationBackPack.cpp, dScripts/EquipmentTriggers/ImaginationBackPack.h, dScripts/EquipmentTriggers/ObyxShardPack.h, dScripts/EquipmentTriggers/RubyShardPack.h, dScripts/EquipmentTriggers/TrialFactionArmorServer.cpp, dScripts/EquipmentTriggers/TrialFactionArmorServer.h
tested that trial armor restores you to full health the first time you equip it in a session (logic is gross but it'd be a lot of changes atm to implement that table
tested that the other to coil style backpacks work
tested that respawning with a charged imagination backpack gives the imagination
=> feat: implement rest of equipment scripts

.gitmodules, CMakeLists.txt, dGame/dGameMessages/GameMessages.cpp
since it's unused
plus we will be using mongoose for other things since it works better with game server type things
=> chore: remove httplib 

dGame/Entity.cpp, dGame/dComponents/QuickBuildComponent.cpp, dGame/dComponents/QuickBuildComponent.h, dGame/dGameMessages/GameMessages.cpp
Tested that rebuilds now correctly flash when getting close to smashing
Tested that lots that have is_smashable set, but dont have a destroyable component set get their isSmashable flag applied correctly.
Tested that SendDieNoImplCode is actually correct now
thanks dave
=> fix: flashing rebuilds not flashing and bricks not appearing from templates without destroyable components but with is_smashable set.

dChatServer/ChatPacketHandler.cpp, dChatServer/PlayerContainer.cpp, dChatServer/PlayerContainer.h
fixes an issue where the friends list doesnt update on login (waiting on confirmation this change fixes the issue)
=> fix: friends not updating and using incorrect world

dChatServer/ChatPacketHandler.cpp
Tested that all players cannot show as online anymore
=> fix: friends

dScripts/ai/AG/AgSpiderBossMessage.cpp
Tested that you are no longer shot around like a ping pong ball.
=> fix: incorrect knockback parameters

dCommon/Amf3.h, dScripts/02_server/Map/NS/NsLegoClubDoor.cpp, dScripts/02_server/Map/NS/NsLegoClubDoor.h
Tested that the lego club teleport and starbase 3001 teleports work now both before and after you visit nexus tower
=> fix: lego club teleport

thirdparty/raknet/CMakeLists.txt, thirdparty/raknet/Source/PacketPool.h
=> fix: REMOVEME

dCommon/Amf3.h, dGame/Entity.cpp, dGame/Entity.h, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/CharacterComponent.h, dGame/dComponents/Component.h, dGame/dGameMessages/GameMessageHandler.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dGameMessages/GameMessages.h, tests/dCommonTests/Amf3Tests.cpp
Tested that the message is handled and has the expected result.  Tested that being gmlevel 0 rejected the message and that shooting gallery still tracks misses
=> feat: Entity message handling and a usage of said message handling

dScripts/02_server/DLU/DLUVanityTeleportingObject.cpp
Checked that the npc now jumps and teleports away instead of disappearing
=> fix: avery npc not having animations anymore

dCommon/dClient/AssetManager.cpp, dCommon/dClient/AssetManager.h, dCommon/dClient/Pack.cpp, dCommon/dClient/Pack.h, dCommon/dClient/PackIndex.cpp, dCommon/dClient/PackIndex.h
Better error messages when failing to load packed asset bundles + some general cleanup of the asset bundle loading code
=> feat: Packed asset bundle improvements

dGame/dUtilities/SlashCommandHandler.cpp, dGame/dUtilities/SlashCommands/DEVGMCommands.cpp, dGame/dUtilities/SlashCommands/DEVGMCommands.h, tests/dGameTests/GameDependencies.cpp
tested that it does indeed shutdown the world
=> feat: shutdown command

dDatabase/CDClientDatabase/CDClientManager.cpp, dDatabase/CDClientDatabase/CDClientTables/CDZoneTableTable.cpp, dDatabase/CDClientDatabase/CDClientTables/CDZoneTableTable.h, dGame/Entity.cpp, dGame/dBehaviors/BasicAttackBehavior.cpp, dGame/dComponents/DestroyableComponent.cpp, dGame/dComponents/VendorComponent.cpp, dGame/dMission/Mission.cpp, dGame/dUtilities/Mail.cpp, dMasterServer/InstanceManager.cpp, dWorldServer/PerformanceManager.cpp, dZoneManager/Level.cpp, dZoneManager/WorldConfig.h, dZoneManager/Zone.cpp, dZoneManager/Zone.h, dZoneManager/dZoneManager.cpp, dZoneManager/dZoneManager.h
Made things that dont need to be pointers, not pointers and made things that still want to be a pointer a managed pointer.
Updated some loops to more modern looping syntax for simplicity
Added const to places that made sense to have better apis that are the correct kind of restricted.
A lot of the changes are comments and moving some lines around to group them better.
Changed the CDZoneTableTable to be a namespace to further remove a need for random pointers where it doesnt make sense.
Tested that server still compiles and values match what they did before.  No functional changes :)
=> chore: some zone maintenance

dCommon/dEnums/dCommonVars.h, dGame/UserManager.cpp, dGame/dBehaviors/PropertyTeleportBehavior.cpp, dGame/dComponents/ActivityComponent.cpp, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/CharacterComponent.h, dGame/dGameMessages/GameMessages.cpp, dGame/dUtilities/SlashCommands/DEVGMCommands.cpp, dGame/dUtilities/SlashCommands/GMZeroCommands.cpp
=> feat: Add implementation for visited levels

dGame/EntityManager.cpp
tested that I can see other players leave and join a world and that i no longer see a white screen when loading between worlds
=> fix: Constructing player to themself

dGame/dComponents/PropertyManagementComponent.cpp, dGame/dPropertyBehaviors/Strip.cpp
Tested that enemies despawn upon entering or leaving build mode
=> fix: destroy enemies on entering build mode

dGame/dInventory/Item.cpp
tested that consuming water no longer leaves a mission unable to be completed
=> fix: consuming items not decrementing mission progress

dMasterServer/InstanceManager.cpp, dMasterServer/InstanceManager.h, dMasterServer/MasterServer.cpp
Tested that i can join clones, zones and private instances and that the expected zones are loaded into
=> feat: remove instance pointer management by migrating to unique_ptr

dGame/dMission/Mission.cpp
Tested that mission with multiple collection tasks now save their progress
=> fix: multiple collection tasks in one mission and remove sanity check on mission rewards

dGame/EntityManager.cpp, dGame/dComponents/ControllablePhysicsComponent.cpp, dGame/dComponents/ControllablePhysicsComponent.h, dGame/dComponents/HavokVehiclePhysicsComponent.cpp, dGame/dComponents/HavokVehiclePhysicsComponent.h, dGame/dComponents/PhantomPhysicsComponent.cpp, dGame/dComponents/PhantomPhysicsComponent.h, dGame/dComponents/PhysicsComponent.cpp, dGame/dComponents/PhysicsComponent.h, dGame/dComponents/RigidbodyPhantomPhysicsComponent.cpp, dGame/dComponents/RigidbodyPhantomPhysicsComponent.h, dGame/dComponents/SimplePhysicsComponent.cpp, dGame/dComponents/SimplePhysicsComponent.h, dGame/dGameMessages/GameMessages.h, dGame/dUtilities/SlashCommands/DEVGMCommands.cpp
Checked Controllable, Simple, Base, Phantom that details are present
=> feat: debug for all physics components and fix inspect by ldf key

vanity/atm.xml
thought i'd put one here already, got annoyed when i saw i hadnt
=> crux prime ninjago ruins ATM

dGame/Character.cpp, dGame/dBehaviors/ConsumeItemBehavior.cpp, dGame/dComponents/AchievementVendorComponent.cpp, dGame/dComponents/ActivityComponent.cpp, dGame/dComponents/InventoryComponent.cpp, dGame/dComponents/VendorComponent.cpp, dGame/dGameMessages/GameMessages.cpp, dGame/dInventory/Item.cpp, dGame/dUtilities/Mail.cpp, dGame/dUtilities/Preconditions.cpp, dScripts/02_server/Map/AG/AgCagedBricksServer.cpp, dScripts/02_server/Map/AG/NpcCowboyServer.cpp, dScripts/02_server/Map/AG/NpcWispServer.cpp, dScripts/02_server/Map/AG/RemoveRentalGear.cpp, dScripts/02_server/Map/FV/ImgBrickConsoleQB.cpp, dScripts/02_server/Map/General/TokenConsoleServer.cpp, dScripts/02_server/Map/NS/NsTokenConsoleServer.cpp, dScripts/02_server/Map/NT/NtCombatChallengeServer.cpp, dScripts/02_server/Map/NT/NtDukeServer.cpp, dScripts/02_server/Map/NT/NtVandaServer.cpp, dScripts/02_server/Map/PR/SpawnGryphonServer.cpp, dScripts/02_server/Map/njhub/NjColeNPC.cpp, dScripts/02_server/Map/njhub/NjScrollChestServer.cpp, dScripts/NPCAddRemoveItem.cpp, dScripts/ai/PROPERTY/AG/AgPropGuard.cpp
Tested that some of these sources still take items as expected and that sources that checked for all inventories now take from all as well
=> fix: item exploits

dMasterServer/MasterServer.cpp
=> fix: need to create account twice due to commit latency??

dScripts/02_server/Map/General/ExplodingAsset.cpp
=> fix: why oh why is the aggro radius apart of the enemy

dCommon/dEnums/eMissionState.h, dGame/Entity.cpp, dGame/dComponents/CharacterComponent.cpp, dGame/dComponents/MissionComponent.cpp, dGame/dComponents/MissionComponent.h, dGame/dGameMessages/GameMessages.cpp, dGame/dMission/Mission.cpp, dGame/dMission/Mission.h, dGame/dUtilities/SlashCommands/DEVGMCommands.cpp, docs/Commands.md
UI is a bit laggy for mission but theres a lot of data
=> feat: Mission Component debug
